### ISSUE TITLE
CouldntDecodeError when using from_wav with large wav files

### ISSUE THREAD

**Issue by walkerdb** [jiaaro/pydub#101]
**EDIT:** All tickets related to large audio files and out-of-memory errors are being merged into #135 
  -- jiaaro

Original issue after the break

---

I am running into an issue where loading wav files > ~400mb with AudioSegment.from_wav fails, raising a CouldntDecodeError, with ffmpeg error code 1. Files under this size limit load and process properly.

The files are largely mono, 24-bit and 96kHz, encoded as PCM S24 LE (s24l).

Could this be a memory issue of some kind?

Here is my ffmpeg version data:

```
ffmpeg version N-72680-gf073764 Copyright (c) 2000-2015 the FFmpeg developers
built with gcc 4.9.2 (GCC)
configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enab
le-libcaca --enable-libdcadec --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmfx --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libope
njpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis -
-enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-lzma --enable-decklink --enable-zlib
libavutil      54. 27.100 / 54. 27.100
libavcodec     56. 41.101 / 56. 41.101
libavformat    56. 34.100 / 56. 34.100
libavdevice    56.  4.100 / 56.  4.100
libavfilter     5. 16.101 /  5. 16.101
libswscale      3.  1.101 /  3.  1.101
libswresample   1.  2.100 /  1.  2.100
libpostproc    53.  3.100 / 53.  3.100
```

[Edit]: If it helps I am running Windows 8.1 and using Python 3.4.2

**Comment by jiaaro** [comment]
It *might* be a memory issue. `AudioSegment` objects keep the entirety of the audio data in RAM as a `bytestring` for the life of the object.

But, I don't think it is. `CouldntDecodeError` is only raised in one place in the codebase: when `ffmpeg` returns an error status code. You can find out the specific ffmpeg command being used by enabling logging (as [detailed here](https://github.com/jiaaro/pydub#debugging)).

Manually running the ffmpeg command that pydub is using may shed some light on the issue. At the very least, it'll print out the full error.

**Comment by walkerdb** [comment]
Thanks for the info! Running the ffmpeg command manually somehow results in a successful conversion.

Here was the original command as built by pydub:
```
ffmpeg -y -f wav -i C:\Users\dev\AppData\Local\Temp\tmpssmy1p2_ -vn -f wav C:\Users\dev\AppData\Local\Temp\tmpvufv8uv6
```
To run the code manually on a single failing file, I instead pointed ffmpeg directly to the source file (instead of its internally-used temp file), and set the output directory as my desktop:

```
ffmpeg -y -f wav -i C:\Users\dev\path\to\file.wav -vn -f wav C:\Users\dev\Desktop\output.wav
```
This ran successfully, which seems to suggest that the issue is either with pydub's temporary file, or something to do with how windows handles its appdata temp folders. Do either of those possibilities sound feasible?

**Comment by walkerdb** [comment]
Looking at my AppData temp directory, I can still see the temp input files from pydub's failures. They are all empty (0 kb).

**Comment by jiaaro** [comment]
Ohhh... Is the temp file on a different partition with a relatively small size? Or that temp files have a maximum file size?

This StackOverflow page may be worth a look http://stackoverflow.com/questions/1683831/limitations-of-temp-directory-in-windows

**Comment by walkerdb** [comment]
After looking at this for a while I can't for the life of me figure it out. I ended up just calling ffmpeg directly from a subprocess to finish the remaining large files, using mutagen for metadata management.

For posterity, the issue has something to do with pydub failing to write the proper data to a temp file given sufficiently large filesizes, and possibly only affects windows machines. The error occurs both in python 2 and 3.

**Comment by jiaaro** [comment]
I wonder if [this line](https://github.com/jiaaro/pydub/blob/master/pydub/audio_segment.py#L319) is part of the problem - How much RAM do you have in the machine that is exhibiting the issue?

**Comment by walkerdb** [comment]
That could be where the failure is happening, but I don't think limited ram is the issue - I have 16 gigs. Unless the program only has an os-limited portion to make use of?

I may try running some debugs later tonight and see if I can narrow down a failure point.

**Comment by jiaaro** [comment]
@walkerdb did you learn anything more about this issue?

**Comment by jiaaro** [comment]
Closing because I'm merging all related tickets into #135
