### ISSUE TITLE
Export "parameters=" does not processed, if file type is "wav"

### ISSUE THREAD

**Issue by koef** [jiaaro/pydub#103]
Hello. I need to apply some parameters for my exported file
I do this:
trimmed_file.export(outfile, format="wav", parameters=["-ar", "8000", "-ac", "1"])

File is created, but convertion parameters (and Debug) does not work, if type of convertible file is "wav". I think it's because return point earlier applying parameters:

        # for wav files, we're done (wav data is written directly to out_f)
        if format == 'wav':
            return out_f

Thank you!

**Comment by jiaaro** [comment]
the parameters keyword argument allows you to specify ffmpeg command line arguments - for wave files pydub does not use ffmpeg.

However if you want to export a wave at 8k mono:

```python
trimmed_file.set_frame_rate(8000).set_channels(1).export(outfile, format="wav")
```

**Comment by koef** [comment]
Thank you, I already figured out and did just that :)
