### ISSUE TITLE
fade: an interesting bug (and fix)

### ISSUE THREAD

**Issue by lepinsk** [jiaaro/pydub#104]
Hey @jiaaro,

I've been testing the fade function – with a worst-case-scenario type audio clip – and I've found something interesting.

I grabbed a 3-second 1000hz tone from a [sine waveform generator](http://www.audiocheck.net/audiofrequencysignalgenerator_sinetone.php), and I'm using pydub to clip a segment out of the middle (to ensure this tone is just 0 → 1000hz → 0). As expected, writing this clipped segment out to file as-is results in a file with a poppy start/finish. (I was trying to figure out was what the minimum fade lengths were to avoid this issue.)

16ms works fine as a fade-in value; the beginning isn't the real problem. The end of the file, though, seems to require a fade around 128ms to avoid any popping; below this you end up hearing a fade out that terminates in a pop, with the effect worsening as your fade length shortens. I don't know if this is truly a bug, or simply a limitation of how the fade function works.

What I did discover, though, is that running the clip through a short fade out (even 16ms) a few times *does* resolve the pop. Here's some demo code:

```python
from pydub import AudioSegment

tone_segment = AudioSegment.from_file("audiocheck.net_sin_1000Hz_-3dBFS_3s.wav")
tone_segment[400:1600].fade_out(16).fade_out(16).fade_out(16).export("16ms-fade-repeated.wav", format="wav")
tone_segment[400:1600].fade_out(16).export("16ms-fade.wav", format="wav")
tone_segment[400:1600].export("no-fade.wav", format="wav")
```

**Comment by jiaaro** [comment]
I did the following experiment and I noticed something interesting: If you append silence it sounds correct.

```python

from pydub import AudioSegment
from pydub.generators import Sine
from pydub.playback import play

tone_segment = Sine(1000).to_audio_segment(duration=3000)

tone_with_fade = tone_segment[400:1600].fade_out(16)

# has pop at the end
play(tone_with_fade)

# no pop at the end (10ms of silence appended)
play(tone_with_fade + AudioSegment.silent(duration=10))
```

I think this must have to do with the playback mechanism

**Comment by lepinsk** [comment]
Hmm, interesting -- I guess it was likely always going to be the case that this issue is really about how very fast changes like this are reproduced in playback.

I've taken a look at the resultant waveforms from my own demo case – the 16ms one and the 16ms * 3 one, and it looks like running ```fade_out``` over the same final 16ms repeatedly arguably does the same thing that adding a tiny buffer of silence does: it increases the gap between *any* sound and the end of the recording.

![screen shot 2015-06-23 at 10 24 02 pm](https://cloud.githubusercontent.com/assets/154543/8323252/95156ddc-19f6-11e5-84a2-ab2de67e0e0c.png)

Anyway, thanks for the thoughtful response. I'll close this issue.
