### ISSUE TITLE
pydub.utils.mediainfo() doesn't support songs with spaces in the name

### ISSUE THREAD

**Issue by sonic2kk** [jiaaro/pydub#106]
If you have a song such as "Bad Religion - Generator.mp3", when calling mediainfo('Bad Religion - Generator.mp3') on it you'll get an error saying something like:

"Argument 'Religion' provided as input filename, but 'Bad' was already specified.
{}"

Just a complete guess from a skim through the source code, but "command.split()" is what I think is causing the issue. I understand why it's used, but I'm thinking it could be causing the problem. I might be way off, I just quickly looked at the source.

I couldn't see this in the issue tracker anywhere. My goal is to get song metadata and then export the song with the same tags the original file had. I'd prefer to do everything inside of PyDub and not have to use an external library such as Mutagen.

**Comment by jiaaro** [comment]
Hey, yeah I believe you've found a bug

**Comment by jiaaro** [comment]
Ok, I've fixed the issue – Also generator is a great song, brings back memories of my childhood :)

**Comment by sonic2kk** [comment]
Awesome, thanks! :)
