### ISSUE TITLE
MemoryError: Clean up tmp files used in MPEG

### ISSUE THREAD

**Issue by jazzmes** [jiaaro/pydub#109]
**EDIT:** All tickets related to large audio files and out-of-memory errors are being merged into #135 
  -- jiaaro

Original issue after the break

---

This is related to memory issues mentioned.
Importing from a file fails to somewhat larger files leaving some temporary files behind.

I can handle this failure in my code, but I am not able to clean up the temporary files used in the ffmpeg call in the AudioSegment.from_file method. The AudioSegment.from_file._from_safe_wav(output) is crashing with a MemoryError and thus the unlink calls are skipped. In turn I eventually run out of space.

Can you catch the exception in order to clean up the temporary files?

Thanks,
T

**Comment by jazzmes** [comment]
If you agree with that I can do a pull request.

**Comment by jiaaro** [comment]
that makes sense yeah - I would accept a pull request as long as it is reasonable and has tests (I've accepted most PRs so far :smile: )

**Comment by jiaaro** [comment]
Closing because I'm merging all related tickets into #135
