### ISSUE TITLE
AssertionError on _sync method on audio_segment.py

### ISSUE THREAD

**Issue by smaniotto** [jiaaro/pydub#113]
While concatenating two segments with different frame rates.
First segment with 44100 and second one with 24000.

Traceback:

  >File "<path_to_file>", line 27, in merge_segments
    merged_segments += AudioSegment.from_mp3(segment)
  >File "<...>/venv/lib/python2.7/site-packages/pydub/audio_segment.py", line 200, in __add__
    return self.append(arg, crossfade=0)
  >File "<...>/venv/lib/python2.7/site-packages/pydub/audio_segment.py", line 704, in append
    seg1, seg2 = AudioSegment._sync(self, seg)
  >File "<...>/venv/lib/python2.7/site-packages/pydub/audio_segment.py", line 287, in _sync
    assert(len(seg2) == s2_len)

**Comment by jiaaro** [comment]
This is part of the same bug as #83 I think that assert needs to be a tad more permissive since it fails whenever you are working with 2 files with frame rates that aren't even multiples

**Comment by smaniotto** [comment]
Yes, thanks for the reply. When I was debugging it really seemed like a rounding issue when trying to convert to the maximum frame rate among segments. For now, I'm performing this frame-rate-conversion step before merging files, so basically it'll skip the conversion inside the _sync method and the asserts will pass. Btw, thanks for the library, this is gold!
