### ISSUE TITLE
Slice audio

### ISSUE THREAD

**Issue by freeleefly** [jiaaro/pydub#118]
I tried `song_x2 = song[::2]`
it doesn't work like what I thought
`song_x2` is almost equal to `song`

check the code , it just works like 
`first_10_seconds = song[:10000]`

`last_5_seconds = song[-5000:]`

I really hope it will add that.

**Comment by jiaaro** [comment]
what do you expect `song[::2]` to return? an an audio segment with every other sample removed (so a quick and dirty double speed)? That would be keeping with the string/list behavior, but I don't know if it makes sense for audio.

**Comment by freeleefly** [comment]
Yes ,it makes music really bad if taking a quick and dirty double speed.
I don't know if you have heard Podcast through Overcast or other apps. That apps have a function what can speed the audio stream which really save time for me

reply on email cant be seen?

So i want to try How to realize it . For the dialogs or reading books，double speed seems not very that bad.
finaly.i use matlab double it.it sounds funny....

yeah, I think maybe pydub really needn't this attribution. My fault

Sorry about mypoor English too

Did I make sense about what I said ?

**Comment by jiaaro** [comment]
The main problem with double-speed is that it causes a pitch shift (voices sound like chipmunks, etc). But, this may interest you: https://github.com/jiaaro/pydub/blob/master/pydub/effects.py#L38

It's an undocumented first attempt at a speed-up function. Works like:

```python
from pydub import AudioSegment
sound = AudioSegment.from_file("/path/to/mysound.wav", format="wav")

# returns a sound that is 25% faster, but without pitch shift
faster_sound = sound.speedup(playback_speed=1.25)
```

It works by throwing away larger chunks – instead of every other sample, it throws away chunks of 0.15 seconds at a time. You can configure the chunk size too. Larger chunks have less audible artifacts, but you can lose bigger pieces (when you get above 0.25, you can lose some short words completely, like "a" or "it")

**Comment by freeleefly** [comment]
Wow,you really make it happen.Thanks

Actually.after that i find a simple way to realize it. The built-in(?) module `Wave` can works like that:
```python
import wave

with wave.open(r"origin.wav",mode = 'rb') as wav:
	params_1 = wav.getparams()
	framerate = wav.getframerate()
	frames_read = wav.readframes(wav.getnframes())

with wave.open(r"output.wav",mode = 'wb') as wav_2:
	wav_2.setparams(params_1)
	wav_2.setframerate(framerate*2)// multiplied by some number to speedup or slowdown
	wav_2.writeframes(frames_read)
```
i will try them both to find a better way.
But it only works on `.wav`, but `pydub` can do other format, doesn't it?

**Comment by jiaaro** [comment]
yeah pydub will (assuming you have ffmpeg installed) allow you to open and save other formats.

Also note: arbitrary frame rates (like 23745) may not play back correctly in all audio players.

some standard frame rates are 11025, 22050, 44100 (cd), and 48000 (dvd)
