### ISSUE TITLE
MIDI file (read, or convert)

### ISSUE THREAD

**Issue by arnaldorusso** [jiaaro/pydub#121]
Is there any possible way to integrate MIDI files management inside `pydub`?
If so, let me know how could be the best practice or the better way to do so.

Cheers.

**Comment by jiaaro** [comment]
pydub doesn't work on midi data directly, but I [posted a gist](https://gist.github.com/jiaaro/339df443b005e12d6c2a) a while back showing how you could produce an audio file from midi data (with the help of a midi library called "mido")

Hope that helps :)

**Comment by arnaldorusso** [comment]
Thank you so much @jiaaro for posting your solution!
Please, let me know if there are any problems while implementing it inside our modules for converting .midi to .wav at [DataSounds](https://github.com/DataSounds).

Cheers!

**Comment by jiaaro** [comment]
feel free to use anything you want from my gist :)
