### ISSUE TITLE
Possible Buffer for Large Objects

### ISSUE THREAD

**Issue by MaxLFarrell** [jiaaro/pydub#124]
**EDIT:** All tickets related to large audio files and out-of-memory errors are being merged into #135 
  -- jiaaro

Original issue after the break

---

I have to process massive 32-bit 44.1kHz files (over 3gb). Is there any way to feed AudioSegment.from_wav the raw data from the file through a buffer?

**Comment by nelsonw2014** [comment]
This. I'm trying to split 1 hour MP3s, and your library memory errors because it doesn't buffer the read.

**Comment by jiaaro** [comment]
Pydub does not presently support streaming operations, but if you can break the data into chunks first, manually, you can instantiate audio segments using the chunks of raw data.

```python
raw_wave =  wave.open(…)
while  raw_wave.tell() < raw_wave.getnframes():
    # read 100k frames (around 1MB for stereo 32-bit audio at 44.1k)
    sound = AudioSegment(
        data=raw_wave.readframes(100000),
        sample_width= raw_wave.getsampwidth(),
        frame_rate=raw_wave.getframerate(),
        channels=raw_wave.getnchannels(),
    )
    # do stuff with sound…
```

In practice this may or may not be worth the trouble. Most pydub users with large files have opted to just run on 64-bit python with ample RAM (probably 16GB+ in your case).

`AudioSegment` instances contain the audio data itself. They function similar to strings - the data is stored in a single continuous block of memory (on python 2, it's actually stored as a bytestring).

A `StreamingAudioSegment` would be possible to implement for most operations, but given the amount of RAM in modern machines, giving the job more memory is easy enough and nobody has tackled that project. If computers continue to have more and more memory, it's possible that nobody will. 

One place it could make a big difference is on servers. Any company running pydub on EC2 (or similar) with large audio files would have a strong incentive to avoid spiky RAM use.

**Comment by jiaaro** [comment]
Marking this with the `todo` label.

Specifically, todo: Try implementing the `StreamingAudioSegment` class - a parallel implementation of `AudioSegment` (which may use `AudioSegment` internally?) which provides the same interface/methods, but does not load the complete audio into RAM.

If there are significant roadblocks there, perhaps just utilities which do things similar to the `while` loop I mentioned above.

**Comment by jiaaro** [comment]
Closing because I'm merging all related tickets into #135
