### ISSUE TITLE
IPython Audio display objects

### ISSUE THREAD

**Issue by nicktimko** [jiaaro/pydub#127]
IPythaupyter Notebook has an [`IPython.display.Audio` object](https://ipython.readthedocs.org/en/stable/api/generated/IPython.display.html?highlight=display#IPython.display.Audio) that can produce a little audio player in the notebook. Any interest in adding a `_repr_*` function to yield one?

Doing it all the time might be really annoying (extremely small clips are useless, large clips might take a long time to dump/display), maybe add some conditionals?

Alternatively, add some method/property to yield an `Audio` object (`AudioSegment.nb`)?

I could bang out something, let me know if it'd be welcome though.

**Comment by jiaaro** [comment]
I think that'd be great :)

**Comment by jiaaro** [comment]
`AudioSegment` objects contain their audio data (they're not lazily evaluated), so there is no performance penalty for accessing or playing them.

My only concern about `__repr__()` would be make sure it is still useful for non-ipython-nb users (like the regular python interactive shell).

**Comment by nicktimko** [comment]
IPython's `_repr_*` functions exist along side `__repr__`. When the notebook has an object it wants to represent, it checks for various methods (forgot the exact precedence) like `_repr_html`, `_repr_png`, etc. and if none are found it reverts to `__repr__`

**Comment by jiaaro** [comment]
great, I think that would be a useful thing to have :)
