### ISSUE TITLE
Why I can't write 'comment' content to the mp3 file as well as 'artist', 'album'?

### ISSUE THREAD

**Issue by pendave** [jiaaro/pydub#136]
So frustrated...
Why I can't write 'comment' content to the mp3 file as well as 'artist', 'album'?

song.export("mytest1.mp3", format="mp3", tags={'artist': 'com', 'album': "Des O'Connor - 123 O'Leary", 'comments': 'nice!!!!'})

Is it something wrong? Or bug?

**Comment by jiaaro** [comment]
According to [wikipedia's page on ID3 tags](https://en.wikipedia.org/wiki/ID3#Layout) the correct name of that tag is "comment" (not "comments").

I also found this ticket in the ffmpeg bug tracker: "[comment metadata doesn't show on iTunes](https://trac.ffmpeg.org/ticket/3922)" – which is the underlying technology that writes the tags.

You may also want to try [mutagen](https://mutagen.readthedocs.org/en/latest/), a much more full-featured library focused specifically on ID3 tagging

**Comment by pendave** [comment]
Thank you so much.

**Comment by matti777** [comment]
Ran into this too. Looks like its by design from ffmpeg side? https://wiki.multimedia.cx/index.php/FFmpeg_Metadata (doesnt list 'comment' for MP3)
