### ISSUE TITLE
Cant inherit properly

### ISSUE THREAD

**Issue by olivierpons** [jiaaro/pydub#139]
From my question [here](http://stackoverflow.com/questions/37098835/how-to-force-to-a-class?noredirect=1#comment61740451_37098835) the function _spawn() should return

`self.__class__(data=data, metadata=metadata)`

but it unconditionally returns a bare-bones AudioSegment instance:

`return AudioSegment(data=data, metadata=metadata)`

And this way we can't easily make inheritance of the `AudioSegment` class

**Comment by dhke** [comment]
I was just going to comment back on SO. 

The [relevant change](https://github.com/jiaaro/pydub/commit/40bd30c81e12664d849de78fcf8bd43359d16c72) has already been merged to master.

jiaaro might want count this as "-1 day reaction" time to a feature request ...

**Comment by olivierpons** [comment]
Thank you very much and congratulations for this amazing work!

**Comment by jiaaro** [comment]
it was an easy change to merge :) very small, easy to understand, and (at least in terms of existing functionality) already covered by tests
