### ISSUE TITLE
Setting exact bitrate for Mp3 file

### ISSUE THREAD

**Issue by nournia** [jiaaro/pydub#142]
I've tried to change bitrate of this [sample mp3 file](http://www.stephaniequinn.com/Music/Canon.mp3):

    audio = AudioSegment.from_file('Canon.mp3')
    audio.export('Canon2.mp3', bitrate='16k', format='mp3')

but it seems that resulted audio file is in '32k' bitrate:

    mediainfo('Canon2.mp3')['bit_rate']
    32022

I'm using `ffmpeg` for conversion and I've tried setting codec parameter which didn't help:

    audio.export('Canon2.mp3', bitrate='16k', format='mp3', parameters=['-codec:a', 'libmp3lame'])

**Comment by jiaaro** [comment]
@nournia the minimum bit rate allowed by the mp3 format is 32k (at least for mpeg-1 layer 3, which is the only variant really worth using, the other options don't allow high enough sample rates to capture high frequency content)

See https://en.wikipedia.org/wiki/MP3#Bit_rate

**Comment by nournia** [comment]
So, it is not possible to make 16k mp3 files?
I mean, I've seen lots of them and they were totally audible. Isn't there any approach for generating them? Maybe something like ffmpeg's optional `strict` mode?

**Comment by jiaaro** [comment]
@nournia you can use mpeg-2 layer 3, but you'll need to use a lower sample rate (`24000` is the max for mpeg-2 layer 3 according to that wikipedia link above)

**Comment by nournia** [comment]
Thanks.

**Comment by PasinduAnthony** [comment]
Thanks

**Comment by jasonzhang761213** [comment]
> @nournia you can use mpeg-2 layer 3, but you'll need to use a lower sample rate (`24000` is the max for mpeg-2 layer 3 according to that wikipedia link above)
> 
> specifically, this should work:
> 
> ```python
> from pydub import AudioSegment
> s = AudioSegment.from_file("./Canon.mp3")
> 
> low_sample_rate = s.set_frame_rate(24000)
> low_sample_rate.export("Canon2.mp3", bitrate="16k", format="mp3")
> ```

I did the same ，but got 18k。
