### ISSUE TITLE
Feed raw audio data to AudioSegment

### ISSUE THREAD

**Issue by lgmcode** [jiaaro/pydub#145]
Hello, can you expose an interface to feed raw audio data to AudioSegment like AudioSegment.from_raw(mp3_data, format='mp3')
in addition to just a file name.
Thanks.

**Comment by jiaaro** [comment]
`AudioSegment.from_file()` can load file-like objects, so you can use StringIO for this…

```python
from pydub import AudioSegment
from StringIO import StringIO

sound = AudioSegment.from_mp3(StringIO(mp3_data))
```

**Comment by lgmcode** [comment]
Cool, I tried and it works. Thanks!

**Comment by olix20** [comment]
I'm trying to do a similar thing but with wav data. 


```python

from io import BytesIO

#get and test 'w' as a working AS object

#teseting constructor with raw data, using BytesIO since it says it needs bytes and not str

#in:
AudioSegment.from_wav(BytesIO(w.raw_data))

#out:
CouldntDecodeError: Decoding failed. ffmpeg returned error code: 1 .... Invalid data found when processing input\r\n'

```
What should i do differently?

**Comment by kylepxiao** [comment]
Having a similar issue with wav data. Has there been a solution?

**Comment by jiaaro** [comment]
`AudioSegment` objects are immutable so you don't need to copy them. If you're just giving an example, and the raw data comes from elsewhere, this is an option:

```python
from io import BytesIO

AudioSegment.from_raw(
    BytesIO(w.raw_data), 
    sample_width=w.sample_width, 
    channels=w.channels,
    frame_rate=w.frame_rate
)
```

Alternatively, since you have the raw data you can also instantiate the `AudioSegment` directly:

```python
AudioSegment(
    w.raw_data,
    sample_width=w.sample_width,
    frame_rate=w.frame_rate,
    channels=w.channels
)
```

**Comment by bobyang9** [comment]
Hello, I would like to feed mp3 data in the form of a BytesIO object to AudioSegment.from_file(), but there is an error when from_file() calls mediainfo_json in utils.py:

```
File ".../server.py", line 88, in analyze
    song = AudioSegment.from_mp3(BytesIO(audio_bytes))
  File ".../audio_segment.py", line 738, in from_mp3
    return cls.from_file(file, 'mp3', parameters=parameters)
  File ".../audio_segment.py", line 685, in from_file
    info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
  File ".../utils.py", line 291, in mediainfo_json
    info = json.loads(output)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

Just for reference, the code I am using to get the BytesIO object is as follows:
```
audio_data = await request.form()
audio_bytes = await (audio_data['file'].read())
song = AudioSegment.from_mp3(BytesIO(audio_bytes))
```
(this is for use in a web app)

It seems like the variable "output" in mediainfo_json is an empty string, causing the problem. Is there a workaround around this?

**Comment by darshanvjani** [comment]
@bobyang9 i am experiencing a similar problem , when i deply the code on heroku container.

**Comment by khalilchatoo** [comment]
@darshanvjani @bobyang9 did you ever solve this? I'm compiling FFmpeg from source in a docker container but am probably missing some flags

**Comment by bobyang9** [comment]
Nope, still buggy. This also happens both on heroku and local. Might just use .wav instead :( I would like to accept many different types of audio files though.

**Comment by asmwarrior** [comment]
> @darshanvjani @bobyang9 did you ever solve this? I'm compiling FFmpeg from source in a docker container but am probably missing some flags

I have the same error. It looks like I have no way to open an in-memory `mp3` file, such as a `io.BytesIO` object I received from other sources. Any ideas?

There are several functions: such as `from_raw`, `from_file` and `from_mp3`, I'm not sure which one could be used, I have tried those, and none could work.

**Comment by asmwarrior** [comment]
Another question is that I see under Windows, the pydub library need to call "ffmpeg.exe" to open the audio file. My guess is that the "ffmpeg.exe" can't open the in-memory file from `io.BytesIO`, instead, it only accepts a file path, such as ”D:/abc.mp3".

**Comment by khalilchatoo** [comment]
@asmwarrior How I ended up solving it IIRC was providing it an absolute path rather than a relative path
