### ISSUE TITLE
detect_silence function seems like have some duplicated chunks

### ISSUE THREAD

**Issue by zmskei** [jiaaro/pydub#146]
The following list was generated by detect_silence function. The result seems like containing  many duplicated frames among these chunks?
[[0, 11873], [10875, 11876], [23093, 24973], [26429, 27767], [26875, 29356], [28635, 30050], [29995, 31393], [30802, 39338], [39524, 41181], [40184, 41235], [40267, 41271], [40274, 41471], [40606, 45852], [45865, 46956], [46365, 47623], [46950, 49842], [48882, 50341], [49373, 50569], [49648, 52040], [51647, 55608], [55309, 57245], [57444, 61666], [60899, 62094], [61150, 62333], [61688, 62778], [62089, 64556], [63962, 65177], [65223, 68727], [69579, 70673], [70184, 71779], [71415, 75260], [77052, 78453], [77627, 78632], [77634, 80082], [79857, 81017], [80128, 81156], [80245, 90494], [90530, 95407], [96416, 99700], [100044, 103553], [103563, 104690], [103965, 105101], [104142, 105204], [104217, 105218], [105376, 106581], [105585, 106588], [105593, 106668], [106656, 110747], [110743, 118845], [117900, 118925], [117931, 118934], [118086, 119443], [119443, 124484], [124317, 125418], [124493, 125956], [125401, 126474], [128511, 130951], [131017, 132341], [133167, 135057], [134550, 135574], [134893, 135927], [134988, 137664], [136750, 137903], [137068, 139829], [140347, 142442], [141767, 147028], [147351, 149566], [150188, 153397], [153355, 156289], [156803, 167318], [166343, 167832], [166895, 167896], [166915, 167990], [167127, 168178]

It is a possible problem?

**Comment by jiaaro** [comment]
weird, yes

**Comment by zmskei** [comment]
Hi, jiaaro. Sorry for no reply such a long time. I have uploaded a slice of the test audio in this reply. The parameter that I used to do the calculation is (min_silence_len=1000, silence_thresh=audio.dBFS). Hope I did not set the wrong parameters. Thanks for your effort providing such a great audio lib!
[slice.zip](https://github.com/jiaaro/pydub/files/400968/slice.zip)

**Comment by jiaaro** [comment]
some updates on this:

I've written this code to test the issue, it does in fact fail

```python
from pydub import AudioSegment
from pydub.silence import detect_silence

# see attachment in zmskei's GitHub issue: 
# https://github.com/jiaaro/pydub/issues/146#issuecomment-237465992
sound = AudioSegment.from_wav("/Users/jiaaro/Downloads/slice.wav")

silences = detect_silence(sound, min_silence_len=1000, silence_thresh=sound.dBFS)

prev_end = -1
for start, end in silences:
    assert start > prev_end
    prev_end = end
```
