### ISSUE TITLE
split_on_silence chunks all have length of 0

### ISSUE THREAD

**Issue by krisfields** [jiaaro/pydub#147]
I attempted to use the code in this issue (https://github.com/jiaaro/pydub/issues/143#issuecomment-225512045) but each chunk always has a length of 0 and thus when it combines them it always combines them into one chunk of total length 0.  Exporting that chunk or any of the "smaller" chunks always results in a file with size of 44 bytes.

```
 sound = AudioSegment.from_file("/path/to/file.wav", format="wav")
 len(sound)
 3953006
 chunks = split_on_silence(sound, min_silence_len=1000, silence_thresh=-16, keep_silence=200)
 len(chunks)
 364
 len(chunks[0])
 0
```

It works fine if I split and export by time instead:

```
song[:60000].export("/path/to/file.wav", format="wav")
```

But then, of course, I'm cutting in the middle of words which I'm trying to avoid.

**Comment by jiaaro** [comment]
may be related to #146
