### ISSUE TITLE
Can you help with this error?

### ISSUE THREAD

**Issue by miletskiy** [jiaaro/pydub#148]
The file exists, ffmpeg in the PATH, but something went wrong (

`pat = "c:\sample\audio.mp3"`
`song = pydub.AudioSegment.from_mp3(pat)`

![win_err](https://cloud.githubusercontent.com/assets/11210381/17078270/efcf2334-50f6-11e6-9d89-1d86b3dbc966.jpg)

Thanks in advance for your answer.

**Comment by jiaaro** [comment]
According to google Windows error 2 is "File not found" usually that means ffmpeg wasn't found, but can also mean the audio file couldn't be found. Did you get a warning that ffmpeg wasn't found?

**Comment by miletskiy** [comment]
Thank you for your answer. 
I implemented my script on the OS X. 
Everything works excellent. Your library is very useful.
