### ISSUE TITLE
Support for amr

### ISSUE THREAD

**Issue by lgmcode** [jiaaro/pydub#151]
Hi,
We need to manipulate some amr audio files recently, but we don't know how to do that with pydub, the method `from_file` with parameter `format='amr'` seems not work. Could you please add support for the amr audio format?

**Comment by lgmcode** [comment]
Sorry, it was my operational error, `from_file` with a second parameter `'amr'` works fine now. Thanks a lot!

**Comment by jiaaro** [comment]
No problem, glad it's working for you :)
