### ISSUE TITLE
Playing external mp3 with pydub?

### ISSUE THREAD

**Issue by lithiumlab** [jiaaro/pydub#152]
Is it possible to read from a external mp3 with pydub like this?
`https://website.com/file.mp3`

**Comment by lithiumlab** [comment]
I just asked myself:
`					external_audio = requests.get('https://palomaimages.washingtonpost.com/audio/alexa-politicsbrief_echosponsor715.mp3')
					au = io.BytesIO()
					au.write(external_audio.content)
					au.seek(0)					
					audio_segment = AudioSegment.from_file(au, format='mp3')
`

**Comment by lithiumlab** [comment]
Great Jiaaro;
I'm now experimenting on reading from a m3u file.
Do you have prior experience with those or integrating with ffmpeg?

I can read and parse m3u files of course but i wonder if there's some tool to recognize and process them in a loop.

**Comment by jiaaro** [comment]
@lithiumlab I'm not sure, I haven't worked with them. Wikipedia says they are text files so probably the easiest thing to do is find a lib or parse the text yourself (with a regex?)

**Comment by jiaaro** [comment]
@lithiumlab did you manage to get something working? Maybe you could share a snippet here or in a gist for people who find this thread by google search?
