### ISSUE TITLE
Lowpass filter

### ISSUE THREAD

**Issue by quoccuongbka** [jiaaro/pydub#153]
Please check lowpass filter implementation, it seems work incorrectly

**Comment by jiaaro** [comment]
@quoccuongbka what were you expecting, what happened instead?

note: the lowpass filter is very simple, it's a first order low pass (so it should attenuate 6dB per octave over the frequency you specify)

**Comment by quoccuongbka** [comment]
@jiaaro: see, I did not say it's incorrect. I just compare result from pydub and audacity, pydub introduce more noise than audacity

Steps: I put a song in sample rate 44100Hz to 2kHz lowpass filter and check result

**Comment by jiaaro** [comment]
For those interested, there is a scipy powered set of filters in [`pydub.scipy_effects`](https://github.com/jiaaro/pydub/blob/master/pydub/scipy_effects.py)

It's not loaded by default since it has a dependency on scipy (pydub aims to work without dependencies for simple cases)

```python
from pydub import AudioSegment
import pydub.scipy_effects

# Filter out frequencies above 500 Hz, with a 3rd order filter
AudioSegment.high_pass_filter(500, order=3)
```

In this code snippet, 500Hz will be attenuated by 3dB. Frequencies above 500 Hz will be attenuated by 18 dB / octave. For example 1000 Hz (one octave higher) will be attenuated by ~21 dB (we started at -3 dB, and reduced by 18dB further since it was an octave higher).

**Comment by quoccuongbka** [comment]
Let me try, thank you so much! :)

**Comment by matttraynar** [comment]
Was wondering if I could get some clarification on the low pass filter? It doesn't seem to actually have any effect on the audio clip I'm using, I assume I'm doing something wrong. I've tried both:

`song.low_pass_filter(300)` 
and
`effects.low_pass_filter(song, 300)`

and then calling export directly after and I can't hear any difference with the audio clip. 
`song.export("my/file/path/song.wav", format="wav")`

300Hz is a arbitrary value but I am trying to create an effect similar to hearing audio through a wall (which I understand is best done using a low pass filter at 300Hz-ish). Am I doing something wrong? Or maybe I am exporting the audio in the wrong way? Thanks in advance for any help you may be able to provide.

**Comment by jiaaro** [comment]
All pudín effects return a new audio segment (the original is not changed) are you doing this?

```python
muffled_song = sound.low_pass_filter(300)
muffled_song.export(…)
```

**Comment by matttraynar** [comment]
Ahaa knew I must've been doing something wrong! I'm used to C++ and assumed I was passing by reference. Thanks a lot!

**Comment by BassThatHertz** [comment]
> ```python
> from pydub import AudioSegment
> import pydub.scipy_effects
> 
> # Filter out frequencies above 500 Hz, with a 3rd order filter
> AudioSegment.high_pass_filter(500, order=3)
> ```
Just so people who stumble across this webpage don't potentially get confused, you meant `low_pass_filter` not `high_pass_filter` as you're filtering **above** a certain frequency. Also, your example doesn't show how to add the filter to an imported audio file so here's an example for those who may be unsure how to do this:

```
from pydub import AudioSegment
import pydub.scipy_effects

# Importing a WAV file named "1.wav". You can import other formats too, as documented in the "Quickstart" section of README.markdown
audio_file = AudioSegment.from_file("1.wav", "wav")

# Put a 4th-order low pass filter at 80Hz.  
filtered_version = song.low_pass_filter(80, order=4)
# (The cutoff frequency, in this case 80Hz, is attenuated by 3dB. Frequencies above the specified frequency are attenuated according to the order of the filter. In this example, a 4th order filter is specified. This means an attenuation of 24dB per octave, i.e. 160Hz is attenuated by 12dB, 240Hz (an octave above) is attenuated by 24dB, 480Hz is attenuated by 48dB, etc.)

# Save the filtered audio file. The first argument is your desired filename with the file extension.
filtered_version.export("2.wav", format='wav')
```

**Comment by palmajoao** [comment]
need to reopen this one as my low_pass filter exports exactly the same file (need to filter frequencies above 10KHz just to filter bat frequencies)
`from pydub import AudioSegment`
`song = AudioSegment.from_wav("F:/20220824_050000T.wav")`
`new = song.low_pass_filter(10000)`
`out_file = "F:/20220824_050000T_filt10000.wav"`
`new.export(out_file, format="wav")`

**Comment by makiv2** [comment]
Agree with @palmajoao, low_pass_filter does not filter out any frequencies.
