### ISSUE TITLE
Can split_on_silence track the chunks' original audio positions?

### ISSUE THREAD

**Issue by xinofekuator** [jiaaro/pydub#154]
I am running this code and I would like to keep track of the init and end seconds for each of the chunks:

sound = AudioSegment.from_mp3(MY_AUDIO)
chunks = split_on_silence(sound,min_silence_len=500,silence_thresh=-50)

Is it possible to obtain them somehow?

**Comment by jiaaro** [comment]
What do you mean by "init" and "end" seconds?

**Comment by xinofekuator** [comment]
I mean the inicial and ending position in seconds of the chunk in the original audio file.

**Comment by jiaaro** [comment]
the easiest way is to use `detect_nonsilent()` directly (probably by copying the [implementation of `split_on_silence()`](https://github.com/jiaaro/pydub/blob/master/pydub/silence.py#L78) and retrieve the chunks manually:

```python
def split_on_silence(audio_segment, min_silence_len=1000, silence_thresh=-16, keep_silence=100):
    """
    audio_segment - original pydub.AudioSegment() object
    min_silence_len - (in ms) minimum length of a silence to be used for
        a split. default: 1000ms
    silence_thresh - (in dBFS) anything quieter than this will be
        considered silence. default: -16dBFS
    keep_silence - (in ms) amount of silence to leave at the beginning
        and end of the chunks. Keeps the sound from sounding like it is
        abruptly cut off. (default: 100ms)
    """

    not_silence_ranges = detect_nonsilent(audio_segment, min_silence_len, silence_thresh)

    chunks = []
    for start_i, end_i in not_silence_ranges:
        start_i = max(0, start_i - keep_silence)
        end_i += keep_silence

        chunks.append(audio_segment[start_i:end_i])

    return chunks
```

**Comment by piercashuang** [comment]
I also want to ask this question.
