### ISSUE TITLE
Add pydub to conda-forge?

### ISSUE THREAD

**Issue by carlthome** [jiaaro/pydub#155]
For CI and general convenience it would be awesome if pydub was available on [conda-forge](https://conda-forge.github.io), thoughts?

**Comment by jiaaro** [comment]
I'm not very familiar with conda, but pydub is available via pypi (and so, pip), which itself is available through conda.

There is more conversation in a conda forge thread here https://github.com/conda-forge/conda-forge.github.io/issues/28

**Comment by jiaaro** [comment]
Closing this for now, if someone is interested in automating the creation of condo-forge projects somehow I'd be happy to discuss further
