### ISSUE TITLE
Issue with exporting mp3 files 

### ISSUE THREAD

**Issue by thisiskylierose** [jiaaro/pydub#16]
pydub is an excellent sound manipulation tool. It makes sense and seem quite easy to use. I will certainly be making use of it, together with PHP and a Flash interface. However, I am stuck on finding a solution to what seems to be a simple problem. 

I can save a wav file using the code example below: 

sound1 = AudioSegment.from_wav("./sounds/1.wav")
sound1 = sound1.reverse()
sound1.export("./sounds/out.wav", format="wav")

But, saving an mp3 file is produces errors with the code below:

sound1 = AudioSegment.from_wav("./sounds/1.wav")
sound1 = sound1.reverse()
sound1.export("./sounds/out.mp3", format="mp3")

The error is: 

Traceback (most recent call last):
  File "/_test/python/test.py", line 15, in 
    sound1.export("./sounds/out.mp3", format="mp3")
  File "/Library/Python/2.7/site-packages/pydub/audio_segment.py", line 289, in export
    stderr=open(os.devnull)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 493, in call
    return Popen(_popenargs, *_kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1228, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

What seems to occur is an mp3 file is created, but results in a 0Kb file. Additionally, I can run ffmpeg through the CLI and the correct file size for the mp3 conversion from wav is created. 

Hoping all of this makes sense and there is a simple answer. Thanks for your time reading this. If there is a solution, please let me know!

**Comment by daxaxelrod** [comment]
I'm getting the same error.

File is in same dir as the project

at top of the file
AudioSegment.converter = "/Users/davidaxelrod/ffmpeg/"
AudioSegment.ffmpeg = "/Users/davidaxelrod/ffmpeg/"

in view
                speech_file = AudioSegment.from_wav(sound_path + ".mp3")
                speech_file.export(sound_path + ".flac", format="flac")
                print("mp3 file")
                speech_content = base64.b64encode(open(sound_path + ".flac", "rb").read())

**Comment by jiaaro** [comment]
@daxaxelrod I'm not sure if this will solve your issue but you have a couple bugs in your code. It should read:

at top of the file

```python
from pydub import AudioSegment

# 1. Only one assignment is necessary, AudioSegment.converter is correct
# 2. this is the path to the ffmpeg executable, I'm guessing here, but make sure 
#      the path is correct. It shouldn't be a directory/have a slash at the end.
AudioSegment.converter = "/Users/davidaxelrod/ffmpeg/bin/ffmpeg"

### And In the view… ###
# If you're reading in an mp3 file it should be "from_mp3"
speech_file = AudioSegment.from_mp3(sound_path + ".mp3")

speech_file.export(sound_path + ".flac", format="flac")
print("mp3 file")
speech_content = base64.b64encode(open(sound_path + ".flac", "rb").read())
```

**Comment by aioannou96** [comment]
I have followed exactly the steps but I am still getting the same error.

1st step: Download and ffmpeg, rename folder in FFmpeg and put it in C:
![image](https://user-images.githubusercontent.com/56006634/79741613-7800b000-82f9-11ea-9945-4d785849b54c.png)

2nd step: 
![image](https://user-images.githubusercontent.com/56006634/79741439-2bb57000-82f9-11ea-910d-e78a2c92d653.png)

3rd step
![image](https://user-images.githubusercontent.com/56006634/79741697-99fa3280-82f9-11ea-89e4-6c5f31aae1d2.png)

Please help

**Comment by aioannou96** [comment]
![image](https://user-images.githubusercontent.com/56006634/79741885-eb0a2680-82f9-11ea-85d2-07b1075314b1.png)
