### ISSUE TITLE
Playing audio in the background

### ISSUE THREAD

**Issue by Noammac** [jiaaro/pydub#160]
I searched the internet and looked into the code and it seems currently there's no way to play sounds in the background of the script. So things like:
```python
import pydub
from pydub.playback import play
import os

pydub.AudioSegment.converter = os.path.dirname(os.path.abspath(__file__)) + r"\ffmpeg.exe"
file = pydub.AudioSegment.from_mp3(r"file.mp3")
print("This should be playing music.")
play(file)
print("It has now played music")
```
Will print `This should be playing music`, wait until it ends and then print `It has now played music`!

A workaround for this would be to export the `mp3` file into `wav`, use `winsound` to play the file (with the `SND_ASYNC` flag) then delete it at the end of the script.

**Comment by steveway** [comment]
Hi, the play function is pretty simple. You can implement this yourself and you can use threads to let it run in the background.
Take a look for example in this file:
https://github.com/steveway/papagayo-ng/blob/working_vol/SoundPlayer.py
The interesting parts for you should be the "_play" and the "Play" functions.
Simply wrapping your play(file) in a thread might already work for you.

**Comment by Noammac** [comment]
Sorry for the extremely long delay. I didn't see your message for some reason, I understand what's going on in the `play` function and in some of the `_play` function but at some point, I just don't understand it anymore. Do you mind adding documentation or explaining it here?

**Comment by steveway** [comment]
Well, I'm not exactly sure what part is the difficult one. Can you tell which lines are confusing?
Essentially the Play function starts the _play function in a thread so it can run in the background.
In the _play function you need to mostly only watch the part in the "if AudioSegment:" block.
We open an audio output, chop the audio into chunks and start playing these with the small for loop.
I haven't really looked at that part since my last message, but you might not need to chop it into chunks, we do this so we can easily stop the playback anytime.

**Comment by Noammac** [comment]
That's what I was confused about. I'll try your way and report back whether
it succeeds or fails.

**Comment by guysoft** [comment]
Hey guys,
I also needed to write this, since I couldn't find a full solution here is mine:
https://gist.github.com/guysoft/bda8ff5be7eb708fd7057850d788dbdf

You can ``-h`` the file and see how to run it. 
If you want this as a PR please tell me what needs to be done.

**Comment by jiaaro** [comment]
`pydub.playback.play` will do it's best to find a player and use it. The pydub project [recommends](https://github.com/jiaaro/pydub#playback) that you use simpleaudio.

```python
from pydub import generators
from pydub.playback import play

# 5 seconds of A 440
sound = generators.Sine(440).to_audio_segment(duration=5000)
play(sound)
```

**Comment by guysoft** [comment]
There is a limitation though in using threads, it means you can't stop the audio from playing in the middle. Unless I am missing from reading the code a way to signal the thread from stopping thr audio. My implementation above does have thay feature.

**Comment by jiaaro** [comment]
@guysoft If you use `simpleaudio` playback is done in a thread and it responds to keyboard interrupt properly. If you use pydub's internal helper function (or just use simpleaudio directly) you can call a function at any time to stop playback:

```python
import time

from pydub import generators
from pydub.playback import _play_with_simpleaudio

# 5 seconds of A 440
sound = generators.Sine(440).to_audio_segment(duration=5000)
playback = _play_with_simpleaudio(audio_segment)

# end playback after 3 seconds
time.sleep(3)
playback.stop()

# OR you can use simple audio directly:
import simpleaudio
playback = simpleaudio.play_buffer(
    sound.raw_data, 
    num_channels=sound.channels, 
    bytes_per_sample=sound.sample_width, 
    sample_rate=sound.frame_rate
)
# end playback after 3 seconds
time.sleep(3)
playback.stop()
```
