### ISSUE TITLE
ffmpeg conflicting parameters

### ISSUE THREAD

**Issue by Tamriel** [jiaaro/pydub#163]
When I use `AudioSegment.from_file(song_path).export(destination_path, format="mp3",                          parameters=['-n'])` I get `Error, both -y and -n supplied. Exiting.` From the ffmpeg doc:
-y (global) Overwrite output files without asking.
-n (global) Do not overwrite output files, and exit immediately if a specified output file already exists.

Can you remove -y internally when one supplies -n?

**Comment by jiaaro** [comment]
If we did that pydub would have to check to see if it failed and raise some kind of exception for users to catch.

I think it's probably clearer to write something like:

```python
import os.path
import pydub

if os.path.exists(destination_path):
    print "can't write, audio exists at that path"
else:
    AudioSegment.from_file(song_path).export(destination_path, format="mp3")
```

What do you think?

**Comment by Tamriel** [comment]
Yes, you are right. Thanks!
