### ISSUE TITLE
Audio slicing/splitting and export does not work as expected

### ISSUE THREAD

**Issue by mpaolino** [jiaaro/pydub#164]
### Steps to reproduce

Take the provided mp3 file (11025 / 16bit / 1 channel) of 120.111 seconds of duration. Slice out the first 0.111 ms and export it to a new file.

```python
segment = AudioSegment.from_file(filename, format="mp3")
new_segment = segment[111:]
new_segment.export("chopped-%s" % filename, format="mp3")
```

### Expected behavior
The exported file should be ~120.0 seconds long.

### Actual behavior
If you load the chopped file in an AudioSegment it shows the duration_seconds to be ~120.0, but if you open the chopped file in audacity or almost anything else out there, it shows the file to still be ~120.111 seconds long, and actually the generated file is even larger than the original one (240475 bytes vs 240222 bytes).

### Your System configuration
- Python version: 2.7.12
- Pydub version:  0.16.6
- ffmpeg or avlib?: ffmpeg
- ffmpeg version: 2.8.8 (latest official packages in Ubuntu Xenial 16.04.1)

### Is there an audio file you can include to help us reproduce?
[120.111.zip](https://github.com/jiaaro/pydub/files/646117/120.111.zip)

**Comment by mpaolino** [comment]
BTW, I've just tried exporting the trimmed audio to WAV and it does generate a ~120.0 second audio. At first glance it seems the mp3 conversion on export is the cause of the problem.

**Comment by mpaolino** [comment]
I see that all mp3 encoders add junk at the begining of the files, so I guess there is nothing you guys can do here.

**Comment by jiaaro** [comment]
@mpaolino Yeah it's a result of how the mp3 encoders work. The best solution is to use a format that doesn't have that issue. WAV is one, but I think FLAC may also work as you'd expect, but with smaller files. Alternatively, you can gzip the wav files to make them significantly smaller. (works on wav because they're uncompressed, doesn't work on compressed formats like mp3)
