### ISSUE TITLE
AudioSegment.split_to_mono should support arbitrary number of channels

### ISSUE THREAD

**Issue by thechriskelley** [jiaaro/pydub#165]
I have a setup that generates a 4-channel wav file. I would like to split this wav file into 4 separate mono tracks. The following will only generate two mono tracks:

```
myWav = AudioSegment.from_file('test.wav', format='wav')
print myWav.channels // 4
print len(myWav.split_to_mono()) // 2
```

It appears that this is due to left/right being hard-coded into `split_to_mono` and `audioop.tomono`. I took a look at adding the capability myself, but the values for `fac1`, `fac2` passed to `audioop.tomono`  are a bit cryptic and I'm not quite sure what needs to happen to iterate over each channel and return a variable length list of `AudioSegment` objects.

**Comment by jiaaro** [comment]
pydub uses `audioop.tomono()` because it's implemented in C and assumed to be faster. As far as I know nobody has actually tested it, but it's roughly equivalent to doing the following:

```python
from pydub import AudioSegment
sound = AudioSegment.from_file("/path/to/file.mp3", format="mp3")

samples = sound.get_array_of_samples()
mono_channels = []

for i in range(sound.channels):
  samples_for_current_channel = samples[i::sound.channels]

  try:
    mono_data = samples_for_current_channel.tobytes()
  except AttributeError:
    mono_data = samples_for_current_channel.tostring()

  mono_channels.append(
    sound._spawn(mono_data, overrides={"channels": 1})
  )
```

**Comment by jiaaro** [comment]
would you mind sending a sample of a 4 channel audio file (even just a few seconds long would be plenty)? I'd like to add some tests with realistic data :)

**Comment by thechriskelley** [comment]
The example you posted actually seems to work just fine! Thank you for that. I've attached a 4 channel audio file.
[4-channel-recording-test.wav.zip](https://github.com/jiaaro/pydub/files/671634/4-channel-recording-test.wav.zip)

**Comment by Qdrew** [comment]
I am very pleased to find this example as I had thought I was doing something wrong with split_to_mono() using 4 channel files.

However I find that although I can split and successfully export the individual channels using the code above, I'm getting incorrect values for timings - eg. anything where I am splitting arrays is in the wrong place and 'duration_seconds' shows half the correct value.

Checking the raw_data, it seems 'tobytes' in the routine above is loading each AudioSegment with double the bytes of the split_to_mono function, even with regular stereo files.

For example 176 bytes instead of the normal 88 for 44.1KHz 16 bit mono.

NB: I'm using a 64 bit Python install, could that affect it? Or is this the same for all? Quickest test - check duration_seconds.

I thought I should flag it up - and I'm wondering if this is a bug in 'tobytes' which is worth knowing about in case it affects others.

Best Regards - and thanks so much for pydub! Drew

**Comment by thechriskelley** [comment]
I ran into this as well, and was able to work around by explicitly passing frame_width from the 4-channel wav to _spawn:

sound._spawn(mono_data, overrides={'channels': 1, 'frame_width': myWav.sample_width})

**Comment by Qdrew** [comment]
That's excellent - thank you so much, thechriskelley!

I had tried frame_width: myWav.frame_width but wasn't getting the right result. Not entirely sure why we use sample_width, but I'm new to all this. All working well with your suggestion anyway.

Hopefully jiaaro can update the split_to_mono routine to use this approach for >2 channel audio.

**Comment by jiaaro** [comment]
@Qdrew we use sample width because with a mono signal each frame contains one sample (since there is only one channel)

**Comment by sunlin15803469083** [comment]
forgive my unknow,now i have to split the two-channel stereo wav into one left-Mono wav and one right-Mono wav ,but i just kown the function of  split_to_mono()   and  can`t use it to export left and right mono wav ,could you give me an example for me ?

**Comment by sunlin15803469083** [comment]
when i deal with big file data ,it`s slowly,file size as 1G bigger

**Comment by jiaaro** [comment]
A fix has been merged to master. This will be in the next release of pydub

**Comment by monersss** [comment]
I have tried to use this code example to separate 19 channels in my audio aif file and save each to wav file. The code seems to work fine but I cannot save the output

`from pydub import AudioSegment
sound = AudioSegment.from_file("C:/Users/m/Desktop/1.aif", format = 'aiff')
print(sound.channels)

samples = sound.get_array_of_samples()
mono_channels = []


for i in range(sound.channels):
  samples_for_current_channel = samples[i::sound.channels]

  try:
    mono_data = samples_for_current_channel.tobytes()
  except AttributeError:
    mono_data = samples_for_current_channel.tostring()
 
  x = mono_channels.append(sound._spawn(mono_data, overrides={"channels": 1}))
  x.export('mono.wav', format = 'wav')`

as i am getting an error:
`AttributeError: 'NoneType' object has no attribute 'export'`

Could someone help me please?
