### ISSUE TITLE
pydub.silence.split_on_silence always returns empty audio chunks

### ISSUE THREAD

**Issue by ag3859** [jiaaro/pydub#169]
### Steps to reproduce
Trying a simply enough code using Python 3.5.2, not sure where missing it.
I have a .wav file at 'path'
sound_file = AudioSegment.from_wav(path)
audio_chunks = pydub.silence.split_on_silence(sound_file)
print("Audio chunks generated ", audio_chunks)

### Expected behavior
I expect the see an array of objects. But I see nothing, including no errors

### Actual behavior
All I see is an empty array []. Needless to say, chunk.export('output', format="wav") has no consequence.

### Your System configuration
- Python version: 3.5.2
- Pydub version: 0.16.7
- ffmpeg or avlib?: ffmpeg
- ffmpeg/avlib version: 3.1.3
[inputfile.wav.zip](https://github.com/jiaaro/pydub/files/721739/inputfile.wav.zip)

### Is there an audio file you can include to help us reproduce?
You can include the audio file in this issue - just put it in a zip file and drag/drop the zip file into the github issue.

**Comment by jiaaro** [comment]
The sample input file is quieter than the silence threshold, so the whole thing is being considered silent. Here's my test session (in ipython)

```python
In [1]: from pydub import AudioSegment

In [2]: sound = AudioSegment.from_wav("/Users/jiaaro/Downloads/inputfile.wav")

In [3]: from pydub.playback import play

In [4]: play(sound)

In [5]: from pydub.silence import split_on_silence

In [6]: split_on_silence(sound)
Out[6]: []

In [7]: split_on_silence?
Signature: split_on_silence(audio_segment, min_silence_len=1000, silence_thresh=-16, keep_silence=100)
Docstring:
audio_segment - original pydub.AudioSegment() object

min_silence_len - (in ms) minimum length of a silence to be used for
    a split. default: 1000ms

silence_thresh - (in dBFS) anything quieter than this will be
    considered silence. default: -16dBFS

keep_silence - (in ms) amount of silence to leave at the beginning
    and end of the chunks. Keeps the sound from sounding like it is
    abruptly cut off. (default: 100ms)
File:      ~/code/pydub/pydub/silence.py
Type:      function

# Here I notice that the sound is longer than min_silence_len so it should be ok
In [8]: len(sound)
Out[8]: 2047

# Here I notice the average loudness of the sound is -19 dBFS (quieter than 
# the default silence_thresh of -16dBFS)
In [9]: sound.dBFS
Out[9]: -19.613251526604525

In [10]: split_on_silence(sound, silence_thresh=-22)
Out[10]:
[<pydub.audio_segment.AudioSegment at 0x10ce438d0>,
 <pydub.audio_segment.AudioSegment at 0x10ce437d0>]
```

**Comment by datascience-prog** [comment]
Thank you, it worked for me! :-)
