### ISSUE TITLE
Quality of mp3 when dB increase

### ISSUE THREAD

**Issue by MagTun** [jiaaro/pydub#170]
### Steps to reproduce
increase dB by 10 ,15 and 20
export with and without bitrate="192k"

When I increase the dB, the quality of the audio decreases way more than if I use [MP3Gain](http://mp3gain.sourceforge.net/). with the same dB gain. With pydub,  I get a lot of "frying". 

### Your System configuration
- Python version: 3.5
- Pydub version: 0.16.7
- ffmpeg or avlib?:  ffmpeg
- ffmpeg/avlib version:  not known

###
This is the media-info before dB increase 
all infor 0 {'encoder': 'LAME3.97b\r', 'genre': 'Speech\r', 'comment': 'Composer\r', 'has_b_frames': '0\r', 'format_name': 'mp3\r', , 'track': '1\r', 'codec_tag_string': '[0][0][0][0]\r', 'start_time':	0.000000\r', 'album': 'test\r', 'size': '1356078.000000\r', 'avg_frame_rate': '0/0\r', 'title': 'IVONA Reader\r', 'codec_time_base': '0/1\r', 'width': '100\r', 'pix_fmt': 'bgra\r', 'level': '-99\r', 'time_base': '1/90000\r', 'channels': '1\r', 'nb_streams': '2\r', 'index': '1\r', 'height': '100\r',	codec_long_name': 'PNG (Portable Network Graphics) image\r', 'duration': '179.644078\r', , 'codec_name': 'png\r', 'sample_rate': '22050.000000\r', 'codec_tag': '0x0000\r', 'bit_rate': '59551.000000\r', 'format_long_name': 'MP2/3 (MPEG audio layer 2/3)\r', 'codec_type': 'video\r', 'bits_per_sample': '0\r'}

This is the media-info after an increase of 20 dB  and bitrate="192k"
all infor 1 {'sample_rate': '22050.000000\r', 'encoder': 'Lavf55.33.100\r', 'nb_streams': '1\r', 'codec_time_base': '1/22050\r', 'index': '0\r', 'format_name': 'mp3\r', 'size': '3593814.000000\r', 'time_base': '1/14112000\r', 'codec_name': 'mp3\r', 'codec_long_name': 'MP3 (MPEG audio layer 3)\r', 'codec_tag_string': '[0][0][0][0]\r', 'start_time': '0.000000\r', 'codec_tag': '0x0000\r', 'bits_per_sample': '0\r', 'channels': '1\r', 'duration': '179.670204\r', 'avg_frame_rate': '0/0\r', 'bit_rate':	160000.000000\r', 'format_long_name': 'MP2/3 (MPEG audio layer 2/3)\r', 'codec_type': 'audio\r'}		

Any idea how to solve that?

Thanks for your help!

**Comment by jiaaro** [comment]
a simple test you can do:

```python
from pydub import AudioSegment
sound = AudioSegment.from_file("/path/to/file.mp3", format="mp3")

# sound.max_dBFS shows how far below the limit the highest sample is (in dB)
max_gain_without_distortion = -1 * sound.max_dBFS
```

**Comment by EnoraNedelec** [comment]
Thanks for your quick reply. max_gain_without_distortion = -1 * sound.max_dBFS gives me -0.0 so I guess this means that I need a dynamic range compression. Too bad, pydub was a really great tool! Hopefully you will implement such type of compression in the future. Anyway, thanks for your help!

**Comment by jiaaro** [comment]
@EnoraNedelec You can try the experimental compression in the [effects module](https://github.com/jiaaro/pydub/blob/master/pydub/effects.py#L116)

```python
from pydub import AudioSegment
sound = AudioSegment.from_file("/path/to/file.mp3", format="mp3")

# Basically a hard-knee limiter at -12dB
compressed_sound = sound.compress_dynamic_range(threshold=-12.0, ratio=30.0, attack=10.0, release=200.0)

# Apply "make up gain" (raise the volume to the theoretical max)
loud_sound = compressed_sound.normalize()
```

**Comment by EnoraNedelec** [comment]
Thanks for this! Unfortunately, it doesn't increase the dB, at least I can't notice it and MP3Gain still show a dB at around 92dB like the original audio.

**Comment by jiaaro** [comment]
Wow, MP3gain is boosting the signal by 92 dB?

**Comment by EnoraNedelec** [comment]
No, no MP3Gain doesn't increase by 92dB. It boosts the audio from about 92-93dB to 105dB cf printscreen. 
![increasedb](https://cloud.githubusercontent.com/assets/15843700/22345516/a7938784-e400-11e6-9fd8-bd1e7665c624.png)

**Comment by jiaaro** [comment]
That's interesting. The MP3Gain UI says it's clipping though (pydub's normalize will not cause clipping). However, I'm not sure the difference between the two columns "clipping" and "clip(Track)"
