### ISSUE TITLE
AudioSegment.from_data() is not in the code

### ISSUE THREAD

**Issue by akuz** [jiaaro/pydub#177]
### Steps to reproduce

The changelog seems to indicate the addition of the AudioSegment.from_data() method -- however, on closer inspection, this method doesn't seem to be in the code.

**Comment by jiaaro** [comment]
Ah you're right, sorry about that.

When I retroactively added previous releases to the change log I misread one of the commits in the history (from_data was added in a PR but we agreed to make it part of the AudioSegment constructor before merging)

The API is this:

```python
from pydub import AudioSegment

sound = AudioSegment(
    # raw audio data (bytes)
    data=b'…',

    # 2 byte (16 bit) samples
    sample_width=2, 

    # 44.1 kHz frame rate
    frame_rate=44100, 

    # stereo
    channels=2
)
```

**Comment by akuz** [comment]
Ah ok, thank you!

**Comment by akuz** [comment]
Sorry, while we are here, is it possible to make two 1-channel AudioSegments from data (I guess yes), and then merge them into a stereo AudioSignal? It's just would be much easier to make mono segments first, then arrange bytes for the stereo segment properly.

**Comment by jiaaro** [comment]
yes, the easiest way (but not most performant) is to do something like:

```python
# both mono
sound1 = AudioSegment(…)
sound2 = AudioSegment(…)

sound1_left = sound1.set_channels(2).pan(-1)
sound2_right = sound2.set_channels(2).pan(+1)

stereo_sound = sound1_left.overlay(sound2_right)
```

**Comment by akuz** [comment]
Thanks a lot for the recipes. I wonder if the high-performance method would make a good candidate for a constructor method, something like make_stereo_segment_from_data(bytes1, bytes2, sample_width, frame_rate), which would do all the necessary checks (byte lengths matching and consistent with the sample width) and then make an AudioSegment with the specified frame rate.

**Comment by jiaaro** [comment]
yeah probably would be useful to have like `AudioSegment.from_mono(seg1, seg2, segn...
)`

**Comment by jiaaro** [comment]
pydub v0.18.0 includes this feature and is now available via PyPI

```python
from pydub import AudioSegment
from pydub.generators import Sine, Square

# make two mono sounds (300 Hz tones)
sound1 = Sine(300).to_audio_segment(duration=1000)
sound2 = Square(300).to_audio_segment(duration=1000)

stereo_sound = AudioSegment.from_mono_audiosegments(sound1, sound2)
```

**Comment by akuz** [comment]
Thanks James!
