### ISSUE TITLE
Incorrect duration after AudioSegment._spawn() with 16 bit samples.

### ISSUE THREAD

**Issue by alessiob** [jiaaro/pydub#179]
### Steps to reproduce

I'm using scipy to apply a convolution to a signal I load with pydub.
When the samples are represented with 16 bits and modified using AudioSegment._spawn(), the duration is not computed correctly.
However, if the AudioSegment instance returned by _spawn() is exported and played out, the duration is correct.

I included Python code with which the problem can be reproduced.
By looking at the pydub source code, I think that AudioSegment.\_\_len\_\_() is correct while the cause of the issue is in AudioSegment.frame_count().
Unfortunately, I couldn't investigate further and submit a pull request.

```
import numpy as np
from pydub.generators import WhiteNoise

# BIT_DEPTH = 8  # Fine.
BIT_DEPTH = 16  # Leading to bug.

def main():
  generator = WhiteNoise(
      sample_rate=48000,
      bit_depth=BIT_DEPTH)

  white_noise = generator.to_audio_segment(duration=1000, volume=0.0)
  print('duration (pre): {} ms'.format(len(white_noise)))

  # Get samples.
  white_noise_samples = white_noise.get_array_of_samples()
  print('num samples (pre): {}'.format(len(white_noise_samples)))

  # Modify samples.
  white_noise_samples = np.right_shift(white_noise_samples, 1)
  print('num samples (post): {}'.format(len(white_noise_samples)))

  # Create new AudioSegment.
  white_noise = white_noise._spawn(white_noise_samples)
  print('duration (post): {} ms'.format(len(white_noise)))


if __name__ == '__main__':
  main()
```

### Expected behavior
duration (pre): 1000 ms
num samples (pre): 48000
num samples (post): 48000
duration (post): 1000 ms

### Actual behavior
duration (pre): 1000 ms
num samples (pre): 48000
num samples (post): 48000
duration (post): 500 ms

### Your System configuration
- Python version: Python 3.4.3
- Pydub version: 0.17.0
- ffmpeg or avlib?: not relevant
- ffmpeg/avlib version: not relevant

### Is there an audio file you can include to help us reproduce?
Not needed.

**Comment by jiaaro** [comment]
I'm not 100% sure, but this may be helpful:

```python
import numpy as np
from pydub.generators import WhiteNoise

# BIT_DEPTH = 8  # Fine.
BIT_DEPTH = 16  # Leading to bug.

shifted_samples = np.right_shift(white_noise_samples, 1)

# gives us 500
len(white_noise._spawn(shifted_samples))

# these give us 4000
len(white_noise._spawn(shifted_samples.tobytes()))
len(white_noise._spawn(shifted_samples.tostring()))

# interestingly this is int64, so that actually makes some sense
shifted_samples.dtype

# and this works as expected, with the last bit giving us 1000
shifted_samples_array = array.array(white_noise.array_type, shifted_samples)
shifted_white_noise = white_noise._spawn(shifted_samples_array)
len(shifted_white_noise)
```

**Comment by alessiob** [comment]
Thanks for your comment @jiaaro!
Right, I forgot the casting part, which is up to the client code.

In my code, I took care of casting but in a different way, namely:
`shifted_samples_array = shifted_samples.astype(white_noise.array_type)`
instead of
`shifted_samples_array = array.array(white_noise.array_type, shifted_samples)`

Maybe when doable, the API doc (https://github.com/jiaaro/pydub/blob/master/API.markdown) could be updated. The example in AudioSegment.get_array_of_samples() could include a simple modification and the casting part.

Again, thanks for your time!

**Comment by jiaaro** [comment]
@alessiob note for any others who find this issue: `nparray.astype()` does not take the same "array type" values that `array.array` takes. pydub's `AudioSegment().array_type` is for `array.array` only.

I'll update API.markdown :)
