### ISSUE TITLE
File duration doesn't correspond to `len(AudioSegment)`

### ISSUE THREAD

**Issue by elricbk** [jiaaro/pydub#180]
### Expected behavior

`len(AudioSegment)` corresponds to file duration

### Actual behavior

Hello.

I'm using `pydub` to detect silence on file ends. Trying to ensure that there
is no more than 10ms of silence. And I have an issue with file duration. I'm
trying to determine duration as `len(AudioSegment)`:

    > fname = 'Error.ogg'
    > len(AudioSegment.from_file(fname)) 
    1076

But it differs both from `ffmpeg` duration:

    > int(float(mediainfo(fname)['duration'])*1000)
    1062

And `soxi` result:

    > soxi -D Error.ogg
    1.062521

And all past 1062ms is silence:

    > AudioSegment.from_file(fname)[1062:].rms
    0

So, the question – is it correct to use `len(AudioSegment)` as duration?

Detailed info from `ffprobe`:

    > ffprobe -v quiet -print_format json -show_format -show_streams Error.ogg
    {
        "streams": [
            {
                "index": 0,
                "codec_name": "vorbis",
                "codec_long_name": "Vorbis",
                "codec_type": "audio",
                "codec_time_base": "1/48000",
                "codec_tag_string": "[0][0][0][0]",
                "codec_tag": "0x0000",
                "sample_fmt": "fltp",
                "sample_rate": "48000",
                "channels": 1,
                "channel_layout": "mono",
                "bits_per_sample": 0,
                "r_frame_rate": "0/0",
                "avg_frame_rate": "0/0",
                "time_base": "1/48000",
                "start_pts": 0,
                "start_time": "0.000000",
                "duration_ts": 51001,
                "duration": "1.062521",
                "bit_rate": "80000",
                "disposition": {
                    "default": 0,
                    "dub": 0,
                    "original": 0,
                    "comment": 0,
                    "lyrics": 0,
                    "karaoke": 0,
                    "forced": 0,
                    "hearing_impaired": 0,
                    "visual_impaired": 0,
                    "clean_effects": 0,
                    "attached_pic": 0,
                    "timed_thumbnails": 0
                }
            }
        ],
        "format": {
            "filename": "Error.ogg",
            "nb_streams": 1,
            "nb_programs": 0,
            "format_name": "ogg",
            "format_long_name": "Ogg",
            "start_time": "0.000000",
            "duration": "1.062521",
            "size": "11592",
            "bit_rate": "87279",
            "probe_score": 100
        }
    }

### System configuration

- Python version: 2.7.10
- Pydub version: 0.18.0
- ffmpeg version: 3.2.4

**Comment by jiaaro** [comment]
`len()` is the correct way to check duration, however, pydub only works on raw audio data. So when you open compressed audio (like mp3), it is first converted to wave/raw samples. Mp3 codecs (and other formats) tend to produce some silence in the first and last chunk of data (15ms total is common)

Do you find that this still happens with a lossless format like wave?

**Comment by elricbk** [comment]
No, `.wav` file returns same duration via all three methods. Thanks for the explanation. I think I'll just use `mediainfo['duration']` to avoid false positives.
