### ISSUE TITLE
Support for ffmpeg/avconv input parameters

### ISSUE THREAD

**Issue by jgraniero** [jiaaro/pydub#184]
This is essentially a feature request for specifying an audio codec when importing a file.

When trying to open _some_ webm files and then export (to any format), there are segments of the audio which cannot be read.  [Here](http://askubuntu.com/questions/752107/how-to-convert-webm-video-to-mp4-when-encountering-errors-for-unsupported-lbrr-f) is a brief summary of the issue.

Running the conversion on command line with something like 

```
ffmpeg -i input.webm -vn -acodec mp3 output.mp3
```

throws the following errors for frames which cannot be read:

```
[opus @ 0x7fe481018a00] Error decoding a SILK frame.
[opus @ 0x7fe481018a00] Error decoding an Opus frame.
[opus @ 0x7fe481018a00] LBRR frames present; this is unsupported
```

After doing some research, it seems like this is an error with ffmpeg's default opus codec.  The following command solves the problem:

```
ffmpeg -acodec libopus -i input.webm -vn -acodec mp3 output.mp3
```

So basically I need a way of telling ffmpeg which audio codec to use for decoding the input file.  I think I can get around this by compiling ffmpeg from source and disabling the default `opus` decoder in favor of the `libopus` decoder (haven't tested) so that `AudioSegment.from_file` picks up `libopus` as the decoder.  I guess I could also open the input file with a different python library which allows me to specify the decoder and then feed the raw bytes to `AudioSegment`.  I think an easier solution might be to just support passing a codec to `AudioSegment.from_file`.

I'd be happy to contribute if this is something you see value in adding to the library.  If there's some other workaround I'm missing, please let me know.  I use this library primarily for working with `webm` files, so this is a pretty significant issue for me.

**Comment by jiaaro** [comment]
I've just added a `codec` kwarg to `AudioSegment.from_file()` which mirrors the behavior of the `codec` kwarg in AudioSegment.export()

would you mind installing from the master branch of this repo and trying:

```python
sound = AudioSegment.from_file("/path/to/file.webm", codec="libopus");
sound.export("/path/to/export.webm", codec="libopus")
```

you may also need `format="webm"` kwarg in one or both of those calls, I'm not sure - would you mind including a attaching a test webm file to this issue for inclusion in our test suite?

**Comment by jgraniero** [comment]
Hey thanks for the quick turnaround.  This does in fact work.

```python
AudioSegment.from_file('input.webm', format='webm', codec='libopus').export('output.mp3')
```

I will attach an audio file shortly, just wanted to let you know that it's working.

**Comment by jgraniero** [comment]
Here's a test file:
[test-audio.webm.zip](https://github.com/jiaaro/pydub/files/903159/test-audio.webm.zip)

You can see the issue by doing the following:

```python
good_seg = AudioSegment.from_file('test-audio.webm', format='webm', codec='libopus')
bad_seg = AudioSegment.from_file('test-audio.webm', format='webm')

# there's some silence in the file, so I'm just choosing a region that I know has sound

# this will look like normal audio data
good_seg[400:500].raw_data

# this will be mostly, if not all zeros / silence
bad_seg[400:500].raw_data
```

**Comment by jiaaro** [comment]
fixed and tests in place
