### ISSUE TITLE
Disk Image Support

### ISSUE THREAD

**Issue by kraftydevil** [jiaaro/pydub#186]
I'm backing up my music library for what hopefully will be the last time and want to see if pydub is a good fit.

I'm currently saving CD disk images as BIN/CUE files and then mounting them whenever I want to burn them to whatever format, depending on various contexts.

1) Can pydub burn from BIN/CUE, ISO, or DMG files?
2) If not directly, can I simply reference a mounted BIN/CUE, ISO, or DMG volume when using the audio_segment class?

Any guidance regarding pydub library usage or archiving strategies is much appreciated.

**Comment by jiaaro** [comment]
Pydub's focus is editing the audio content of the files, it doesn't have any support for burning CDs.

If you are able to mount a DMG (or similar) and modify that volume, then sure pydub will happily write files wherever you ask it to. I don't know if you can mount and them modify a disk image though.

**Comment by kraftydevil** [comment]
Good to know, thank you.

I don't want to modify the disk image per se - just use it as input to write mp3 output to a directory. So yeah, I guess it's technically burning a virtual CD.

Although modifying the disk image to include updated meta data would be awesome.
