### ISSUE TITLE
AttributeError: 'AudioSegment' object has no attribute 'get_array_of_samples'

### ISSUE THREAD

**Issue by kevinashaw** [jiaaro/pydub#187]
I am getting an AttributeError in the following code, which use to work well.
How is it possible for the get_array_of_samples() method not to exist?
I would report the pydub version, but I can't find a __version__ attribute in pydub objects.
Thanks.

        try:
            self.mFileAudio  = pydub.from_file(self.mFilePathName, "mp4") # There is no error reporting that I can find.
            if self.mFilePathName:
                if self.mVerbose: print(self.THISFILENAME+"::Imported mp4 file, generating LPCM...", end="")
        except Exception as e:
            print("\n")
            print(self.THISFILENAME+".init()::File not found or similar. ")
            print(self.THISFILENAME+".init()::Filename = "+self.mFilePathName)
            print(self.THISFILENAME+".init()::CWD      = "+os.path.abspath(os.path.curdir))
            print(e)
            raise(e)

        if self.mFileAudio:
            self.mFileAudio = self.mFileAudio + 6  # Amplify audio by 6dB
            self.mData = self.mFileAudio.get_array_of_samples()   << Error here

**Comment by jiaaro** [comment]
If you installed with pip, you can check your version is with `pip freeze`

`AudioSegment().get_array_of_samples()` was added in v0.16.0, so my best guess is that the installed pydub is older than that

**Comment by kevinashaw** [comment]
Perfect.  That fixed it.  I was using 
```
pip install pydub
```
But for some reason it kept installing version 0.9.  Only when I used the following command did it work:
```
pip install pydub==0.16.7
```
I have no idea why.
Anyway.  Thanks!
