### ISSUE TITLE
pydub.silence.detect_silence: Only Returning Some Silences

### ISSUE THREAD

**Issue by piercefreeman** [jiaaro/pydub#188]
### Steps to reproduce
Take a long .mp3 audio file (~8hrs) that has about 10 scattered silences approximately evenly spaced throughout the recording
Import it as an AudioSegment
Detect silence using detect_silence

### Expected behavior

`chunks = detect_silence(sound, min_silence_len=4000, silence_thresh=-60)
`

Using the above code, I would expect the code to detect all silences that are within the file.

### Actual behavior
Function returns only three silences (these are valid silences within the file) but doesn't seem to parse the rest of the file: 

[[1905584, 1913835], [3242730, 3251669], [4767363, 4775895]]

The end of the file should lie around 28,800,000ms.

### Your System configuration
- Python version: 2.7.6
- Pydub version: 0.18.0
- ffmpeg or avlib?: ffmpeg

**Comment by jiaaro** [comment]
My first intuition is that your silence threshold is too low. `-60 dBFS` is _very_ quiet.

I created the following test and it worked like you'd expect (though super slowly):
```python
from pydub.playback import play
from pydub.generators import WhiteNoise
from pydub.silence import detect_silence

wng = WhiteNoise()

parts = [wng.to_audio_segment(45*60*1000) for i in range(10)]
splits = [wng.to_audio_segment((5+i)*1000, volume=-75) for i in range(10)]

sound = splits[0]._spawn([s.raw_data for pair in zip(parts, splits) for s in pair])
len(sound)

detect_silence(sound, min_silence_len=4000, silence_thresh=-60)
```

which returned:
```python
[[2700000, 2705000],
 [5405000, 5411000],
 [8111000, 8118000],
 [10818000, 10826000],
 [13526000, 13535000],
 [16235000, 16245000],
 [18945000, 18956000],
 [21656000, 21668000],
 [24368000, 24381000],
 [27081000, 27095000]]
```

**Comment by piercefreeman** [comment]
Not sure about the root of the issue, but after switching to some higher quality audio files the problem seemed to rectify itself.  Likely was the silence threshold or perhaps ambient noise.

This ticket's good to close.
