### ISSUE TITLE
Error when attempting to crossfade with duration longer than one of the files

### ISSUE THREAD

**Issue by techlover10** [jiaaro/pydub#193]
### Steps to reproduce
Create an audio segment from a sound file.  Attempt to append a second sound file, with a crossfade duration longer than the actual sound file.

### Expected behavior
Either an error message that explains the issue, or a default to crossfading with the maximum length that would be possible.

### Actual behavior
A TooManyMissingFrames exception is thrown from an unintuitive place.

### Your System configuration
- Python version: 3.5.2
- Pydub version: 0.18.0
- ffmpeg or avlib?: ffmpeg
- ffmpeg/avlib version: 2.8.11-0ubuntu0.16.04.1

**Comment by jiaaro** [comment]
Minor update on this, that error happens when the crossfade is longer than original segment (not the one being appended).

…so in `sound1.append(sound2, crossfade=1000)`, it happens when sound1 is shorter than 1000ms.

Rereading this now I understand but that wasn't what I expected :)
