### ISSUE TITLE
Exported mp3 files doesn't show up in Finder window

### ISSUE THREAD

**Issue by fbid** [jiaaro/pydub#195]
Using the following simple script:

    from pydub import AudioSegment
    
    song1 = AudioSegment.from_mp3("input_files/test1.mp3")
    song2 = AudioSegment.from_mp3("input_files/test2.mp3")
    
    csong = song1 + song2
    
    csong.export("c.mp3",format="mp3")

The concatenated mp3 file is exported correctly, but it's not immediately visible in Finder. 

The only way to make it visible is running `killall Finder`, which forces all the Finder windows to reboot.

### Your System configuration
- Python version: 2.7.10
- pydub: latest release
- Mac OS X : 10.10.5
- ffmpeg: 3.3.1

**Comment by jiaaro** [comment]
I don't think there's anything we can do to make Finder notice the new file.

I doubt it'll make any difference, but you can try closing the file when you're done with it:

```python
# …your code…
f = csong.export("c.mp3", format="mp3")
f.close()
```
