### ISSUE TITLE
Video export support

### ISSUE THREAD

**Issue by henriquegogo** [jiaaro/pydub#198]
Could be possible to do the same that pydub does with audio but with video? It's easy to do using ffmpeg directly.
I'm just thinking... if pydub uses ffmpeg as 'engine', why isn't possible to do the same but with videos (and export the result as video)

**Comment by jiaaro** [comment]
It is certainly possible to create something like that, but I think the most straightforward way to tackle that would be to create another class like `AudioSegment` (maybe `VideoSegment`?) which handles the visual component only (so just a sequence of images, without audio) and then a higher level class like `MediaSegment` or something which manipulates the audio and video content independently.

Pydub uses ffmpeg to deal with format conversions, but all the other functionality is implemented using python/std lib/numeric libraries

**Comment by globophobe** [comment]
Have you considered https://github.com/Zulko/moviepy/ ?

**Comment by jiaaro** [comment]
Closing due to age and because video is currently (and probably will always be) outside the scope of pydub.
