### ISSUE TITLE
Why do we need to "right shift" the samples array?

### ISSUE THREAD

**Issue by Ori226** [jiaaro/pydub#200]
Hi.
I'm not sure this is the place to issue the question..

I'm trying to convert a Wav file into numpy array, manipulate it and then save it again. In the documentation, the example (copied below) shows that we need to "numpy.right_shift" the array, before continue to manipulating it. Why?

    import array
    import numpy as np
    from pydub import AudioSegment
    
    sound = AudioSegment.from_file(“sound1.wav”)
    samples = sound.get_array_of_samples()
    
    shifted_samples = np.right_shift(samples, 1)
    
    # now you have to convert back to an array.array
    shifted_samples_array = array.array(sound.array_type, shifted_samples)
    
    new_sound = sound._spawn(shifted_samples_array)

**Comment by fzyukio** [comment]
I would like to know why too.

**Comment by jiaaro** [comment]
You don’t need to right shift the samples - right shift was intended to be an example operation you would do on the array of samples (and the actual effect of a right shift depends on the bit depth of the samples - if I remember correctly, 8 and 16 bit audio use signed Ints, which again if I remember correctly, right shifting an Int is the same as floor division by 2 so this is basically just cutting the amplitude in half for most audio signals, aka 6dB quieter)
