### ISSUE TITLE
Play mp3 song without see information in console

### ISSUE THREAD

**Issue by xcbtrader** [jiaaro/pydub#203]
Hello.

While playing a song, is it possible that information is not displayed by the console?
I'm making a game and I do not want it to show anything.

Regards

**Comment by jiaaro** [comment]
The playback functions included in pydub are provided to aid debugging, I would advise you to make your own more featureful version for use in real apps (perhaps using the pyaudio method as a starting point?)

**Comment by jiaaro** [comment]
starting in pydub `v0.20.0` the ffplay prints substantially less (the banner is not printed anymore, thanks to PR #204 :) )
