### ISSUE TITLE
Can't disable logging info

### ISSUE THREAD

**Issue by spygg** [jiaaro/pydub#210]
HI guys
When i play the mp3 file use pydub, it will produce some log infomation, and i can't disable it. Just like this:

**_Input #0, wav, from '/tmp/tmpyn931rsj.wav':   0KB sq=    0B f=0/0   
  Duration: 00:00:01.73, bitrate: 256 kb/s
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 16000 Hz, 1 channels, s16, 256 kb/s
   1.72 M-A: -0.000 fd=   0 aq=    0KB vq=    0KB sq=    0B f=0/0_**  

I guess those info are generated by ffmpeg, but when i use ffmpeg in console with  **-loglevel quiet** it shows nothing !

##########################################################
HERE are the environment i use:

_ffmpeg version 3.3.2 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 20160609
  configuration: 
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100_

The sample code is https://github.com/spygg/bydict/blob/master/bydict/audio.py
**Best regard!**

**Comment by jiaaro** [comment]
Ideally ffmpeg output would be passed through the logging system and only appear if you set the appropriate logging level (probably [logging.DEBUG as shown in the README](https://github.com/jiaaro/pydub#debugging))

I _think_ it makes sense to send ffmpeg's output though the "pydub.converter" logger along with other conversion related logging

**Comment by flegac** [comment]
Just execute this before playing sounds:
```
def hack():
    from pydub import playback
    from pydub.utils import get_player_name
    from tempfile import NamedTemporaryFile

    def _play_with_ffplay(seg):
        PLAYER = get_player_name()
        with NamedTemporaryFile("w+b", suffix=".wav") as f:
            seg.export(f.name, "wav")
            subprocess.call([PLAYER, "-nodisp", "-autoexit", "-hide_banner", "-loglevel", "quiet", f.name])

    playback._play_with_ffplay = _play_with_ffplay

```
This redefine an internal function to add the `-loglevel quiet` to the ffmpeg command.
