### ISSUE TITLE
ResourceWarning: unclosed file

### ISSUE THREAD

**Issue by augustoccesar** [jiaaro/pydub#214]
When simple opening a mp3 file using:
```python
AudioSegment.from_mp3(input_path)
```

It causes the warning
> ResourceWarning: unclosed file <_io.BufferedReader name='fake/path'>
  return cls.from_file(file, 'mp3', parameters)

I fixed it in my environment by changing the line 432 in the `audio_segment.py` file from
```python
file = _fd_or_path_or_tempfile(file, 'rb', tempfile=False)
```
to
```python
with _fd_or_path_or_tempfile(file, 'rb', tempfile=False) as file:
```
and put all the content bellow inside the `with` so it autoclose the file.

But it also can be put lower inside the `_fd_or_path_or_tempfile` method where the
`open()` is called.

**Comment by jiaaro** [comment]
Thanks for reporting this! 

What OS did you get this warning on? windows? also which version of python?

**Comment by augustoccesar** [comment]
Hello @jiaaro ,

I'm using `MacOS Sierra 10.12.4` and `Python 3.6.0`

**Comment by Vital95** [comment]
I have tried your solution - did not helped.
But thanks anyway.

**Comment by brennv** [comment]
After trying unsuccessfully to invoke the `py.warnings` logger with `logging.captureWarnings(True)`, I was able to reproduce this issue with the help of `pytest`.

```python
# show_warnings.py
import warnings
import pydub
import pytest

@pytest.mark.filterwarnings('error')
def test_func():
    pydub.AudioSegment.from_file("./test/data/test1.mp3")
    warnings.warn('trigger py.warnings')
```

Which runs with:

```
pip install pytest
pytest show_warnings.py
```

Revealing the warning:

```
------------------------------------ Captured stderr call -------------------------------------
Exception ignored in: <_io.FileIO name='./test/data/test1.mp3' mode='rb' closefd=True>
ResourceWarning: unclosed file <_io.BufferedReader name='./test/data/test1.mp3'>
```

**Comment by brennv** [comment]
As it turns out, there's an easier way to reproduce this:
```
python3 -W default -c 'import pydub; pydub.AudioSegment.from_file("./test/data/test1.mp3")'
```

Shows:
```
-c:1: ResourceWarning: unclosed file <_io.BufferedReader name='./test/data/test1.mp3'>
```
