### ISSUE TITLE
Concatenation with silence between two files

### ISSUE THREAD

**Issue by vitaly-zdanevich** [jiaaro/pydub#215]
Good day, I need to merge/concat few ogg and export to the one aac. Is it possible to add a silence between concatenated files? Maybe I can generate silence? Looks like without that I will need to create a `silence.ogg` and use it as a glue between every chunk. Thank you.

**Comment by jiaaro** [comment]
yup, you can use `AudioSegment.silent(…)` like so:

```python
from pydub import AudioSegment

ten_second_silence = AudioSegment.silent(duration=10000)
```

for more info see [the API docs](https://github.com/jiaaro/pydub/blob/master/API.markdown)

**Comment by vitaly-zdanevich** [comment]
Thank you.
