### ISSUE TITLE
Appending two segments generates a segment of length less than the sum of the two segments

### ISSUE THREAD

**Issue by yacc** [jiaaro/pydub#219]
### Steps to reproduce
Run this exemple with after unzipping the two audio files attached

```python
from pydub import AudioSegment

sample1 = AudioSegment.from_wav("90-riff-hip-hop-G-09.wav")
sample2 = AudioSegment.from_wav("90-riff-hip-hop-G-10.wav")

samples = [sample1, sample1]
combined = samples[0]

for song in samples[1:]:
    combined = combined.append(song, crossfade=2000)

combined.export("output.wav", format="wav")
```
with the following:
```csh
➜ sox 90-riff-hip-hop-G-09.wav -n stat
Samples read:            940800
Length (seconds):     10.666667
Scaled by:         2147483647.0
```
and 
```csh
➜ sox 90-riff-hip-hop-G-10.wav -n stat
Samples read:            940800
Length (seconds):     10.666667
```
[audio_files.zip](https://github.com/jiaaro/pydub/files/1349088/audio_files.zip)

### Expected behavior
The length of the output file should be the sum of the length of the two input files.
10.666667 + 10.666667 = 21.333334

### Actual behavior
Size is `length1 + length2 - crossfade_length`, where `crossfade_length` is the length of the crossfade.
```csh
➜ sox output.wav -n stat
Samples read:           1705256
Length (seconds):     19.333968
```

### Your System configuration
- Python version: Python 3.5.1
- Pydub version: pydub (0.16.4)
- ffmpeg or avlib?: not sure
- ffmpeg/avlib version: ffmpeg 3.3.4/libav 12.2

### Culprit code
The following code in `pydub/audio_segment.py:956` creates a crossfaded segment in a way that is not what a crossfade would typically do. 

```python
        xf = seg1[-crossfade:].fade(to_gain=-120, start=0, end=float('inf'))
        xf *= seg2[:crossfade].fade(from_gain=-120, start=0, end=float('inf'))

        output = TemporaryFile()

        output.write(seg1[:-crossfade]._data)
        output.write(xf._data)
        output.write(seg2[crossfade:]._data)
```
The expected behavior is to generate a segment of length the sum of the two original segments by appending both segment while applying the following (in pseudo code) and for a linear xfade:

```python
       xf1 = seg1[-crossfade:].fade(from 100% to 50%)
       xf2 = seg2[:crossfade].fade(from 50% to 100%)

        output = TemporaryFile()

        output.write(seg1[:-crossfade]._data)
        output.write(xf1._data)
        output.write(xf2._data)
        output.write(seg2[crossfade:]._data)
```

**Comment by jiaaro** [comment]
the method you propose (with `xf1` and `xf2`) ensures the output has a duration that is the sum of the two audio segments, but the cross fade is not a crossfade it's a fade out and then a fade in (a crossfade would play both simultaneously )
