### ISSUE TITLE
Expose result as a file-like object, without need to export

### ISSUE THREAD

**Issue by john-bonachon** [jiaaro/pydub#220]
Would it be possible to expose result as a file-like object, without needing to export it?

i.e.

```
>>> audio = AudioSegment.from_file("the_file.ext")
>>> type(audio.file)
>>> <_io.BufferedReader name='the_file.ext'>
```

**Comment by cruxicheiros** [comment]
Hi @john-bonachon!
If you're asking what I think you're asking, you can access the audio data in the form of a bytestring with `AudioSegment(...).raw_data`. This is documented in [API.markdown](https://github.com/jiaaro/pydub/blob/master/API.markdown).

**Comment by jiaaro** [comment]
@john-bonachon Either the raw data for the audio samples like @cruxicheiros suggested, or if you want the complete audio file you'll need to do:

```python
import io
f = io.BytesIO()
audio.export(f, format='wav')
```

The raw audio data does not include any headers that would normally be in an audio file (the meta data is stored in the audio segment separately from the audio samples)

**Comment by john-bonachon** [comment]
great. thought `.export` accepted a string (filename) as parameter, but it actually accepts a file object, so it can be an `io.BytesIO` instance. thanks!

**Comment by jordyjwilliams** [comment]
@jiaaro thanks for that solution! Had been looking for a way to do this exporting the `raw_format` data with RIFF headers.

A side note... It could be nice if when supplied on creation (eg on a wave file) there was a way to access this directly.

Example
```python
seg = AudioSegment.from_wav(io.BytesIO_object_with_headers)
seg.raw_data  # contains headers already.
```

Totally understand if that's out of the scope of what's necessary. It is admittedly a very edge case as to where one woudl want this.

**Comment by tibbe** [comment]
I was initially confused about this as well and it turns out that pydub-stubs has the wrong type for `export` (and `from_file`) which made me think those don't accept file-like object while they actually do: https://github.com/clo4/pydub-stubs/issues/5
