### ISSUE TITLE
Effects.strip_silence method returns only the first part of mp3 file

### ISSUE THREAD

**Issue by danaggray** [jiaaro/pydub#228]
### Steps to reproduce
Apply strip_silence method to short mp3 file
audio_out = effects.strip_silence(temp_audio, silence_len=1000, silence_thresh=-50, padding=100)
Export altered audio segment to new 'wav' file
audio_out.export(output_file_path, format="wav")

### Expected behavior
Should have an audio file with most of the 'silence' section removed, 1 sec of padding.

### Actual behavior
I get the first 'chunk' of audio as the resultant file. The second chunk is not properly appended. I was able to add a code snippet to output the chunks at ~ effects.py line 108 and the chunk.wav files produced are what I would expect, but ~ line 112 of effects.py where the appending happens does not appear to be succeeding, though it looks like the actual issue may be ~line 978 in the audio_segment.py _spawn method. I think the segments are getting handled correctly just before that.

### Your System configuration
- Python version: 2.7
- Pydub version: v0.20.0
- ffmpeg or avlib?: ffmpeg
- ffmpeg/avlib version: 20170918 win64

### Is there an audio file you can include to help us reproduce?
You can include the audio file in this issue - just put it in a zip file and drag/drop the zip file into the github issue.

[ashortIntroTest.zip](https://github.com/jiaaro/pydub/files/1435795/ashortIntroTest.zip)

**Comment by mikejcorey** [comment]
This appears to be happening for me as well -- basically a show-stopper for me. I'm using detect_nonsilent, but the effect seems to be the same.

**Comment by TuBui** [comment]
There is a bug in the [strip_silence()](https://github.com/jiaaro/pydub/blob/master/pydub/effects.py#L110) method:

```
seg = chunks[0]
for chunk in chunks[1:]:
    seg.append(chunk, crossfade=crossfade)

```
The developer seems to forget that seg.append() return a new object instead of appending to the existing object. To fix it:

```
seg = chunks[0]
for chunk in chunks[1:]:
    seg = seg.append(chunk, crossfade=crossfade)
```

**Comment by derek-adair** [comment]
Submit a PR, this is important.

**Comment by jiaaro** [comment]
A PR was submitted and accepted (sort of a long time ago. v0.22.0 I think – sorry for the delay in dealing with issued)
