### ISSUE TITLE
Converting from PyAudio str to AudioSegment returns errors

### ISSUE THREAD

**Issue by ksigWyatt** [jiaaro/pydub#235]
### Steps to reproduce
See my main file [here](https://github.com/ksigWyatt/Embedded_Compressor/blob/Issue/compressor/Server/MainHandler.py)

### Expected Behavior
Working on creating an embedded compression system, similar to those found on professional audio mixers. The program is supposed to read incoming audio signal from a microphone, compress the audio if the level gets too loud and continue streaming the sound to the speakers, all in real time. I am capturing audio samples using `PyAudio` via [the given "wire" example](https://github.com/djfroofy/PyAudio/blob/master/test/wire.py). Those "samples" are sectioned into chunks thanks to the library and streamed shortly after recording. I'm simply attempting to compress them if they are too loud.

The types which are being used are:
- data = samples from the stream `<type 'str'>` - _Unicode string_
- chunk = batch of audio bytes `<type 'int'>` - _always returns 1024_
- capture_stream_write = variable created to capture from stream.write(data, chunk) <type 'NoneType'>
- compressed_segment = `<class 'pydub.audio_segment.AudioSegment'>`

### Actual Behavior
PyAudio returns as a `string` from the method `stream.read()`.
I need the ability to convert these string samples to the AudioSegment object in order to use the compression function. It would be perfect if each "chunk" was able to be compressed.

As a result, what ends up happening is I get a combination of a few errors depending on how I have everything setup. I know that it's not the right type. So how can I make this type conversion work?

**1.** Creating a "wave" object before compression: 
```
wave_file = wave.open(f="compress.wav", mode="wb")
wave_file.writeframes(data)
frame_rate = wave_file.getframerate()
wave_file.setnchannels(2)
# Create the proper file
compressed = AudioSegment.from_raw(wave_file)
compress(compressed) # Calling compress_dynamic_range
```

> Exception wave.Error: Error('# channels not specified',) in <bound method Wave_write.__del__ of <wave.Wave_write instance at 0x000000000612FE88>> ignored

**2.** Sending RAW PyAudio data to compress method:
```
data = stream.read(chunk)
compress(chunk) # Calling compress_dynamic_range
```

> thresh_rms = seg.max_possible_amplitude * db_to_float(threshold)
AttributeError: 'int' object has no attribute 'max_possible_amplitude'

 **3.** Sending capture_stream_write to compress method: 
> AttributeError: 'NoneType' object has no attribute 'max_possible_amplitude'

### System Config
- Python version: `2.7.13 :: Anaconda 4.4.0 (64-bit)`
- Pydub version: Most Recent - `v0.20.0`
- ffmpeg or avlib?: ffmpeg
- ffmpeg/avlib version: N-86669-gc1d1274

**Comment by ksigWyatt** [comment]
After learning from my silly mistakes I've mended the first error but still facing this error. 
> AttributeError: Wave_write instance has no attribute 'seek'first 

_I suspect that you'd have to convert to a `wave_read` object first_

**Comment by ksigWyatt** [comment]
Got it working. Now just have to go back to String for PyAudio to work right

> TypeError: argument 2 must be string or read-only buffer, not AudioSegment

**Comment by jiaaro** [comment]
for that last bit you’ll probably want `sound.raw_data`

**Comment by ksigWyatt** [comment]
That works, it's not the fluid playback that I'd like because it's making little temp wav files and compressing those in real time - but at least it works.

**Comment by jiaaro** [comment]
if you have raw wave data you should be able to instantiate AudioSegments directly instead of using the from_file() classmethod:

```python
data = stream.read()
sound = AudioSegment(data, sample_width=2, channels=2, frame_rate=44100)
```

**Comment by ksigWyatt** [comment]
My type conversion is working now, so I'll close this issue
