### ISSUE TITLE
Allow overriding binary path e.g. set ffmpeg binary to /usr/local/bin/ffmpeg

### ISSUE THREAD

**Issue by jwkvam** [jiaaro/pydub#242]
### Steps to reproduce
I use conda, my conda environment has ffmpeg in it because some other packages use it. Unfortunately this ffmpeg doesn't have many features and it fails to encode/decode things.

### Expected behavior
I use macos and have ffmpeg installed by homebrew. I prefer conda binaries for most things (e.g. python) so that path has higher priority than homebrew's install path. I would like to be able to specify the ffmpeg binary like `/usr/local/bin/ffmpeg`. I'd rather not have to futz with `$PATH`.

### Actual behavior
Right now it finds ffmpeg installed by conda and it fails to open an mp3.

### Your System configuration
- Python version: Conda 3.6.4
- Pydub version: 0.20.0
- ffmpeg or avlib?: ffmpeg
- ffmpeg/avlib version: 3.4.1

### Is there an audio file you can include to help us reproduce?
Any mp3 will do.

**Comment by derek-adair** [comment]
This is not a reasonable ask.  This is a very specific issue and off topic...

Just modify $path.

**Comment by derek-adair** [comment]
Submit a PR - its rather innocuous.

**Comment by jwkvam** [comment]
>
> This is not a reasonable ask. This is a very specific issue and off
> topic...
> Just modify $path.



> Submit a PR - its rather innocuous.


No problem, I'll stay out of this repo.

>

**Comment by jiaaro** [comment]
@jwkvam Sorry for the extremely long delay in responding, this should actually be possible already:

```python
from pydub import AudioSegment

AudioSegment.converter = "/path/to/ffmpeg"
```

@derek-adair I appreciate the energy and enthusiasm (really!), but also it's important to the project to respect the requests and questions of others, even if you don't necessarily agree with their goals or approach. Thank you for your help in managing the issues, I certainly havn't had time to address the growing pile of tickets :)
