### ISSUE TITLE
Cannot open .wav without ffmpeg

### ISSUE THREAD

**Issue by Hyperclaw79** [jiaaro/pydub#245]
### Steps to reproduce
Try to execute:
```py
from pydub import AudioSegment
sound = AudioSegment.from_wav('hello.wav')
```
### Expected behavior
Successfully open the wav file without relying on ffmpeg for installation.
>You can open and save WAV files with pure python.

### Actual behavior
Looks like the import of pydub checks for ffmpeg. There should be a check to prevent this for the use case requiring only `wav` files. 

### Your System configuration
- Python version: 3.6.4
- Pydub version: 0.20.0
- ffmpeg or avlib?: None installed
- ffmpeg/avlib version:

**Comment by jiaaro** [comment]
This has been fixed and a unit test has been added (kind of a long time ago, sorry about the delay in updating the issue)
