### ISSUE TITLE
WAV conversion failed

### ISSUE THREAD

**Issue by tlc** [jiaaro/pydub#248]
### Steps to reproduce
            snip.export(fname + '.wav', format='wav', bitrate='16k',
                        parameters=['-ac', '1', '-sample_fmt', 's16'])

### Expected behavior
I'm trying to create 16k, mono WAV snippets from 48K stereo.

### Actual behavior
The results are 48K stereo.

I'm guessing since you avoid ffmpeg for WAV, some conversions
aren't supported.  Especially since 'parameters' is explicitly ffmpeg arguments.

### Your System configuration
- Python version:  2.7.2
- Pydub version: 0.20.0
- ffmpeg or avlib?: ffmpeg
- ffmpeg/avlib version: 2.8.11-0ubuntu0.16.04.1

**Comment by jiaaro** [comment]
The recommended way to do this for wav files is `snip.set_frame_rate(16000).set_channels(1).export(…)`

**Comment by chussong** [comment]
I just encountered this and spent hours trying to figure out why my parameters weren't working through Pydub even though they worked when invoking ffmpeg from a terminal. Looking through the documentation gave no hint as to why this was happening, but upon checking the source code I see that the `parameters` argument is simply silently ignored when converting to raw or wav. 

In my opinion, it's fair to assume that anyone who goes to the trouble of specifying a keyword argument expects it to be read by the function. I think any of the following is reasonable:

- Always invoke ffmpeg if `parameters` is provided
- Raise an exception if `parameters` is provided for raw or wav export
- Actually parse the `parameters` argument to check for things which will affect the parameters of the `wave_data` and adjust them accordingly

I can implement any of these myself but I'd like to hear the opinions of people who are more familiar with the library.

**Comment by derek-adair** [comment]
1st is probably desirable.  

@jiaaro was there any reason this was designed this way?  It seems like this should always go through ffmpeg or libav?

**Comment by jiaaro** [comment]
pydub is supposed to support wave files without requiring ffmpeg since pydub can read wave files using the stdlib `wave` module (same for raw, which is just a wave file without headers)

I agree that when parameters is provided we should assume the user wants to use ffmpeg/libav

**Comment by chussong** [comment]
OK, I agree that seems like the best balance between maintainability and correct functionality.

I'll make a pull request "soon".

**Comment by chussong** [comment]
It turned out that allowing codecs and parameters for raw output is more difficult than it sounds, so I implemented the ffmpeg call for wav and raised an exception for raw. See #393 for the specific proposal.

**Comment by derek-adair** [comment]
Let me clarify that i do not feel passionate about the following, just spit-balling;

>pydub is supposed to support wave files without requiring ffmpeg

This _seems_ a bit off from a design point of view; i'd expect pydub to _always_ use my installed audio library.  I may have specific features enabled or disabled via said library.  I would have to dig deeper, but i suspect this feature (wav support w/o ffmpeg/libav) creates other similar predicaments.

It could be interesting to detect ffmpeg/libav installation and limit functionality accordingly.  This could be as simple as throwing a warning, stating you can only read/save wav's.  It would leave open the possibility to fail more gracefully (less bug reports).

**Comment by jiaaro** [comment]
@derek-adair yeah, I mostly agree – the reason it doesn't call into ffmpeg for wave is that wave format is the input to ffmpeg, and it seemed pointless to have ffmpeg convert from wave to wave. For all format conversions, pydub produces a wave and then passes that into ffmpeg.

**Comment by chussong** [comment]
Perhaps it's the fact that my native language is C++, but I'm 100% fine with pydub doing whatever it wants internally [as long as it behaves "as-if"](https://en.cppreference.com/w/cpp/language/as_if) the conversion with ffmpeg was actually performed. The wav shortcut seems like a reasonable optimization as long as the resulting wav file actually is the same as the one the user requested. I think we can be confident this is true if no `codec` or `parameters` are specified, unless I'm missing something?

That said, if ffmpeg is smart enough to figure out when no conversion is required and just copy the file, the overhead might not be too bad. I guess we should do some quick benchmarks and see how different the cases are? If people are relying on pydub to save large batches of wav files quickly I don't want to break that.

**Comment by derek-adair** [comment]
@chussong "behaves as-if" is a great way of saying what i was thinking, however, i think the purpose here is for compatibility.  PyDub is to work w/ wave files w/o ffmpeg or libav.

I could be wrong, but i'd be surprised to find many users that are _intentionally_ avoiding ffmpeg/libav.  It hamstrings this entire project to not use them.  So i think we either;

-  Deprecate the stdlib funcitonality, make ffmpeg/libav a requirement.
- Follow the "as-if" rule
- Possibly a "compatibility mode" that throws errors (not warnings) for using any functions that require audio libraries that are not there.  This would probably be the most work...
