### ISSUE TITLE
Consider releasing a new version

### ISSUE THREAD

**Issue by naktinis** [jiaaro/pydub#250]
The last release (`v0.20.0`) was half a year ago. Some really useful features like [slicing by step](https://github.com/jiaaro/pydub/commit/491bfc9522152c727c0d185b1d6c3491aa7e1e37) are not available in the version uploaded to PyPI, for example.

**Comment by jiaaro** [comment]
That chunking feature is actually why I’ve hesitated - it somewhat breaks from the standard behavior of slicing - it is, however much more useful than an AudioSegment containing every third millisecond (for example)

**Comment by jiaaro** [comment]
v0.21.0 is now available on pypi
