### ISSUE TITLE
Export mp3 add 50ms blank at start and 20ms at end

### ISSUE THREAD

**Issue by ChoiZ** [jiaaro/pydub#251]
### Steps to reproduce
```
out_f = open("/path/"+filename+".mp3", 'wb')
playlist.export(out_f, format="mp3", bitrate="192k")
```

### Expected behavior
Music start directly without blank and end without blank

### Actual behavior
Music start with blank and finish with blank

### Your System configuration
- Python version: 2.7.13
- Pydub version: 0.20
- ffmpeg or avlib?: ffmpeg
- ffmpeg/avlib version: 3.2.8-1

### Is there an audio file you can include to help us reproduce?
http://i.imgur.com/xeyko3B.png
http://i.imgur.com/ddk0VWl.png

**Comment by ChoiZ** [comment]
Ok it's lame encoder : https://superuser.com/a/856879/284686
I try to encode into wav and no problem.

**Comment by styk-tv** [comment]
Well... that is totally LAME! Hello audience... excuse the 50ms loop gap in my LAME encoder :)
