### ISSUE TITLE
Can pybud open "audio/webm;codecs=opus" audio from a <class:byte> object

### ISSUE THREAD

**Issue by git-ankur-shukla** [jiaaro/pydub#257]
### Expected behavior
I am recording some audio using react-mic which gives me the output in the form of "audio/webm;codecs=opus" encoded blob. I send this blob via a POST request to a django backend for processing and Google Speech Recognition. 
Can I use pydub to access the blob in django which is in a byte class object?
I need to convert the audio to mono and get some of its properties and then send it to Google Speech API.

**Comment by jiaaro** [comment]
You can give a file-like object (including BytesIO) to `AudioSegment.from_file()` but you'll need to specify the format like:

```python
from io import BytesIO
from pydub import AudioSegment

opus_data = BytesIO(opus_audio_bytes)

sound = AudioSegment.from_file(opus_data, codec="opus")
```

you may have to mess around with the codec arg. You can ask ffmpeg for a list of available codecs using `ffmpeg -codecs` (or `avconv -codecs` if you use libav)

**Comment by jiaaro** [comment]
I think this is resolved, closing :)

**Comment by git-ankur-shukla** [comment]
@jiaaro thanks for the response. :)

**Comment by sshehata** [comment]
I spent a very long time trying to get the same thing to work so I thought I would share my experience.
This did not work for me:
```
sound = AudioSegment.from_file(opus_data, codec="opus")
```
But this did:
```
sound = AudioSegment.from_file(opus_data, codec="webm")
```
