### ISSUE TITLE
function "export" : can not change wav to mp3?

### ISSUE THREAD

**Issue by canon99** [jiaaro/pydub#258]
# code as fellow
```
from pydub import AudioSegment
sound = AudioSegment.from_file("1.wav", format="wav")
sound.export("2.mp3", format="mp3")
```

# result
create a new empty file "2.mp3", i think it should be the same content with 1.wav, help me, thx a lot..

**Comment by jiaaro** [comment]
if you add the following what is the output?

```python
print(len(sound))
print(sound.dBFS)
```

**Comment by canon99** [comment]
thx for helping.
# output is
'''
len(sound) = 15282
sound.dBFS = -16.791599592815224
'''

# some more try
i am watching [another issue in pydub](https://github.com/jiaaro/pydub/issues/5)
1. if i use `ffmpeg -y -f wav -i ./1.wav -f mp3 ./2.mp3`, it will work well (mp3 file not 0 byte)
2. if i use pydub, the code as `sound.export("2.mp3", format="mp3")`, it will show the error like below:

‘’‘
C:\ProgramData\Anaconda3\lib\site-packages\pydub\utils.py:165: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
15282
-16.791599592815224
Traceback (most recent call last):
  File "F:/CodingTests/python/AudioCall/AudioPress.py", line 6, in <module>
    sound.export("1", format="mp3")
  File "C:\ProgramData\Anaconda3\lib\site-packages\pydub\audio_segment.py", line 678, in export
    p = subprocess.Popen(conversion_command, stdin=devnull, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 1224, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
‘’‘

**Comment by canon99** [comment]
converter should be what?
`AudioSegment.converter = "C:\\ProgramData\\Anaconda3\\Lib\\ffmpeg"`
or
`AudioSegment.converter = "C:\\ProgramData\\Anaconda3\\Lib\\ffmpeg\\bin\\ffmpeg.exe"`

**Comment by jiaaro** [comment]
it should be a path ending in `ffmpeg.exe` but the specific location depends where you have it installed

**Comment by LethaboMotsoaledi** [comment]
Hi @jiaaro. Does this error look familiar? Thanks
![test3](https://user-images.githubusercontent.com/37307703/37315826-5bd5bbbc-2664-11e8-807f-bc28b77dc3e7.PNG)
![capture](https://user-images.githubusercontent.com/37307703/37315828-5c1df8f0-2664-11e8-9f1c-8c31c9c6c037.PNG)

**Comment by jiaaro** [comment]
@LethaboMotsoaledi If you are using avconv you will need to set the converter path to the avconv binary (so something ending in avconv.exe)

regardless, yes that is what you see when python is unable to find the executable you are trying to run in the subprocess (in this case, either ffmpeg or avconv)

**Comment by jiaaro** [comment]
closing due to age.
