### ISSUE TITLE
Question: How to only append raw data but not re-encode?

### ISSUE THREAD

**Issue by cofinley** [jiaaro/pydub#259]
I am wanting to append bytes to the raw data of a song (for steganography purposes), but I don't want to re-encode the song since the original bytes won't be preserved. Wav is lossless, but I need the output to be mp3 specifically.

Ideally, I'd want to look at the raw audio data, append to it, but then save the mp3 as is with the new audio data, without exporting it. Is this possible with pydub, or should I go for more of a low-level approach? I'm a little out of my depth here so any help is appreciated.

### Your System configuration
- Python version: 3.6
- Pydub version: 0.21.0
- ffmpeg or avlib?: ffmpeg
- ffmpeg/avlib version: N-82215-g3932ccc

**Comment by cofinley** [comment]
I tried to find the audio byte data in the file’s bytes read in from I/O but it seems the audio data is interpreted in a different way?

**Comment by jiaaro** [comment]
pydub converts everything to an array of samples (essentially wav format) when you instantiate an AudioSegment object. I've had mixed results with just truncating mp3 data though. Might be worth a shot. My understanding is that MP3 encodes the audio data in chunks so if you use CBR (constant bit-rate) you should be able to just measure the number of bytes to break the audio data on the chunk boundaries.

Hope this helps :)

**Comment by cofinley** [comment]
Thanks, I'll give that a shot!
