### ISSUE TITLE
Slicing [::dur_in_ms] seems to constantly slice into 1ms (0.000997732426304) intervals

### ISSUE THREAD

**Issue by stigwue** [jiaaro/pydub#260]
### Steps to reproduce
1. read in audio_sample of any length (I read 15s of an mp3)
2. run the following code
```
print 'audio read is ' + str(audio_sample.duration_seconds) + ' seconds'
t = 3
print 'slicing into intervals of ' + str(t) + 's'
slices = audio_sample[::(t * 1000)]
print 'audio sliced into ' + str(len(slices)) + ' slices'
print 'first slice is ' + str(slices[0].duration_seconds) + 's'
```

### Expected behavior
audio read is 15.0 seconds
slicing into intervals of 3s
audio sliced into 5 slices
first slice is 3s

### Actual behavior
audio read is 15.0 seconds
slicing into intervals of 3s
audio sliced into 15000 slices
first slice is 0.000997732426304s

### Your System configuration
- Python version: 2.7.10
- Pydub version: 0.20.0
- ffmpeg or avlib?: ffmpeg
- ffmpeg/avlib version: 3.4.2

### Is there an audio file you can include to help us reproduce?
No.

**Comment by jiaaro** [comment]
slicing into chunks is a new behavior - can you confirm that you’re on the latest version of pydub

**Comment by stigwue** [comment]
Thanks. The problem was for v0.20.0. Now the chunks are of the right size (v0.21.0) and now is a generator element so len() no longer applies!
