### ISSUE TITLE
cannot get libav nor ffmpeg

### ISSUE THREAD

**Issue by mctaichi** [jiaaro/pydub#265]
Hi, all. I am working on Raspberry pi zero W to run pydub on python3.5. 
But I have a problem in first step. I cannot get libav nor ffmpeg by following command.
```
# libav
apt-get install libav-tools libavcodec-extra-53

####    OR    #####

# ffmpeg
apt-get install ffmpeg libavcodec-extra-53
```
Both resulted into "package ... not found".
For confirmation, I tried "import pydub" in python3 script, but failed getting following message.
```
/home/pi/.local/lib/python3.5/site-packages/pydub/utils.py:165: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
```
How can I solve it?

### My System configuration
- Python version: 3.5.3
- Pydub version: 0.21.0
- ffmpeg or avlib?: cannot install
- ffmpeg/avlib version:

**Comment by hXtreme** [comment]
Can you try to download the [FFmpeg source](https://github.com/FFmpeg/FFmpeg) and compile it on it on your rpi0?

I don't have an rpi0 so I can't verify if it would work.
