### ISSUE TITLE
How to convert two mono audio files to one stereo file

### ISSUE THREAD

**Issue by Extrablue** [jiaaro/pydub#271]
Forgive me if there is an easy solution, but I can't seem to figure out how to combine to mono wav files into one stereo track.

It's easy to do the other way around (https://github.com/jiaaro/pydub/issues/229) though.

Any thoughts?

**Comment by jiaaro** [comment]
I think you’re looking for [`AudioSegment.from_mono_audiosegments()`](https://github.com/jiaaro/pydub/blob/master/API.markdown#audiosegmentfrom_mono_audiosegments)

**Comment by Extrablue** [comment]
Thank you very much. Missed that one.

**Comment by olawalejuwonm** [comment]
@jiaaro @Extrablue can one wav file be converted to stereo as well?
