### ISSUE TITLE
Concatenating multiple wav file in one.

### ISSUE THREAD

**Issue by david-aksnes-2013** [jiaaro/pydub#282]
I am on python programming language, I want to join multiple wav files one by one. I do not know how many wav files before concatenating. I found [this method](https://stackoverflow.com/questions/2890703/how-to-join-two-wav-files-using-python?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa) which only concatenating two wav files together.

The mimic code I try is:

```
import os
from pydub import AudioSegment

wav_names = ['wav_0', 'wav_1', 'wav_2'] # more than 3 files...
wav_paths:  ['/home/Desktop/tmpowtse1k6.wav', '/home/Desktop/tmpcnm7rljh.
wav', '/home/Desktop/tmpyofbtrvk.wav']

def _concatenate_wav(orders, wavs):                                                  
    combined_wav = None                                                                             
    for order, wav in zip(orders, wavs):                                                            
        order = AudioSegment.from_wav(wav)                                                          
        combined_wav += order                                                                       
    combined_wav.export(os.path.join(os.path.dirname(__file__), "output.wav"), format="wav")     

if __name__ == "__main__"
    _concatenate_wav(wav_names, wav_paths)
```

The result in console I get is:

      File "server.py", line 105, in _concatenate_wav
        combined_wav += order
      File "/home/user/.local/lib/python3.5/site-packages/pydub/audio_segment.py", line 305, in __radd__
        raise TypeError("Gains must be the second addend after the "
    TypeError: Gains must be the second addend after the AudioSegment

I solved this problem before with sox:

```
from subprocess import call
......
call(["sox", "*.wav", "output.wav"])

```
my friend, however, told me that calling Linux command within python is going to slow down the execution.

Can anyone help??please kindly suggest to how to solve these prob...

Thanks in advance

---------------------------------------------------------------------------------------------------------------------------------------
- Python version:  Python 3.5.2
- Pydub version: pydub-0.22.0
- ffmpeg or avlib?: ffmpeg
- ffmpeg/avlib version: ffmpeg version 2.8.14

Wav files: (similar like this)
[wav.tar.gz](https://github.com/jiaaro/pydub/files/2038272/wav.tar.gz)

**Comment by david-aksnes-2013** [comment]
I figure it out. :)

**Comment by c0bra** [comment]
![what did you see](https://imgs.xkcd.com/comics/wisdom_of_the_ancients.png)

**Comment by jiaaro** [comment]
@c0bra The issue here is that pydub allows `sound += 6` to increase gain by 6 dB. but in the loop, during the first time through, you have essentially `None + sound`. The error is telling you you have to have the audio segment on the left and the gain on the right. But really the solution here is to use `AudioSegment.empty()` instead of `None` at the beginning of the loop:

```python
combined_wav = AudioSegment.empty()
for order, wav in zip(orders, wavs):                                                            
    order = AudioSegment.from_wav(wav)                                                          
    combined_wav += order                 
```

**Comment by c0bra** [comment]
@jiaaro Yea I ended up doing:

```python
wavs = [AudioSegment.from_wav(wav['path']) for wav in wavset]
combined = wavs[0]

for wav in wavs[1:]:
    combined = combined.append(wav)
