### ISSUE TITLE
change Audiosegment to ndarray for librosa to add effect

### ISSUE THREAD

**Issue by bzvew** [jiaaro/pydub#289]
I wonder how to change Audiosegment to float32 ndarray for librosa to manipulate.

**Comment by jiaaro** [comment]
Have you tried using [‘AudioSegment(…).get_array_of_samples()`](https://github.com/jiaaro/pydub/blob/master/API.markdown#audiosegmentget_array_of_samples)?

**Comment by AbbyYangbb** [comment]
You can get "array.array"object by using ```AudioSegment(…).get_array_of_samples()```, for example
,
```ar = chunk.get_array_of_samples()```
and if you want to get numpy.ndarray, try:
```import numpy as np
ar = np.array(ar)```

**Comment by zhenql** [comment]
> You can get "array.array"object by using `AudioSegment(…).get_array_of_samples()`, for example
> ,
> `ar = chunk.get_array_of_samples()`
> 
> and if you want to get numpy.ndarray, try:
> `import numpy as np`
> `ar = np.array(ar)`

the type of data x is int and |x| may more than 1, but the type of librosa is float32 and less than 1.
how to use x generated from pydub in librosa?

**Comment by mattc-eostar** [comment]
And how to change back to AudioSegment?

**Comment by jiaaro** [comment]
@mattc-eostar That's [covered in the docs](https://github.com/jiaaro/pydub/blob/master/API.markdown#audiosegmentget_array_of_samples):

```python
from pydub import AudioSegment
sound = AudioSegment.from_file("sound1.wav")

samples = sound.get_array_of_samples()

# then modify samples...

new_sound = sound._spawn(samples)
```

**Comment by mattc-eostar** [comment]
Ah, perfect. Thank you!

[cid:image001.png@01D54857.D590D110]
Matt Conflitti
Data Scientist
Rutherford and Associates
1009 Productions Ct • Holland, MI 49423
P: (616) 392-5000 • F: (616) 392-1178
www.eostar.com<http://www.eostar.com/> • Visit us on LinkedIn<http://www.linkedin.com/company/rutherford-&-associates>
[signature_1538161222]
