### ISSUE TITLE
Fail test in macOS 

### ISSUE THREAD

**Issue by skar404** [jiaaro/pydub#292]
Fail test in macOS:

- [test_export_as_ogg](https://github.com/jiaaro/pydub/blob/master/test/test.py#L567), 
- [test_export_forced_codec](https://github.com/jiaaro/pydub/blob/master/test/test.py#L576), 
- [test_export_mp3_as_ogg](https://github.com/jiaaro/pydub/blob/master/test/test.py#L702), 
- [test_export_mp3_as_webm](https://github.com/jiaaro/pydub/blob/master/test/test.py#L714), 
- [test_export_mp4_as_ogg](https://github.com/jiaaro/pydub/blob/master/test/test.py#L720), 
- [test_exporting_to_ogg_uses_default_codec_when_codec_param_is_none](https://github.com/jiaaro/pydub/blob/master/test/test.py#L883)

```
Traceback (most recent call last):
  File "/Users/users/project/pydub/test/test.py", line 573, in test_export_as_ogg
    exported_ogg = seg.export(format='ogg')
  File "/Users/users/project/pydub/test/pydub/audio_segment.py", line 868, in export
    p.returncode, conversion_command, p_err))
pydub.exceptions.CouldntEncodeError: Encoding failed. ffmpeg/avlib returned error code: 1

Command:['avconv', '-y', '-f', 'wav', '-i', '/var/folders/z1/z1pzg4cj7k3cw5fbbhq58r740000gn/T/tmpqou5gh72', '-acodec', 'libvorbis', '-write_xing', '0', '-f', 'ogg', '/var/folders/z1/z1pzg4cj7k3cw5fbbhq58r740000gn/T/tmpanhhu88i']
```

### Your System configuration
- Python version: 3.6.4
- Pydub version: https://github.com/jiaaro/pydub/pull/290
- ffmpeg or avlib?: avconv
- avlib version: 12.3
- macOS: 10.13.4

**Comment by jiaaro** [comment]
It looks like you installed avlib without the ogg codec, there are flags you can specify when you install (I assume you used homebrew?) to include those extra codecs

**Comment by skar404** [comment]
@jiaaro sorry, my issues duplicate is https://github.com/jiaaro/pydub/issues/269
