### ISSUE TITLE
JSONDecodeError after calling  AudioSegment.from_mp3

### ISSUE THREAD

**Issue by zhenlei** [jiaaro/pydub#303]
### Steps to reproduce
call function  AudioSegment.from_mp3("/tmp/musics/2.mp3")

### Expected behavior
no exception

### Actual behavior
<ipython-input-71-c4f6540e69e9> in <module>()
----> 1 AudioSegment.from_mp3("/tmp/musics/2.mp3")

/usr/local/lib/python3.5/dist-packages/pydub-0.22.1-py3.5.egg/pydub/audio_segment.py in from_mp3(cls, file, parameters)
    705     @classmethod
    706     def from_mp3(cls, file, parameters=None):
--> 707         return cls.from_file(file, 'mp3', parameters)
    708 
    709     @classmethod

/usr/local/lib/python3.5/dist-packages/pydub-0.22.1-py3.5.egg/pydub/audio_segment.py in from_file(cls, file, format, codec, parameters, **kwargs)
    658             stdin_data = file.read()
    659 
--> 660         info = mediainfo_json(orig_file)
    661         if info:JSONDecodeError
    662             audio_streams = [x for x in info['streams']

/usr/local/lib/python3.5/dist-packages/pydub-0.22.1-py3.5.egg/pydub/utils.py in mediainfo_json(filepath)
    266     stderr = stderr.decode("utf-8", 'ignore')
    267 
--> 268     info = json.loads(output)
    269 
    270     if not info:

/usr/lib/python3.5/json/__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    317             parse_int is None and parse_float is None and
    318             parse_constant is None and object_pairs_hook is None and not kw):
--> 319         return _default_decoder.decode(s)
    320     if cls is None:
    321         cls = JSONDecoder

/usr/lib/python3.5/json/decoder.py in decode(self, s, _w)
    337 
    338         """
--> 339         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    340         end = _w(s, end).end()
    341         if end != len(s):

/usr/lib/python3.5/json/decoder.py in raw_decode(self, s, idx)
    353         """
    354         try:
--> 355             obj, end = self.scan_once(s, idx)
    356         except StopIteration as err:
    357             raise JSONDecodeError("Expecting value", s, err.value) from None

JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 2 (char 3)

### Your System configuration
- Python version: 3.5
- Pydub version: 0.22.1
- ffmpeg or avlib?: ffmpeg
- ffmpeg/avlib version: git-2018-02-27-40102a2

### Is there an audio file you can include to help us reproduce?
[2.zip](https://github.com/jiaaro/pydub/files/2231478/2.zip)

**Comment by zhenlei** [comment]
This is caused by ffmpeg

**Comment by jiaaro** [comment]
@zhenlei were you able to get things working?

**Comment by derek-saal** [comment]
What did you do to fix this? I have the same issue -_-

**Comment by yannboun** [comment]
ditto

**Comment by zhenlei** [comment]
@jiaaro  I have fixed it by reinstalling a official ffmpeg.  the root cause is that my ffmpeg output has been customized, doesn't match pydub filter's rule.

**Comment by lloxis** [comment]
I'm having this issue and nothing is fixing it ! pls help

**Comment by kylefoley76** [comment]
I'm having the same problem.  Would you like me to upload the MP3 I'm using?

**Comment by jiaaro** [comment]
Dear google searchers: 
In a nutshell, pydub asks ffmpeg for info about the audio in json format, but some ffmpeg/avconv builds do not return valid json (or return other non-json).

If you want to help us make pydub more reliable, please:

1. post whether you're using ffprobe or avprobe (check by calling `pydub.utils.get_prober_name()`)
2. Try running the probe command at the command line and post the output:
    - for ffprobe: `cat /path/to/your.mp3 | ffprobe -of json -v info -show_format -show_streams -read_ahead_limit "-1" cache:pipe:0 2>/dev/null`
    - for avprobe: `cat /path/to/your.mp3 | avprobe -of json -v info -show_format -show_streams - 2>/dev/null`

**Comment by lauremoro** [comment]
Hi, I am using ffprobe. I ran the probe command as advised in your post and did not get any output at the command line.
