### ISSUE TITLE
FileNotFoundError: [WinError 2]

### ISSUE THREAD

**Issue by djmanbr** [jiaaro/pydub#307]
**Code:**
`from pydub import AudioSegment`
`audiofile = AudioSegment.from_ogg("C:/my/folder/file.ogg")`

**Error**
I'm getting WinError 2 (The system cannot find the specified file)
When I use:
`audiofile = AudioSegment.from_wav("C:/my/folder/file.wav")`
I'm not getting any error, why?

- Python version: 3.7.0
- Pydub version: I have downloaded it right now
- ffmpeg or avlib?: ffmpeg
- ffmpeg/avlib version: i'm not sure, i have downloaded it today

**Comment by jiaaro** [comment]
This is covered in other questions but for posterity: This is almost always due to pydub not being able to find ffmpeg/avconv or one of the other binaries provided by the ffmpeg/avconv package
