### ISSUE TITLE
Could you include steps to uninstall?

### ISSUE THREAD

**Issue by Jun711** [jiaaro/pydub#311]
Expect to see steps to cleanly uninstall pydub + dependencies in the document? 

when I installed the dependencies, it seems to take quite a while. Could you include steps to uninstall in the document as well, thanks?

**Comment by jiaaro** [comment]
Pydub is a pure python package with no python dependencies. So it'd just be `pip uninstall pydub`

If you have ffmpeg, avlib, or scipy installed, pydub will use those packages. Users are responsible for installing or uninstalling those optional dependencies manually.

**Comment by Jun711** [comment]
Thanks for replying.
Yea, I was concerned about optional dependencies ```brew install ffmpeg --with-libvorbis --with-sdl2 --with-theora```
This seems to install quite a lot of dependencies. Without installing these, I couldn't get it run with this error: 
```FileNotFoundError: [Errno 2] No such file or directory: 'ffprobe': 'ffprobe'``` 
After installing these optional dependencies, I was able to use pydub. 

So, to uninstall, should I just do ```brew uninstall ffmpeg --with-libvorbis --with-sdl2 --with-theora```? as I am trying on my local machine for now.

**Comment by jiaaro** [comment]
for macs `brew uninstall ffmpeg` should be sufficient. You may also want to`brew uninstall cleanup` though I don't think it's necessary

**Comment by Jun711** [comment]
I will do it using `brew uninstall ffmpeg` if i need to uninstall. thanks.
