### ISSUE TITLE
get_array_of_samples method returns signed data type

### ISSUE THREAD

**Issue by shinaji** [jiaaro/pydub#312]
### Steps to reproduce
import numpy as np
audio = AudioSegment.from_file("example.wav", "wav")
arr = nbp.array(audio.get_array_of_samples())
print(arr.dtype)

### Expected behavior
The data type of the array is uint8.

### Actual behavior
The data type of the array is int8.

**Comment by jiaaro** [comment]
for 8 bit audio, I think uint8 is correct - I _think_ that is just an accident of history (as discussed here, they blame bill gates but who knows https://www.dsprelated.com/showthread/comp.dsp/71057-1.php )

**Comment by shinaji** [comment]
Thank you for the reply.
As you mentioned uint8 is correct, but the returned type was "signed"  int8.

**Comment by jiaaro** [comment]
ah, I misunderstood - thank you for the PR
