### ISSUE TITLE
FileNotFoundError: [Errno 2] I have ffmpeg installed.

### ISSUE THREAD

**Issue by guattari92** [jiaaro/pydub#344]
While trying to play a wav file with pydub and my github repository, I ran into an error message like this. I thought it was the online link was the problem so tried running the code with a local wav. file but got the same error message. I have ffmpeg installed. Is there anything I should be doing to fix this problem?

**Error Message**
```
Traceback (most recent call last):
  File "./audiopython_prelim_3.py", line 17, in <module>
    song_b1 = AudioSegment.from_wav("guattari92.github.io/pokemongym.wav")
  File "/Users/cy/Library/Python/3.7/lib/python/site-packages/pydub/audio_segment.py", line 728, in from_wav
    return cls.from_file(file, 'wav', parameters)
  File "/Users/cy/Library/Python/3.7/lib/python/site-packages/pydub/audio_segment.py", line 610, in from_file
    file = _fd_or_path_or_tempfile(file, 'rb', tempfile=False)
  File "/Users/cy/Library/Python/3.7/lib/python/site-packages/pydub/utils.py", line 57, in _fd_or_path_or_tempfile
    fd = open(fd, mode=mode)
**FileNotFoundError: [Errno 2] No such file or directory: 'guattari92.github.io/pokemongym.wav'**
```

### Your System configuration
- Python version: 3.7
- Pydub version: 0.23.0
- ffmpeg or avlib?: usr/local/Cellar
- ffmpeg/avlib version: 4.1

**Comment by Axel-Erfurt** [comment]
maybe a wrong path ("guattari92.github.io/pokemongym.wav") ?

**Comment by guattari92** [comment]
Hmm, the path pulls the wav file fine on the web-browser. Is there another way to designate a path?

**Comment by Axel-Erfurt** [comment]
this works (for me)

`from urllib.request import urlopen
from pydub import AudioSegment
from pydub.playback import play


wav_file = urlopen("https://guattari92.github.io/pokemongym.wav")
with open('/tmp/test.wav','wb') as output:
  output.write(wav_file.read())

song = AudioSegment.from_mp3("/tmp/test.wav")
play(song)`

**Comment by guattari92** [comment]
It worked! Thanks :D
