### ISSUE TITLE
Direct way to get a numpy array from a mp3?

### ISSUE THREAD

**Issue by josephernest** [jiaaro/pydub#346]
Doesn't this (working) code:

    np.array(pydub.AudioSegment.from_mp3('test.mp3').get_array_of_samples())

waste some ressource by first converting to an `array.array` and then converting to a numpy array?

Questions:

1) Is there a direct way to get a numpy array from a MP3?

2) Is there a simple way to have a normalized numpy array (i.e. all values in [-1,1])?

Thanks in advance!

**Comment by jooshua-inglis** [comment]
np.fromstring(pydub.AudioSegment.from_mp3('test.mp3').

Not quite sure what you mean by normalized numpy array, are you trying to scale down the arrray. If so you can just say arr/math.abs(arr.max()).

**Comment by josephernest** [comment]
@jooshua-inglis it doesn't seem to work:

    import numpy as np
    import pydub
    a = np.fromstring(pydub.AudioSegment.from_mp3('test.mp3'))

> TypeError: argument 1 must be string or read-only buffer, not AudioSegment

**Comment by McCrearyD** [comment]
Yeah I would love a solution for this.

Currently trying to run it through a TensorFlow model & in order to convert the sound to mfcc, it's required that the audio be stored in a NumPy array.

    class DataContainer:
        def __init__(self):
            self.X = []
            self.Y = []

        def append_data(self, chord_name, quality, path):
            input_format = path.split('.')[-1]
            sound = AudioSegment.from_file(path, format=input_format)
            sound = np.fromstring(sound)  # this doesn't work
            mfcc = lf.mfcc(sound)

            self.X.append(mfcc)
            self.Y.append(chord_name, quality)

Gives this error: `TypeError: a bytes-like object is required, not 'AudioSegment'`

**Comment by McCrearyD** [comment]
Actually fixed it right afterwards...

I used the AudioSegment method `get_array_of_samples` in order to return the array.
I then converted it into NumPy using the regular `np.array` method.

End code:

    class DataContainer:
        def __init__(self):
            self.X = []
            self.Y = []

        def append_data(self, chord_name, quality, path):
            input_format = path.split('.')[-1]
            sound = AudioSegment.from_file(path, format=input_format)
            sound = np.array(sound.get_array_of_samples())
            mfcc = lf.mfcc(sound)

            self.X.append(mfcc)
            self.Y.append(chord_name, quality)

**Comment by dieguitoo080** [comment]
from pydub import AudioSegment
from pydub.generators import Sine

def create_beep(duration_ms=500, freq=440):
    return Sine(freq).to_audio_segment(duration=duration_ms)

linterna_apagandose = create_beep(300, 300)
grito_hojas = create_beep(700, 600)
golpe_espada = create_beep(400, 200)
teclas_susurro_hoja = create_beep(800, 500)
voces_luces = create_beep(600, 700)
paginas_voz_luz = create_beep(900, 400)

linterna_apagandose.export("linterna_apagandose.mp3", format="mp3")
grito_hojas.export("grito_hojas.mp3", format="mp3")
golpe_espada.export("golpe_espada.mp3", format="mp3")
teclas_susurro_hoja.export("teclas_susurro_hoja.mp3", format="mp3")
voces_luces.export("voces_luces.mp3", format="mp3")
paginas_voz_luz.export("paginas_voz_luz.mp3", format="mp3")
