### ISSUE TITLE
("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)

### ISSUE THREAD

**Issue by mrazimi** [jiaaro/pydub#372]
C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\pydub\utils.py:165: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)

**Comment by jiaaro** [comment]
This runtime warning is intended to help users discover that pydub was not able to find ffmpeg. The easiest way to resolve it is to make sure you have ffmpeg installed and it's discoverable in your PATH
