### ISSUE TITLE
AttributeError: 'WindowsPath' object has no attribute 'read'

### ISSUE THREAD

**Issue by Zebrafish007** [jiaaro/pydub#374]
This "AttributeError: 'WindowsPath' object has no attribute 'read'" from https://github.com/jiaaro/pydub/issues/273 is back!

Pydub: 0.23.1
3.5.6 |Anaconda custom (64-bit)| (default, Aug 26 2018, 16:05:27) [MSC v.1900 64 bit (AMD64)]
ffmpeg-1.4
pathlib: 1.0.1-py35_0

Script:

from pydub import silence, AudioSegment
from pathlib import Path
import os, sys

print (sys.version)

AudioSegment.converter = r"C:\\Program Files\\net.downloadhelper.coapp\\converter\\build\\win\\64\\ffmpeg.exe"
AudioSegment.ffprobe   = r"C:\\Program Files\\net.downloadhelper.coapp\\converter\\build\\win\\64\\ffprobe.exe"

my_file = Path("C:\\x\\audio.mp3")    
audio = AudioSegment.from_mp3(my_file)

**Comment by Zebrafish007** [comment]
To be specific:
Traceback:
 File "c:\y\lib\site-packages\pydub\audio_segment.py", line 665, in from_file
    stdin_data = file.read()
AttributeError: 'WindowsPath' object has no attribute 'read'

**Comment by Zebrafish007** [comment]
The python build-in file.read() is 2.7 and no longer exist in 3.5. Although in komodo edit 11.1 still highlighted as a reserved build-in word it might explain a few things.

**Comment by jiaaro** [comment]
I suspect this is because pydub tries to detect whether it'd been given a file-like object, or a string file path, and it's assuming a Path object is a file-like object (and trying to read it)

**Comment by Zebrafish007** [comment]
Update: installed pydub 0.23.1 and keep getting the error:
    `FileNotFoundError: [WinError 2] The system cannot find the file specified`

Boiled down to the pydub util.py file:

     command = [prober, '-of', 'json'] + command_args
     print ('command : %s' % command)  # added to show output
     res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)

print result:

     command : ['ffprobe', '-of', 'json', '-v', 'info', '-show_format', '-show_streams', 'C:\\music\\mozart.mp3']

Complete traceback:

Traceback (most recent call last):
  File "z:\AA\lol6.py", line 20, in <module>
    audio = AudioSegment.from_mp3(my_file)
  File "x:\y\anac\lib\site-packages\pydub\audio_segment.py", line 717, in from_mp3
    return cls.from_file(file, 'mp3', parameters=parameters)
  File "x:\y\anac\lib\site-packages\pydub\audio_segment.py", line 665, in from_file
    info = mediainfo_json(orig_file)
  File "x:\y\anac\lib\site-packages\pydub\utils.py", line 264, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
  File "x:\y\anac\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "x:\y\anac\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

lol6.py:

     from pydub import silence, AudioSegment
     from pathlib import Path
     import os, sys, pydub

     AudioSegment.converter = r"C:\Program Files\net.downloadhelper.coapp\converter\build\win\64\ffmpeg.exe"
     AudioSegment.ffprobe   = r"C:\Program Files\net.downloadhelper.coapp\converter\build\win\64\ffprobe.exe"

     print (sys.version)
     print('ffmpeg : ', AudioSegment.ffmpeg)
     print('ffmpeg : ', AudioSegment.ffprobe)

     print(os.getcwd()+"\\ffmpeg\\bin\\ffmpeg.exe")

     my_file = Path('C:\\music\\mozart.mp3')

     print(my_file) 

     audio = AudioSegment.from_mp3(my_file)

**Comment by Zebrafish007** [comment]
After digging deep in audio_segment> utils > subprocess (conda) I couldn't still figure it out why it kept bumping.  However, 

mypaths = os.getenv('PATH').split(';')

     for i in mypaths:
         if i.find('python'):
             print(i)

showed me that the changed windows environment variables were not updated for python in the editor. PC rebooted and the newly installed FFmpeg and its folder in PATH showed up under `C:\Python\FFmpeg\`. Ran script and had succes. Problem solved.
