### ISSUE TITLE
Does pydub support treads to speed up ？

### ISSUE THREAD

**Issue by jackielyc** [jiaaro/pydub#378]
the issue is the same as the topic。

**Comment by derek-adair** [comment]
This is (likely) outside of the scope of pydub.

[Here](https://docs.python.org/2/library/threading.html) is a link to the docs on threads in python.

[Here](https://realpython.com/intro-to-python-threading/) is a very thorough and up-to-date tutorial on how you can use this api.

**Comment by derek-adair** [comment]
[Celery](http://docs.celeryproject.org/en/latest/getting-started/introduction.html) is also probably necessary.

**Comment by jiaaro** [comment]
Pydub should be mostly thread safe, but it's up to the user to implement threading. Pydub itself operates in a single thread
