### ISSUE TITLE
Concatenated audio becomes progressively louder.

### ISSUE THREAD

**Issue by insignedesign** [jiaaro/pydub#383]
### Steps to reproduce
I am getting audio (mp3) from google's cloud text to speech neural service. I pass a string at a time to the service, then concatenate the output to form a podcast/audiobook.

### Expected behavior
The appended audio should be the same level.

### Actual behavior
The audio becomes progressively louder.

### Your System configuration
- Python version: 2.7.15
- Pydub version: .23.1
- ffmpeg or avlib?: ffmpeg
- ffmpeg/avlib version: 4.1.3

### Is there an audio file you can include to help us reproduce?

https://soundcloud.com/jeremy-dooley-246671747/chapter-1-hard-fork

**Comment by jiaaro** [comment]
can you share a code snippet to reproduce this?

**Comment by insignedesign** [comment]
Yes, apologies for my code, I am a typeface designer, not a programmer :)

def addblank(trans, blank, full):
        #glob.glob works on current dir only
#grab everything in this dir, iterate through it
        blankas = AudioSegment.from_file(blank, frame_rate=44100, sample_width=2)
        tranas = AudioSegment.from_file(trans, frame_rate=44100, sample_width=2)
        fullas = AudioSegment.from_file(full, frame_rate=44100, sample_width=2)
        #we add these two files together, and the curfile is upsampled to the right rate
        combined = fullas + blankas + tranas 
        #shutil.move(working_dir+fl_name, output_dir+fl_name)
        combined.export(full, format="mp3", bitrate="352k")

**Comment by insignedesign** [comment]
Hello, any new information on this issue?

**Comment by jiaaro** [comment]
I assume you're calling this many times which is causing your audio to be decoded and re-encoded to mp3 over and over. Can you try using WAVE for all the operations and encoding to mp3 just once at the end of the process? I suspect the mp3 codec is changing the loudness slightly on each decode-encode cycle.

**Comment by insignedesign** [comment]
Hi @jiaaro, it appears that using lossless .wav fixed the issue. Thank you for your help.
