### ISSUE TITLE
volume decrease somewhere in the middle

### ISSUE THREAD

**Issue by arianaa30** [jiaaro/pydub#390]
I just discovered this library which makes life way easy! Thanks. Couple of questions:

1- How can I decrease the audio volume somewhere in the middle of the file? Say in a 10s audio, I want 5 to 6 seconds to have lower volume, possibly with fade-in and fade-outs. 
I can cut the video in 3 portions, decrease the volume of middle portion, and append all later. But not sure if that will be very smooth with no artifacts.

2- How about blending two audio? After 1, I would like to add my voice to the middle part while still having the background music.

3- Btw can I do the same things with video as well, or its only for audio? Like, adding audio to videos, cropping videos, video fade-in and fade-out, etc.

**Comment by jiaaro** [comment]
1 & 2. Those topics are covered in the [README](https://github.com/jiaaro/pydub/blob/master/README.markdown) and there are examples in [API.markdown](https://github.com/jiaaro/pydub/blob/master/API.markdown) as well.

3. pydub only supports audio right now, but you can use it on the audio channels in videos you are editing using other libraries if you like

**Comment by zamirkhan** [comment]
Apologies for responding to a closed issue, but it's still not clear to me, after reading the README and playing around with some of the fade options, how to properly achieve #1. That is, fading a piece of audio just in the middle. 

Say I have 10 seconds of music, I want the first and last 2 seconds to be at normal/default volume (let's call this `normalDb`). From 2 to 3 seconds, I want to fade out to a lower volume (`fadedDb`) and stay that way until 7 to 8 seconds, where I want to fade back up (to `normalDb`).

I have tried to achieve this by combining two fade commands, in sequence, on the same audio. However, while it works for the beginning (the fade out portion), the fade-back-in at the end is not achieving what I want. The last portion (e.g. the last 2 seconds) has static in it, almost like it has been over-processed. I wonder if it is because both fade operations are affecting the latter portion of the audio. What's the recommended way to do this?

**Comment by jiaaro** [comment]
@zamirkhan you should split the audio in to two parts. The first part which is 7 sec where you fade down, the. The last three which has a one second fade in, then re-combine the two parts

**Comment by youssefavx** [comment]
Hey guys I've got a similar problem here but I guess it's slightly nuanced / different. 

I have a list of volume levels that I want to basically smoothly / gradually increase and decrease the volume over for 300 ms chunks of audio, and perhaps even have a parameter where I can control how 'smooth' the transitions are. 

I have a list like so:
``python
volumes = [0.3, 0.9, 0.1, 0.4, 0.2]
```

And for every 300 ms chunk, I want to set its volume to that. However, when that is done for 300 ms, the transitions are way too abrupt. If I add a fade in and fade out, it's a bit better but it still sounds abrupt, and for 300 ms, a 200 ms fade in eats too much of the audio up. 

So for this reason I'd like to have a smoother fade over time over these values. Meaning, at the first 300 ms, it gradually goes up from 0.3 to 0.9, and at 600 ms it gradually does down to 0.1. 

Now, if there is some parameter to control smoothness that would be even better, because then I could decide "Ah actually it needs to be set so it goes from: 0.3 to 0.9 and then goes down to 0.2 over time by the end (the general trend of the array)"


Here is my code so far:

```python
from pydub import AudioSegment
from pydub.effects import ratio_to_db
slicing_points = [0, 1000, 2000, 3000]
volumes = [0.3, 0.9, 0.1, 0.4, 0.2]
audrey = AudioSegment.from_file('sonicsimilarity/audrey.wav')
#audrey = audrey.overlay(audrey, position=1000)
#audrey = audrey[slicing_points[0]:slicing_points[-1]]


silent_audio = AudioSegment.silent(duration=0)


first = True
for slicing_point, volume in zip(slicing_points, volumes):
    #print(volume)
    if first:
        previous_slicing = slicing_point
        first = False
    else:
        current_slicing = slicing_point
        print('Segment:', previous_slicing, '->', current_slicing)
        print('Volume:', volume)
        audrey_segment = audrey[previous_slicing:current_slicing]
        audrey_segment = audrey_segment.fade_in(200).fade_out(200)
        audrey_segment = audrey_segment.apply_gain(ratio_to_db(volume))
        silent_audio += (audrey_segment)
        previous_audrey_segment = audrey_segment
        previous_slicing = slicing_point
    #audrey = audrey[0:1000] + (audrey[1000:2000] - 100) + audrey[2000:]
print(len(audrey))
silent_audio.export('audrey2.wav', format='wav')
```

Is there anyway to do these smooth transitions?

**Comment by youssefavx** [comment]
The trouble with my current code, is if, say, I change the volumes to be:

```python
volumes = [0.8, 0.9, 0.8]
```

Even though they're all at the same level, you'll hear that the audio oscillates because of the fade ins and fade outs. So it's not exactly smoothing over the entire array to fade in and fade out every time.

**Comment by youssefavx** [comment]
Okay I wrote a function to do a gradual fade between volumes in an array. The trouble though is that's very slow. Profiling code, it seems 80 seconds are spend with the audiosegment append function. Here is my code:


```
def create_number_gradient(first_number, second_number, resolution=340):

    if second_number == first_number:
        return [first_number] * resolution
    resolution = (second_number - first_number) / resolution
    #print('resolution', resolution)
    gradient = []
    for i in np.arange(first_number, second_number, resolution):
        gradient.append(i)
    return gradient

def modulate_volume_with_volume_list(filepath, slicing_points, volumes):


    sound = AudioSegment.from_file(filepath)

    silent_audio = AudioSegment.silent(duration=0)
    first = True
    for index, slicing_point in enumerate(slicing_points):
        #print(volume)
        if first:
            previous_slicing = slicing_point
            first = False
            second = True
        if second:
            #Don't fade from volume to volume, just use previous volume
            current_slicing = slicing_point


            previous_volume = volumes[index-1]


            volume_gradient = create_number_gradient(previous_volume, previous_volume, resolution=current_slicing-previous_slicing)
            sound_300ms_chunk = sound[previous_slicing:current_slicing]
            for i in range(current_slicing-previous_slicing):
                sound_segment = sound_300ms_chunk[i:i+1]
                sound_segment = sound_segment.apply_gain(ratio_to_db(volume_gradient[i]))
                silent_audio += sound_segment



            previous_slicing = slicing_point
            second = False

        else:
            current_slicing = slicing_point


            try:
                current_volume = volumes[index]
                previous_volume = volumes[index-1]
            except IndexError:
              try:
                current_volume = volumes[index-1]
                previous_volume = volumes[index-1]
              except:

                current_volume = volumes[-1]
                previous_volume = current_volume

            volume_gradient = create_number_gradient(previous_volume, current_volume, resolution=round(current_slicing-previous_slicing))
            sound_300ms_chunk = sound[previous_slicing:current_slicing]
            for i in range(round(current_slicing-previous_slicing)):
                sound_segment = sound_300ms_chunk[i:i+1]

                sound_segment = sound_segment.apply_gain(ratio_to_db(volume_gradient[i]))
                silent_audio += sound_segment



            previous_slicing = slicing_point

        
    no_longer_silent = silent_audio
    return no_longer_silent
```


```
Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000  102.383  102.383 {built-in method builtins.exec}
        1    0.006    0.006  102.383  102.383 <string>:2(<module>)
        1    7.978    7.978  102.252  102.252 <ipython-input-30-ffbcd1c855a5>:53(modulate_volume_with_volume_list)
    83545    0.082    0.000   89.676    0.001 audio_segment.py:362(__add__)
    83545   87.510    0.001   89.585    0.001 audio_segment.py:1250(append)
   250888    0.797    0.000    2.546    0.000 audio_segment.py:402(_spawn)
    83793    0.417    0.000    2.180    0.000 audio_segment.py:300(__getitem__)
   250892    1.065    0.000    1.527    0.000 audio_segment.py:179(__init__)
        2    0.036    0.018    1.301    0.650 audio_segment.py:644(from_file)
        2    0.000    0.000    1.046    0.523 subprocess.py:920(communicate)
        2    0.045    0.022    1.046    0.523 subprocess.py:1662(_communicate)
    83546    0.308    0.000    0.925    0.000 audio_segment.py:434(_sync)
    83545    0.142    0.000    0.919    0.000 audio_segment.py:1170(apply_gain)
    10085    0.035    0.000    0.897    0.000 selectors.py:402(select)
    10085    0.854    0.000    0.854    0.000 {method 'poll' of 'select.poll' 
```

Would love any tips on how to make this more efficient. Here I'm taking a 340 ms chunk, and then pretty much for every ms, changing the volume gradually, then appending that ms on the last ms, and so on.
