### ISSUE TITLE
Is there a delay feature?

### ISSUE THREAD

**Issue by Cr3atable** [jiaaro/pydub#394]
I feel a bit bad about asking this in an issue out of all things but I've not noticed the ability to add blank audio in between concatenated clips of audio. I could obviously use a blank mp3 file with the exact duration for the amount of time I need, but it needs to be specific for each piece of audio I am making into one file. Is this a feature, or can I expect this to be a feature in the future?

**Comment by jiaaro** [comment]
There is slicing and `AudioSegment.silent()` so you could do something like:

```python
from pydub import AudioSegment

my_sound = AudioSegment.from_file(...)

# add 1.5 sec silence at the 5 seconds mark
part1 = my_sound[:5000]
part2 = my_sound[5000:]
delay = AudioSegment.silent(duration=1500)

sound_with_delay = part1 + delay + part2
```

**Comment by Cr3atable** [comment]
This works really well. Thank you!
