### ISSUE TITLE
In the pydub object property raw_data we get the RIFF headerless bytes, how do I get the bytes along with the RIFF headers.

### ISSUE THREAD

**Issue by yasersakkaf** [jiaaro/pydub#402]
When read a .wav using tensorflow as shown below:

> audio = tensorflow.read_file(wavefile_path)
print(audio.eval())

I get a byte which contains the RIFF headers in the first 44 characters.

These headers are missing when I convert the pydub object to bytes using the raw_data method as shown below, it gives me the output same as tensorflow's but without the RIFF headers (i.e. without the first 44 characters)

> from pydub import AudioSegment
> audio = AudioSegment.from_wav(wavefile_path)
> byte_audio = audio.raw_data
> print(byte_audio)

Can you modify the method so that we get the output same as that of the tensorflow.

### Your System configuration
- Python version: 3.6 
- Pydub version: 0.23.1
- ffmpeg or avlib?: ffmpeg
- ffmpeg/avlib version: 4.1.3

### Is there an audio file you can include to help us reproduce?
[Chunk5.zip](https://github.com/jiaaro/pydub/files/3338690/Chunk5.zip)

You can include the audio file in this issue - just put it in a zip file and drag/drop the zip file into the github issue.

**Comment by yasersakkaf** [comment]
One solution is to read the file using open in binary mode and then pass it directly to AudioSegment specifying the parameters as shown below.

> f = open(wavefile_path, 'rb')
> audio_bytes = f.read()

> audio = AudioSegment(audio_bytes, sample_width=2, frame_rate=16000, channels=1 )

Ater this if I do:

> print(audio.raw_data)

I get the RIFF headers as:

> b'RIFF\x84\xd1\x0f\x00WAVEfmt \x10\x00\x00\x00\x01\x00\x01\x00\x80>\x00\x00\x00}\x00\x00\x02\x00\x10\x00data'

**Comment by jordyjwilliams** [comment]
See here: this thread was useful for me with a similar issue:
https://github.com/jiaaro/pydub/issues/220
