### ISSUE TITLE
Why is the RMS always int?

### ISSUE THREAD

**Issue by bkanaki** [jiaaro/pydub#418]
Hi,

I am not sure if this is a right place to ask questions, but I was scrutinizing the source code that calculates RMS and I  found that you cast the RMS value to the `int` in your pyaudioop [here](https://github.com/jiaaro/pydub/blob/7f4d5e3bf84e95681eb1c99aa6a12bae6737c030/pydub/pyaudioop.py#L147).

May I please know why do you do that?

Thanks!

**Comment by jiaaro** [comment]
pyaudioop is a python (re-)implementation of the audioop module from the CPython stdlib (only used by pypy). 

It’s an int because audioop.c uses an int. 

Also, Pyaudioop was contributed to Pypy long ago and they’ve made lots of improvements since then so that code pretty much never runs :)

**Comment by bkanaki** [comment]
Thanks for your response. I almost didn't pay attention to the imports in utils.py.
