### ISSUE TITLE
pydub.exceptions.CouldntEncodeError during export

### ISSUE THREAD

**Issue by lrh000** [jiaaro/pydub#420]
### Steps to reproduce
from pydub import AudioSegment
mp3 = AudioSegment.from_mp3('test.mp3')
mp3[17*1000+500:].export('1.mp3', format="mp3")
### Expected behavior
cut audio

### Actual behavior
pydub.exceptions.CouldntEncodeError: Encoding failed. ffmpeg/avlib returned error code: 1

Command:['ffmpeg', '-y', '-f', 'wav', '-i', '/tmp/tmp23aprg5t', '-f', 'mp3', '/tmp/tmpmdc4qs7p']

Output from ffmpeg/avlib:

b"ffmpeg version 4.1.3 Copyright (c) 2000-2019 the FFmpeg developers\n  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 20160609\n  configuration: --enable-version3 --enable-postproc --enable-libvorbis --enable-libvpx\n  libavutil      56. 22.100 / 56. 22.100\n  libavcodec     58. 35.100 / 58. 35.100\n  libavformat    58. 20.100 / 58. 20.100\n  libavdevice    58.  5.100 / 58.  5.100\n  libavfilter     7. 40.101 /  7. 40.101\n  libswscale      5.  3.100 /  5.  3.100\n  libswresample   3.  3.100 /  3.  3.100\nGuessed Channel Layout for Input Stream #0.0 : mono\nInput #0, wav, from '/tmp/tmp23aprg5t':\n  Duration: 00:03:35.30, bitrate: 705 kb/s\n    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, mono, s16, 705 kb/s\nAutomatic encoder selection failed for output stream #0:0. Default encoder for format mp3 (codec mp3) is probably disabled. Please choose an encoder manually.\nError selecting an encoder for stream 0:0\n"

### Your System configuration
- Python version: 3.5.2
- Pydub version: 0.23.1
- ffmpeg or avlib?: ffmpeg
- ffmpeg/avlib version: 4.1.3

### Is there an audio file you can include to help us reproduce?
You can include the audio file in this issue - just put it in a zip file and drag/drop the zip file into the github issue.

**Comment by lrh000** [comment]
I have solved the problem. Thx

**Comment by blaine12100** [comment]
Can you tell me what fixed this issue for you?

**Comment by lrh000** [comment]
> Can you tell me what fixed this issue for you?

apt-get install ffmpeg libavcodec-extra
