### ISSUE TITLE
what is the reference of the silence_thresh

### ISSUE THREAD

**Issue by ArtemisZGL** [jiaaro/pydub#426]
sorry i am not familiar with db and dbfs. but i see that when calculate db, i should have a reference value, and i want to konw what is the reference value of the silence_thresh in detect silence, is the max value in the audio or just the constant one or anything else?

**Comment by jiaaro** [comment]
dBFS uses the maximum amplitude that can be stored by the format as a reference, so all dBFS values are negative numbers

**Comment by ArtemisZGL** [comment]
thanks a lot ! @jiaaro
