### ISSUE TITLE
Next playback on pydub.

### ISSUE THREAD

**Issue by ahmadraniri** [jiaaro/pydub#427]
I like pydub so much, cause it can plays my m4a files (not like pygame or pyglet), and I discovery a way to play multiple files ..., then I feel curious about  how to use "next play" feature for pydub, you know it's like when you play some audio files until you listen to a song you hate and want to skip it.
I am sorry for a "stupid question" and thanks for the attention.

**Comment by ahmadraniri** [comment]
solved thanks.

**Comment by nium9** [comment]
How did you solve it?
