### ISSUE TITLE
Howe hide the displayed information when playing a file ?

### ISSUE THREAD

**Issue by patsuckow** [jiaaro/pydub#428]
Is there an option to hide the displayed information when playing a file?

![Снимок экрана от 2019-10-24 19-02-59](https://user-images.githubusercontent.com/12321741/67503821-f6ed9680-f690-11e9-8562-453507a53bd4.png)

**Comment by ahmadraniri** [comment]
can i see your code?

**Comment by jiaaro** [comment]
Have you tried `contextlib.redirect_stderr()` ?

**Comment by patsuckow** [comment]
Yes, I tried it, this also does not work for pydub :(

**Comment by patsuckow** [comment]
I solved this problem as follows:

```python
play(generators.Sine(440).to_audio_segment(duration=1500))
back_up = '\x1b[A\x1b[A\x1b[A\x1b[A\x1b[A'
print(back_up + 700*' ' + back_up + 700*'\b')
```
That is, the displayed 4 lines are first replaced with spaces and after that we return to the very beginning using `\b`

**Comment by eliranwong** [comment]
I find none of the answers mentioned above work.

I finally managed to hide the pydub playback output by using a subprocess.

If you are interested, I implemented at:

https://github.com/eliranwong/UniqueBible/blob/main/util/RemoteCliMainWindow.py#L287
