### ISSUE TITLE
Songs should be saved with the same tag info they were opened with

### ISSUE THREAD

**Issue by BenjaminRH** [jiaaro/pydub#44]
Currently, by default a song imported with `AudioSegment.from_file` and then saved with `song.export(name)` is saved as the same format it was opened with. It would be very helpful if the tags could remain, too. So if the tags argument isn't provided for the `export` method, it would use whatever metadata was there originally.

I hope this makes sense.

**Comment by VitalySvyatyuk** [comment]
Unfortunately, @marcwebbie 's method doesn't work at Windows 10. I tried both Pythons: 2 and 3.
But it works perfect at Linux.
So, for Windows [mutagen](https://code.google.com/p/mutagen/) will be nice.

**Comment by wal1624** [comment]
This issue is not fully resolved as many, including me, keep coming across the same issue.
