### ISSUE TITLE
How can I get data from microphone?

### ISSUE THREAD

**Issue by costales** [jiaaro/pydub#443]
Hi,

I would like to read the microphone each 500 ms in a loop, then manipulate that slice of sound and play it.

I did not find any code for doing this. Is this possible?

Thanks in advance!!

**Comment by Mattwmaster58** [comment]
@jiaaro would have the final say here, but reading through the docs and such, it appears that data from the microphone is beyond the scope of this project. Try [this](https://stackoverflow.com/questions/1936828/how-get-sound-input-from-microphone-in-python-and-process-it-on-the-fly) answer from StackOverflow for a way to do this.

**Comment by jiaaro** [comment]
@Mattwmaster58 agreed
