### ISSUE TITLE
Issue opening a file.

### ISSUE THREAD

**Issue by QasimWani** [jiaaro/pydub#447]
### Steps to reproduce
from pydub import AudioSegment
song = AudioSegment.from_mp3("path/to/file.mp3")

### Expected behavior
No error upon executing the above code should be produced.

### Actual behavior
This is what actually ends up happening.
![image](https://user-images.githubusercontent.com/43754306/74094933-0c0ef980-4ab7-11ea-90b6-c74289a09920.png)
(note: I'm using Jupyter notebook)

### Your System configuration
- Python version: python 3.7.3
- Pydub version: 0.23.1
- ffmpeg or avlib?: **I don't have either of those**
- ffmpeg/avlib version: **I don't have either of those.**

**How may I be able to solve this issue. Should I install an extension of either ffmpeg / avlib?**

Thanks for help.

**Comment by GreyAlien502** [comment]
> Should I install an extension of either ffmpeg / avlib?

Yeah, you need to install one of those, and then it should work.

**Comment by QasimWani** [comment]
Thanks. will keep you updated in case there's still an issue!
