### ISSUE TITLE
Error: Instance of 'AudioSegment' has no 'low_pass_filter' member

### ISSUE THREAD

**Issue by BassThatHertz** [jiaaro/pydub#448]
### Steps to reproduce
```
from pydub import AudioSegment

song = AudioSegment.from_file("1.flac", "flac")
new = song.low_pass_filter(5000)

new.export("1.flac", format="flac")
```
### Expected behavior
Add a low pass filter to a song.

### Actual behavior
I get the following error in VSCode:
`Instance of 'AudioSegment' has no 'low_pass_filter' member`

### Your System configuration
- Python version: 3.7.3
- Pydub version: 0.23.1 I think? Here's what shows in Command Prompt when I do pip install pudub:
```
C:\Users\H\Desktop>pip install pydub
Requirement already satisfied: pydub in c:\users\h\appdata\local\programs\python\python37\lib\site-packages (0.23.1)
```
- ffmpeg or avlib?: FFmpeg 
- ffmpeg/avlib version: FFmpeg 4.2.2

### Is there an audio file you can include to help us reproduce?
You can include the audio file in this issue - just put it in a zip file and drag/drop the zip file into the github issue.

**Comment by hassan-c** [comment]
I have tested your code and it works OK for me. I notice that you mention:

> I get the following error in VSCode:

This most likely means that VSCode is not detecting members of the `AudioSegment` class. Make sure that you have the Python extension installed, and that it is working properly. You may sometimes need to restart VSCode to help it to detect imported libraries.

**Comment by hassan-c** [comment]
Since this is not an issue with ```pydub```, this issue can be closed.
