### ISSUE TITLE
Error with converting webm to flac

### ISSUE THREAD

**Issue by DevJhns** [jiaaro/pydub#449]
### Steps to reproduce
I'm using recordrtc js lib to record audio from webrtc audio stream,
on server side converting webm stream record to flac,
`.export(format='flac', parameters=["-ac", "1"])`
 on safari ipad i get this error

Stream #0:0 -> #0:0 (opus (native) -> pcm_s16le (native))
Error while opening decoder for input stream #0:0 : Invalid data found when processing input
 Metadata:
    major_brand     : mp42
    minor_version   : 1
    compatible_brands: isommp41mp42
    creation_time   : 2020-02-11T13:00:49.000000Z
  Duration: 00:00:01.05, start: 0.000091, bitrate: 36 kb/s
    Stream #0:0(und): Audio: opus (mp4a / 0x6134706D), 48000 Hz, mono, fltp, 27 kb/s (default)
    Metadata:
      creation_time   : 2020-02-11T13:00:49.000000Z
      handler_name    : Core Media Audio
[opus @ 0x558016b70140] Invalid extradata size: 2
Stream mapping:
  Stream #0:0 -> #0:0 (opus (native) -> pcm_s16le (native))
Error while opening decoder for input stream #0:0 : Invalid data found when processing input
[opus @ 0x558016b70140] Invalid extradata size: 2
Error while opening decoder for input stream #0:0 : Invalid data found when processing input

so problem with it records in mp42 and not webm I guess?
But ipad have mediarecorder api support, or I'm doing something wrong?

**Comment by GreyAlien502** [comment]
Can you give more information to help diagnose the issue?
You say: ``` .export(format='flac', parameters=["-ac", "1"])```,
but this sounds like an error importing, not exporting.
Does the error occurring only when you run ``.export(...)``? or does it still occur if you remove that?

**Comment by DevJhns** [comment]
@GreyAlien502 sure, thanks for help!
getting audio bytes with:
`AudioSegment.from_file(io.BytesIO(stream_part['audio']), codec="opus")`

error occurring only on ipad, other browsers/os works fine.
Didn't try removing .export() couse need it in flac format

**Comment by GreyAlien502** [comment]
Just for testing, can you save the ```stream_part['audio']``` to a file directly?
I understand that you want to convert to flac, but if we can look at the raw input that the iPad sends, we can see if it is giving you what you expected and fix what needs to be fixed accordingly.

**Comment by DevJhns** [comment]
@GreyAlien502, sure, you are right, thx for help,
a bit busy today, I'll be able to send example tommorow
