### ISSUE TITLE
Add LICENSE file to release tarball

### ISSUE THREAD

**Issue by opoznyak** [jiaaro/pydub#489]
### Steps to reproduce
1) Download release tarball from here -> https://pypi.org/project/pydub/#files
2) Unpack and check for any LICENSE file there
### Expected behavior
MIT LICENSE should be present there.

### Actual behavior
No LICENSE is there

### Your System configuration
- Python version: 3.8.2 
- Pydub version: 0.24.1
- ffmpeg or avlib?: ffmpeg
- ffmpeg/avlib version: 4.2.2

### Is there an audio file you can include to help us reproduce?
None

**Comment by kynan** [comment]
@jiaaro any chance this can be fixed? This is currently a blocker for conda packaging pydub.
