### ISSUE TITLE
Split audio with speech into time-segments

### ISSUE THREAD

**Issue by marlon-br** [jiaaro/pydub#495]
### Expected behavior
I want to split audio file by ~equal segments (for example each segment is about 10 seconds long). This audio file contains speech, so I don't want to cut words in the middle. This is why files could be not exactly 10 seconds long.

### Actual behavior
Now it is possible to split by separate words

### Is there an audio file you can include to help us reproduce?
Any file with human speech

**Comment by GreyAlien502** [comment]
Splitting on words will be difficult.
In rapid speech, words are often slurred together, and sometimes would take a speaker of the language to determine word boundaries. 

If there are short pauses between the words you want to split though, you could split on that using ```pydub.silence.detect_silence``` to tell you what zones are safe to split in.

**Comment by marlon-br** [comment]
thanks, finally I have splitted audio at single words with use of pydub.silence.detect_silence and concatenated single words in phrases with required lengths.
