### ISSUE TITLE
Changing AudioSegment volume as percentage

### ISSUE THREAD

**Issue by sundayz** [jiaaro/pydub#496]
### Expected behavior
There should be an easy way to change the volume of an AudioSegment, for example in terms of percentage, where you can set an AudioSegment to 50% volume to make it half its original volume.

### Actual behavior
The only way to change volume is relative DB adjustment

I have tried to implement my own function to do it, but it doesn't work as expected. Values like 0.9 (90%) are much too quiet. Here is my code:

```python
def set_volume(segment: AudioSegment, volume: float) -> AudioSegment:
	if volume == 1:
		return segment

	gain = clamp(ratio_to_db(volume, 1, True), -120, 0)

	# Apply the relative change. For example if dBFS is -10, relative change is -5, result will be -15
	return segment.apply_gain(segment.dBFS + gain)
```

This library is great and allows people like me with no audio engineering background to use ffmpeg easily, I feel like most people would expect something like `AudioSegment.set_volume(0.5)` to be available, considering how easy using the rest of the library is. Why is there no way to set the volume of the AudioSegment in terms of percentage, where 0 is silent, 1 is the original and 2 is twice as loud?

Maybe there's a reason for it, or maybe there is a way of doing it that I have missed. I tried using the `ratio_to_db` function but it didn't seem to do what I wanted it to do.

**Comment by GreyAlien502** [comment]
The relative DB adjustment already does what you ask.
```python
segment.apply_gain(ratio_to_db(volume))
```
does the following:
 
>set the volume of the AudioSegment in terms of percentage, where 0 is silent, 1 is the original and 2 is twice as loud

**Comment by sundayz** [comment]
Thanks a lot! Maybe this should be noted in the readme.

**Comment by afsara-ben** [comment]
noise.apply_gain(ratio_to_db(volume)) this did not work. The noise stays the same, volume does not decrease
