### ISSUE TITLE
detect_silence results confusing

### ISSUE THREAD

**Issue by hankp46** [jiaaro/pydub#510]
I'm trying to determine if a wav file contains any sound using this simple script;

`from pydub import AudioSegment,silence
sound = AudioSegment.from_file("testout.wav", format="wav")
silence = silence.detect_silence(sound, min_silence_len=1000, silence_thresh=-16)
silence = [((start/1000),(stop/1000)) for start,stop in silence] #convert to sec
print(silence)

If I input a file with sound result is:
(0.0, 9.172)]  Which I think means the file is completely silent
When I expected
[ ]

`

**Comment by hankp46** [comment]
Volume of wav file was too low. After increasing volume achieved desired results.

**Comment by jiaaro** [comment]
Thanks for following up, sorry I didn't get to it before you did!
