### ISSUE TITLE
Stop pydub audio (in a thread)

### ISSUE THREAD

**Issue by le-grand-mannitout** [jiaaro/pydub#514]
Hello !

Is there a way to stop a sound while it's playing ?

I'm using a thread, so I can't do something like :

```python
while 1:
   try:
        play(sond)
    except KeyboardInterrupt:
        break
```

Thank you in advance for your time !

**Comment by jiaaro** [comment]
if you'd like to play audio in a thread with play/pause/etc - I recommend you play the audio with [simpleaudio](https://simpleaudio.readthedocs.io/en/latest/) – you can use the code in pydub.playback as a template to get started:

```python
from pydub import AudioSegment
import simpleaudio

seg = AudioSegment.from_file(...)

playback = simpleaudio.play_buffer(
        seg.raw_data,
        num_channels=seg.channels,
        bytes_per_sample=seg.sample_width,
        sample_rate=seg.frame_rate
)

... after a while...
playback.stop()
```

**Comment by le-grand-mannitout** [comment]
It's working !

Thank you very much !
