### ISSUE TITLE
ffmpeg link in pydub.com is not working

### ISSUE THREAD

**Issue by stvreumi** [jiaaro/pydub#515]
### Steps to reproduce
- Go to http://pydub.com/ and click [anything else ffmpeg supports].

### Expected behavior
Should go to [this website](https://ffmpeg.org/general.html#Supported-File-Formats_002c-Codecs-or-Features).

### Actual behavior
But the link on the website will go to some phishing website.

**Comment by jiaaro** [comment]
Thanks! fixed :)
