### ISSUE TITLE
Pydub. "Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work".

### ISSUE THREAD

**Issue by TheKingDavidF** [jiaaro/pydub#541]
I have an error on python when using pydub: "Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work". But I already download ffmpeg, add path to user's and system's variables, uninstall and install ffmpeg and pydub by pip, but nothing can help. I don't know what I can do more. The problem the same I windows 7 and in windows server. Please help me.

**Comment by Devin-Wallace** [comment]
what was your solution?
