### ISSUE TITLE
 The system can not find the file specified

### ISSUE THREAD

**Issue by AphroMad** [jiaaro/pydub#542]
### Steps to reproduce
Hey ! So here is my code : 

```
from pydub import AudioSegment
sound1 = AudioSegment.from_mp3("sound_0.mp3")
sound2 = AudioSegment.from_mp3("sound_1.mp3")

sound = sound1 + sound2
sound.export("test.mp3",format="mp3")
```

### Expected behavior
Just supposed to work

### Actual behavior
I got the error message : WindowsError: [Error 2] The system can not find the file specified

### Your System configuration
- Python version: 3.8
- Pydub version: I just installed it
- ffmpeg or avlib?:  ffmpeg
- ffmpeg/avlib version: 2020-12-15-git-32586a42da-full_build-www.gyan.dev

### What did I try ? 
So, I found some things to do on a [Stackoverflow subject](https://stackoverflow.com/questions/22284461/pydub-windowserror-error-2-the-system-can-not-find-the-file-specified),
I tried to add this 
`pydub.AudioSegment.ffmpeg = "way//to//ffmpeg.exe"`
But it doesn't worked, then this 
`AudioSegment.converter = "way//to//ffmpeg.exe"`
Still doesn't work, so, because I'm on spyder with anaconda, I tried this on the anaconda prompt 
`conda install -c conda-forge ffmpeg`
I even tried to put ffmpeg.exe,ffplay.exe in the current working directory but still doesn't worked..

So I'm desperately here for some help, thanks in advance

**Comment by mohammadmomeni** [comment]
Same problem !

**Comment by AphroMad** [comment]
@mohammadmomeni 
I actually made it work, I found multiple solution over the net, here they are : 
add this line : `pydub.AudioSegment.ffmpeg = "way//to//ffmpeg.exe"`
OR
add this line : `AudioSegment.converter = "way//to//ffmpeg.exe"`
OR
because I'm using anaconda, this line on the anaconda prompt : `conda install -c conda-forge ffmpeg`
OR
last thing, put ffmpeg.exe,ffplay.exe in the current working directory
