### ISSUE TITLE
AudioSegment.overlay() slow when called many times

### ISSUE THREAD

**Issue by Bentroen** [jiaaro/pydub#550]
Hello!

I'm currently working on a tool that renders [Note Block Studio](https://github.com/HielkeMinecraft/OpenNoteBlockStudio) songs (`.nbs`) to audio files. This format is similar to MIDI in that it contains what notes should be played at a given moment, each one with a certain pitch, volume and panning.

Thanks to Pydub, I got this to work flawlessly in less than two days. However, the songs made in this program may easily reach 20,000+ notes, which means calling `AudioSegment.overlay()` thousands of times. Of course, this slows down everything.

A song with 20k notes takes about 2.5 hours to complete, while a black-MIDI-type song with 150k notes took nearly 14 hours. When removing the `overlay()` call, however, everything is done within seconds (even with all the pitch/gain/speed changes).

I know the aim of Pydub is not to be highly efficient, but intuitive. What I'd like to know is if there's any way around the `overlay()` method that still allows me to keep the other modifications done with Pydub. More specifically:

- When inspecting the source code, I noticed this method is implemented in pure Python. Could it be made more efficient by doing lower-level calls, such as calling `ffmpeg` to overlay the audio? (I'd be happy to give this a go if it turns out to be possible.)
- Should I use `AudioSegment.get_array_of_samples()` on each sound and use something else to overlay them? Or...
- Is what I'm trying to accomplish too advanced for Pydub, and I should use a lower-level package instead (e.g. pysox)?

Thanks!

**Comment by jiaaro** [comment]
the core functionality of overlay is already implemented in native code (assuming you're using cpython) the main performance issue is usually garbage collection. I've written a module that avoids many many calls to overlay for cases like this that you might find useful (feel free to fork it :) )

https://gist.github.com/jiaaro/b610728a642bbaa28b3f1e5d3b6f9cf7

**Comment by Bentroen** [comment]
Perfect! It seems much more intuitive to collect all the segments and then combine them in one go. The operation that took 2.5 hours before was now done in 9 minutes! 😄

Have you considered adding this module to the source? I believe it's useful enough that it should be in there :)

---

Just for the record, I've encountered two different issues that I managed to solve as follows:

```
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    handle = nbs_to_audio.render_audio(song, output)
  File "C:\Users\Bentroen\Desktop\Projects\NBS Bot\NBS-Bot\nbs_to_audio.py", line 195, in render_audio
    track = mixer.to_audio_segment()
  File "C:\Users\Bentroen\Desktop\Projects\NBS Bot\NBS-Bot\pydub_mixer.py", line 54, in to_audio_segment
    output[i+sample_offset] += int(samples[i] * samp_multiplier)
OverflowError: Python int too large to convert to C long
```

Turns out that was just clipping, i.e. the sum of two samples the value exceeded `sys.maxsize`. I fixed it by simply setting it to the max value when that happens, and prevented it by applying a negative gain to all segments as soon as they're loaded from each file, then normalizing the final track.

The second issue was a `MemoryError` when `_sync`ing the sounds:

```
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    handle = nbs_to_audio.render_audio(song, output)
  File "C:\Users\Bentroen\Desktop\Projects\NBS Bot\NBS-Bot\nbs_to_audio.py", line 195, in render_audio
    track = mixer.to_audio_segment()
  File "C:\Users\Bentroen\Desktop\Projects\NBS Bot\NBS-Bot\pydub_mixer.py", line 39, in to_audio_segment
    parts = self._sync()
  File "C:\Users\Bentroen\Desktop\Projects\NBS Bot\NBS-Bot\pydub_mixer.py", line 22, in _sync
    segs = AudioSegment.empty()._sync(*segs)
  File "C:\Users\Bentroen\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pydub\audio_segment.py", line 442, in _sync
    for seg in segs
  File "C:\Users\Bentroen\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pydub\audio_segment.py", line 442, in <genexpr>
    for seg in segs
  File "C:\Users\Bentroen\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pydub\audio_segment.py", line 960, in set_frame_rate
    frame_rate, None)
MemoryError
```

This wasn't a problem before because, as I was calling `overlay()` as I generated the segments, the `_sync` function checked _at most_ two segments at once. However, when combining them at the same time, all of a sudden it had to check 20,000 clips at once, and I believe all the iterations caused Python to run out of memory.

I managed to solve this by setting all segments to the same frame rate, channel count, and sample width as soon as they're loaded from the file, and then removing the call to `_sync` completely. I'm working with only around 20 audio files, and it's much more efficient to ensure they're all in sync than it is to check the 20,000+ resulting segments. :)

**Comment by Bentroen** [comment]
Okay, I've just managed to go from 9 minutes down to **23 seconds** by replacing the built-in array with a `numpy` array, and adding the samples with array slicing. This is absolutely insane!! Thank you so much for helping me achieve this result 😄

**Comment by Peda1996** [comment]
> 
> 
> @Peda1996 Yeah, here it is! https://gist.github.com/Bentroen/4df9b8d5d052f9d14bc1a8531fe49994
> 
> Before calling `to_audio_segment()`, make sure all your sounds have the same sample rate by `sync()`ing them previously if necessary, otherwise, a MemoryError may occur as it tries to find a common sample rate. :)

Do you have any idea, what the best way of sampling the pitched nodes (changed frequencies, so that the pitch is changed) would be?

**Comment by Peda1996** [comment]
Well, I decided to use librosa for this task. To speed up the pitch shifting process, I decided, to add a small backup storage, in form of a dictionary.

```
import librosa

bak = {}

# pitcher
def pitcher(sound, note):
    if (sound, note) in bak:
        return bak[(sound,note)]
    
    samples = np.array(sound.get_array_of_samples(), dtype="float32")
    y_shifted = librosa.effects.pitch_shift(samples, sound.frame_rate, n_steps=note-60)
    
    y = np.array(y_shifted, dtype=np.int16)
    new_sound = sound._spawn(y, overrides={'frame_rate': sound.frame_rate, "sample_width":2}).normalize(headroom=1)
    bak[(sound,note)] = new_sound
    return new_sound
```
