### ISSUE TITLE
How to cite this package in my paper?

### ISSUE THREAD

**Issue by kgco** [jiaaro/pydub#552]

**Comment by jiaaro** [comment]
I don't know the convention for citing open source packages, but I would think linking to the tag that represents the version you used would be fine. (i.e., On the main "code" page of this repo, click "Releases", and find the version of pydub you used, click the link to the page where you can download the code for that release, and use that url in your citation)

**Comment by kgco** [comment]
> I don't know the convention for citing open source packages, but I would think linking to the tag that represents the version you used would be fine. (i.e., On the main "code" page of this repo, click "Releases", and find the version of pydub you used, click the link to the page where you can download the code for that release, and use that url in your citation)

The convention for citing open source packages is to cite some paper(s) the author published, and of course, directly citing the GitHub repo or the package website is also common. I'll cite the package as you say. Thanks for your code, it helps me a lot.
