### ISSUE TITLE
AudioSegment from_file with remote file?

### ISSUE THREAD

**Issue by dorkrawk** [jiaaro/pydub#56]
I was trying to use `from_file` with uri to an .mp3 and I found that this does not work.  What do you think about adding the ability to pass in a uri for a remotely located file into the file parameter of `from_file`?

If this make sense as a feature I'd be willing to try to build it out and submit a pull request.

**Comment by hay** [comment]
Note that in Python 3 you need to import `BytesIO` from the `io` library, so the example above should be written as:

```python
from io import BytesIO
from pydub import AudioSegment
import requests

res = requests.get("http://bizvsdev.s3.amazonaws.com/Ep13.mp3")
podcast = AudioSegment.from_file(BytesIO(res.content), "mp3")
```

**Comment by PiusLucky** [comment]
Thanks  @hay that helped.
