### ISSUE TITLE
Error: invalid option: --with-libvorbis

### ISSUE THREAD

**Issue by nicolas-raoul** [jiaaro/pydub#575]
At https://github.com/jiaaro/pydub/blob/master/README.markdown the Mac instructions include these command lines:
```
brew install libav --with-libvorbis --with-sdl --with-theora
```
```
brew install ffmpeg --with-libvorbis --with-sdl2 --with-theora
```

Problem: Both fail with the error below, presumably because [Homebrew stopped supporting the --with-libvorbis option in late 2018](https://stackoverflow.com/a/54939425/226958).
```
Error: invalid option: --with-libvorbis
```
Cheers!

**Comment by OliverSparrow** [comment]
The brew formulas for `libav` and `ffmpeg` now automatically install these files, listing them as dependencies. Just running `brew install libav` or `ffmpeg` alone should work now.
