### ISSUE TITLE
pydub ERRORS on Azure Databricks Runtime 7.3 LTS

### ISSUE THREAD

**Issue by drshyamsundaram** [jiaaro/pydub#584]
### Steps to reproduce
Additional Details
Running the notebook on MS Azure Data bricks runtime : Databricks Runtime 7.3 LTS

Code fragment
from pydub import AudioSegment
from pydub.playback import play
file_test='/dbfs//mnt/test/SoundHelix-Song-1.mp3'
sound = AudioSegment.from_file(file_test, format="mp3")

Need assistance on how to resolve this. We are not able to install anything on the Data Bricks, we can add JAR(s) for libararies. The code works fine on the local jupyter notebook. Facing issue on the databricks. 
### Expected behavior
The file is present and the sound object should have got created.
The pydub, ffmpeg libraries have been setup from pypi

### Actual behavior
We get error message
/databricks/python/lib/python3.7/site-packages/pydub/utils.py:179: RuntimeWarning: Couldn't find ffplay or avplay - defaulting to ffplay, but may not work
  warn("Couldn't find ffplay or avplay - defaulting to ffplay, but may not work", RuntimeWarning)
/databricks/python/lib/python3.7/site-packages/pydub/utils.py:193: RuntimeWarning: Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work
  warn("Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work", RuntimeWarning)
FileNotFoundError: [Errno 2] No such file or directory: 'ffprobe': 'ffprobe'

### Your System configuration
- Python version:3.7.5 
- Pydub version: 0.23.0
- ffmpeg or avlib?: 
- ffmpeg/avlib version:  1.4

### Is there an audio file you can include to help us reproduce?
You can include the audio file in this issue - just put it in a zip file and drag/drop the zip file into the github issue.

**Comment by drshyamsundaram** [comment]
We seem to have resolved the issue.

**Comment by shivek-dubey** [comment]
How this got resolved ? Any help on this ?
