### ISSUE TITLE
Different conversion results on same wav data with pydub and ffmpeg

### ISSUE THREAD

**Issue by v-yunbin** [jiaaro/pydub#636]
I use pydub and ffmpeg to convert a  Multichannel wav  to mono wav, then use ASR model to recognize the mono wav.
The ASR recognise result of  converted wav by pydub  has bad result than the asr result of  converted wav by ffmpeg.
pydub commad: `audio_sound.export(wav_path, format="wav", parameters=["-acodec","pcm_s16le","-ac","1","-ar",str(sample_rate)])
`
ffmpeg commad: `ffmpeg -i wav_path -acodec pcm_s16le -ac 1 -ar sample_rate outwavpath`

### mySystem configuration
- Python version: python 3.8
- Pydub version: 0.25.1
- ffmpeg/avlib version: 3.1

**Comment by JunZhan2000** [comment]
Can you show the two results?
