### ISSUE TITLE
Deploy Pydub with a Flask API?

### ISSUE THREAD

**Issue by NeoPrint3D** [jiaaro/pydub#648]
Is it possible to create a server side application with pydub and flask.

If so how would you set up the ffmpeg in the environment

**Comment by frankiedrake** [comment]
You can install `ffmpeg` in your system using `apt-get`. If deploying with Docker it's quite simple

**Comment by NeoPrint3D** [comment]
Well I was mosty thinking of a serverless environment like vercel edge functions
