### ISSUE TITLE
When running AudioSegment.overlay(), audioop gives error: "Lengths should be the same"

### ISSUE THREAD

**Issue by akpeker** [jiaaro/pydub#679]
### Steps to reproduce
```
  rate, wav_data = wavfile.read(str(wav_path))
  audio = AudioSegment(data=wav_data, frame_rate=rate, sample_width=2, channels=1)
  wnoise = WhiteNoise(sample_rate=audio.frame_rate).to_audio_segment(duration=audio.duration_seconds*1000, volume=-40)
  au_wn = audio.overlay(wnoise)
```
- I used wavfile.read() instead of AudioSegment.from_file() due to other requirements in the project.
- I used duration=audio.duration_seconds*1000 instead of len() because it was not as accurate.

### Expected behavior
The two audio (audio and wnoise) should be overlaid (added) and returned in au_wn

### Actual behavior
Exception is raised by audioop: "Lengths should be the same"

### Your System configuration
- Python version: 3.8.5
- Pydub version: 0.25.1
- ffmpeg or avlib?: No
- ffmpeg/avlib version: ---

### Is there an audio file you can include to help us reproduce?
I used a wav file with 16 bit sample size (16-bit signed integer PCM), 1 channel, 16000 sample rate.
The other file is white noise, generated as above.

### What I Found So Far:
I stepped through the code and checked that the lengths of `seg1` and `seg2` in `overlay()` are the same, up to the point they are passed to `audioop.add()`. But they have different data types: `seg1` (originally loaded from wav, using `wavfile` library) is an `numpy.ndarray` (Array of int16) whereas `seg2` (which is generated by `WhiteNoise` generator) is `bytes`. This may be throwing off `audioop` when calculating number of frames; it is probably expecting `seg1` also to have `bytes`, and then divide by sample size to find number of frames. But `len()` already gives number of frames for a `numpy.ndarray`.

From what I understand, it would be great if either `AudioSegment` converts to `bytes` any other data type that is passed to it (if everything down the road requires data to be `bytes`), or, `overlay` and other methods are able to handle other data types like `numpy arrays`.

I'll appreciate if you let me know there's a fix, a workaround, or let me know if I am doing something wrong above and I need to fix.
Thanks!

**Comment by jiaaro** [comment]
I think you can call tobytes on the ndarray with very little overhead

**Comment by akpeker** [comment]
Thanks! I used 
`audio = AudioSegment(data=bytes(wav_data), frame_rate=rate, sample_width=2, channels=1)`
and everything worked fine. I later discovered sections in the README on converting between numpy data types and byte arrays so that pydub works properly.
