### ISSUE TITLE
is this repo still active?

### ISSUE THREAD

**Issue by Angus1811** [jiaaro/pydub#728]
# is this repo still active?

I am trying to submit a pull request but I need to know if this is still active,

The last commit was in December and most pull requests have not been approved in over 2 months

---

does anyone know anything about this?

**Comment by minglecm** [comment]
I do not know, but I really like your avatar.

**Comment by hydra3333** [comment]
the owner seems to be making a lot of contributions to private repositories, so he's active

**Comment by jiaaro** [comment]
Yeah, just busy with work
