### ISSUE TITLE
Problem with append() and missing frames

### ISSUE THREAD

**Issue by nratter** [jiaaro/pydub#82]
I can't seem to get the append() function to work. It works when i use the '+' operator, but anytime I use append() I get the following error:

Traceback (most recent call last):
  File "./test.py", line 59, in <module>
    sound2_quieter.append(quieter)
  File "/usr/local/lib/python2.7/site-packages/pydub/audio_segment.py", line 663, in append
    xf = seg1[-crossfade:].fade(to_gain=-120, start=0, end=float('inf'))
  File "/usr/local/lib/python2.7/site-packages/pydub/audio_segment.py", line 162, in __getitem__
    "missing frames: %s" % missing_frames)
pydub.exceptions.TooManyMissingFrames: You should never be filling in    more than 2 ms with silence here, missing frames: 3969

**Comment by pranilvora** [comment]
I'm having the same issue. I'm trying to import a bunch of songs and then crossfade them all together into one continuous mix. But everytime I run the code, I get the TooManyMissingFrames Exception. 

from pydub import AudioSegment

songs = [
	AudioSegment.from_mp3("Bang.mp3"),
	AudioSegment.from_mp3("Morning.mp3"),
	AudioSegment.from_mp3("Proxy.mp3"),
	AudioSegment.from_mp3("Ode.mp3"),
	AudioSegment.from_mp3("Above.mp3"),
	AudioSegment.from_mp3("Cuba.mp3"),
	AudioSegment.from_mp3("Born.mp3"),
	AudioSegment.from_mp3("Backlash.mp3"),
	AudioSegment.from_mp3("Mammoth.mp3"),
	AudioSegment.from_mp3("waves.mp3"),
]

continuousSong = AudioSegment.empty()

for song in songs:
	print song
	temp = AudioSegment.empty()
	temp = continuousSong.append(song, crossfade=20000)
	continuousSong = AudioSegment.empty()
	continuousSong = temp
	print continuousSong.duration_seconds

print continuousSong.duration_seconds

continuousSong.export("test5.mp3", format="mp3", bitrate="256k")

**Comment by jiaaro** [comment]
Which line does the exception happen on? Would you be able to share the audio files needed to reproduce the issue?

**Comment by MaxMatti** [comment]
I have the same problem. I tried with multiple files and for me the problem seems to be using the following code:
```finalsong = AudioSegment.empty()
finalsong.append(song)```
I then replaced append with the + operator:
```finalsong = AudioSegment.empty()
finalsong = finalsong + song```
and then it worked. Also using append after that first + operation was no problem.

**Comment by jiaaro** [comment]
I think this is the same as #83 - the assertion error happens because the frame rates don't divide evenly.

**Comment by olivierpons** [comment]
Same problem with silence. This code wont work (it should append 3s silence at the beginning):

```
dst_full = "mymp3.mp3"
fhandle, tmp_name = tempfile.mkstemp(suffix='.tmp.mp3')
os.close(fhandle)
os.chmod(tmp_name, 0777)
final = AudioSegment.silent(float(3 * 1000))
final = final.append(AudioSegment.from_mp3(dst_full))
out_f = open(tmp_name, 'wb')
final.export(out_f, format='mp3')
out_f.close()
os.rename(tmp_name, dst_full)
```

and if you change 
`final = final.append(AudioSegment.from_mp3(dst_full))`
to
`final = final + AudioSegment.from_mp3(dst_full)`

it works
