### ISSUE TITLE
WAVE exporting sometimes fails without format='wav'

### ISSUE THREAD

**Issue by puterleat** [jiaaro/pydub#84]
With pydub==0.9.5
If I say:

```
a=pydub.AudioSegment.from_file('myfile.m4a')
outfile = a[:10000].export('xx.wav')
outfile.close()
```

and then 

```
b=pydub.AudioSegment.from_wav('xx.wav')
```

I get the error: CouldntDecodeError: Decoding failed. ffmpeg returned error code: 1

Trying to play with sox I get:

```
FAIL formats: can't open input file `xx.wav': WAVE: RIFF header not found
```

Am I doing something wrong?

My ffmpeg (if relevant) is:

ffmpeg -v
ffmpeg version 2.5.3 Copyright (c) 2000-2015 the FFmpeg developers
  built on Jan 17 2015 12:08:40 with Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/2.5.3 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-libx264 --enable-libmp3lame --enable-libvo-aacenc --enable-libxvid --enable-vda
  libavutil      54. 15.100 / 54. 15.100
  libavcodec     56. 13.100 / 56. 13.100
  libavformat    56. 15.102 / 56. 15.102
  libavdevice    56.  3.100 / 56.  3.100
  libavfilter     5.  2.103 /  5.  2.103
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100

**Comment by puterleat** [comment]
OK - have solved the problem. I'd thought that pydub inferred the export format from the file extension, but this isn't the case. I'm not actually sure what format is written when export(format=None), but passing in the correct format param (="wav") fixes my issue.

Perhaps the default for format could be documented and/or it could be made a required param?

**Comment by jiaaro** [comment]
@puterleat it tries to infer the format, but relies on ffmpeg to do so. I'm not sure how ffmpeg tries to do that but you're right that it fails sometimes, often inexplicably. I've avoided requiring the parameter so far because for many users it *does* work.

Unfortunately this depends heavily on each user's particular ffmpeg installation :/

**Comment by jiaaro** [comment]
This has probably been resolved and was probably due to python's lack of built-in support for 24-bit wave audio (at the time). Will re-open if it comes up again.
