### ISSUE TITLE
Effect: Invert Audio Proposal

### ISSUE THREAD

**Issue by varunsrin** [jiaaro/pydub#85]
I'm trying to invert the audio in a flac file, and I don't see an easy way to do this with AudioSegment today.

I think this can be accomplished with an 'invert' method in AudioSegment which returns a new segment with the data generated from pyaudioop.mul(self._data, self.sample_width, -1.0).

I can write and submit a PR if you're interested in this feature.

**Comment by varunsrin** [comment]
Tested that the following returns a perfect inverse of the AudioSegment:
```
segment._spawn(data=pyaudioop.mul(segment._data, segment.sample_width, -1.0))
```

**Comment by jiaaro** [comment]
thanks for this :)

 btw, `pyaudioop` is a python implementation of `audioop` in the python stdlib, it is included only for use in other interpreters that do not include audioop (like pypy, though they now include our version :+1:)

**Comment by jiaaro** [comment]
Just cut a new release with improvements and bug fixes of the past few months, including this PR
