### ISSUE TITLE
File length change when converting flac to mp3

### ISSUE THREAD

**Issue by varunsrin** [jiaaro/pydub#86]
I noticed that a flac -> mp3 creates a sample file that isn't the exact same length as the source. There appears to be more empty samples at the start of the file. 

I'm trying to understand how to calculate this delta accurately, so that I can convert an audio file from one format to another, and create a perfect inverse of it.

**Comment by varunsrin** [comment]
So it appears to add 2256 or 2257 samples to the beginning of the track. in a test with a sine chirp, it appeared to be silence.

**Comment by jiaaro** [comment]
The conversion between file types is handled by ffmpeg, if the conversion is not correct that may be a bug in ffmpeg, or in the specific codecs being used.

It's worth pointing out that mp3 is a lossy format, so this isn't entirely unexpected. 2256 samples (assuming 44.1k) is only 5ms of silence
