### ISSUE TITLE
Audio loudness normalization

### ISSUE THREAD

**Issue by peter-moran** [jiaaro/pydub#90]
Peak normalization is not always helpful and it appears that ffmpeg supports loudness normalization, where gain is applied to achieve an average amplitude level. It would be awesome to integrate this into pydub. Others have achieved this, such as https://github.com/kylophone/neg23

**Comment by jiaaro** [comment]
It's an interesting Idea, but it's not that hard to normalize amplitude without any new methods.

`rms` is a measure of average amplitude, which pydub provides as `audio_segment.rms` and also provides a convenience method that provides this value converted to dBFS (`audio_segment.dBFS`)

If you want a group of audio files to be the same average amplitude, basically you choose an average amplitude (in dBFS, `-20` in the example below), and adjust as needed:

```python
from pydub import AudioSegment

# a list containing AudioSegment objects
sounds = […]

def match_target_amplitude(sound, target_dBFS):
    change_in_dBFS = target_dBFS - sound.dBFS
    return sound.apply_gain(change_in_dBFS)

normalized_sounds = [match_target_amplitude(sound, -20.0) for sound in sounds]
```

**Comment by tcarroll2** [comment]
I would like to see more information on how to accomplish this as well.  I have a playlist made up of 75 tracks and desire to have them all normalized to one another.  I'm willing to make a pass through all the files to determine the peak RMS/DBFS, saving that information to a config file, then when each track is sent through AudioSegment the adjustment level could be calculated based upon what was stored for that playlist.

**Comment by TonyDandelion** [comment]
from pydub import effects
_sound = AudioSegment.from_file("./input.wav", "wav")
sound = effects.normalize(_sound)
sound.export("./output.wav", format=file_type)

**Comment by tcarroll2** [comment]
> from pydub import effects
> _sound = AudioSegment.from_file("./input.wav", "wav")
> sound = effects.normalize(_sound)
> sound.export("./output.wav", format="wav")

@TonyDandelion I guess I don't understand the normalize process.  Doesn't there need to be a reference to the "normal" RMS/DBFS to compare to?

Right now I am setting a constant in my code as targetDBFS = 19, then I use a function to either decrease or increase the DBFS of the segment based on the segments current DBFS.

Can you explain to me how the normalize process you recommended would work?

Also, I am using the tracks from my iTunes library, so I am not looking to write the track back to disc as that would remove all my metadata I have stored in my iTunes tracks.

Thanks!

**Comment by TonyDandelion** [comment]
> > from pydub import effects
> > _sound = AudioSegment.from_file("./input.wav", "wav")
> > sound = effects.normalize(_sound)
> > sound.export("./output.wav", format="wav")
> 
> @TonyDandelion I guess I don't understand the normalize process. Doesn't there need to be a reference to the "normal" RMS/DBFS to compare to?
> 
> Right now I am setting a constant in my code as targetDBFS = 19, then I use a function to either decrease or increase the DBFS of the segment based on the segments current DBFS.
> 
> Can you explain to me how the normalize process you recommended would work?
> 
> Also, I am using the tracks from my iTunes library, so I am not looking to write the track back to disc as that would remove all my metadata I have stored in my iTunes tracks.
> 
> Thanks!

hello, the method you mentioned is a kind of amplitude normalization method. The code I write here is to used for standard amplitude normalize. The different between these two method is your method set a target amplitude(which small than the max amplitude) value and make the whole audio scale to the target amplitude, but my method is to scale the whole audio to the max amplitude. In other words, I use max amplitude as my target amplitude, but you set up a personal target amplitude to normalize audio. 

As for the audio storage problem you mentioned, you can directly save it to another device (usb flash drive or portable hard drive) after you process it.

**Comment by tcarroll2** [comment]
> hello, the method you mentioned is a kind of amplitude normalization method. The code I write here is to used for standard amplitude normalize. The different between these two method is your method set a target amplitude(which small than the max amplitude) value and make the whole audio scale to the target amplitude, but my method is to scale the whole audio to the max amplitude. In other words, I use max amplitude as my target amplitude, but you set up a personal target amplitude to normalize audio.
> 
> As for the audio storage problem you mentioned, you can directly save it to another device (usb flash drive or portable hard drive) after you process it.

@TonyDandelion ah, I think I understand now.  I'm normalizing across multiple songs while setting the maximum amplitude that would apply to each song, where the process you're using is you're normalizing the amplitude within a single file.  Correct?  I'm trying to keep the volume from having to be adjusted while each track segment is playing.  It seems to be working for me.  Thanks for your explanation! ~ Tom

**Comment by TonyDandelion** [comment]
you're welcome.  Actually, no matter which single file, there is a max amplitude belong to itself. And for every audio file, this max amplitude is the same. When you listen the music by your smart phone, there is a max  volume. You can not adjust the volume louder and louder. There is a limit.  

As your understand, My method is to scale the amplitude(or volume) of each audio to this max amplitude. It seems that you have understand the difference between these two methods.

**Comment by rhausman** [comment]
Didn't want to open a whole new issue for this related problem, but there may be a bug with some audiosegments not having a .dbFS property.
Example:
`AudioSegment.from_wav(PATH_1+'0.wav').dbFS`
gives
'AttributeError: 'AudioSegment' object has no attribute 'dbFS'
Upon closer inspection, the AudioSegment ONLY has `'sample_width', 'frame_rate', 'channels', 'frame_width', '_data'`, and no other information attached to it.
Has anyone experienced this problem? Thank you in advance.

**Comment by selfcontrol7** [comment]
Hi,

I am experiencing the same issue.
`AttributeError: 'Transcribe' object has no attribute 'dBFS'`

Transcribe is my class.
Please, help.

> Didn't want to open a whole new issue for this related problem, but there may be a bug with some audiosegments not having a .dbFS property.
> Example:
> `AudioSegment.from_wav(PATH_1+'0.wav').dbFS`
> gives
> 'AttributeError: 'AudioSegment' object has no attribute 'dbFS'
> Upon closer inspection, the AudioSegment ONLY has `'sample_width', 'frame_rate', 'channels', 'frame_width', '_data'`, and no other information attached to it.
> Has anyone experienced this problem? Thank you in advance.

**Comment by JpMCarrilho** [comment]
> Didn't want to open a whole new issue for this related problem, but there may be a bug with some audiosegments not having a .dbFS property.
> Example:
> `AudioSegment.from_wav(PATH_1+'0.wav').dbFS`
> gives
> 'AttributeError: 'AudioSegment' object has no attribute 'dbFS'
> Upon closer inspection, the AudioSegment ONLY has `'sample_width', 'frame_rate', 'channels', 'frame_width', '_data'`, and no other information attached to it.
> Has anyone experienced this problem? Thank you in advance.

@rhausman  - Should be `dBFS` instead of `.dbFS`, uppercase B.
