### ISSUE TITLE
Subprocess error using pydub from PyQt

### ISSUE THREAD

**Issue by tsw-apropos** [jiaaro/pydub#92]
When executing an export from wav to mp3 format I get an error from line 479 or audiosegment.py where subprocess.call is made with the stderr being directed to os.devnull.

This then cascades through subprocesses to a final line of 
WindowsError: [Error 6] The handle is invalid.

This same code runs fine under Linux or under windows via command line.

Are you aware of some way in which the pyqt environment might be affecting this call and ways it could be addressed?

**Comment by tsw-apropos** [comment]
Wanted to add that with some digging it seems that the use of the call method without explicitly specifying stdin, stdout and stderr is the source of the problem. However it is worth noting that once stdin is specified, then it seems that the full path to the executable file also need to be specified to avoid a different error.

**Comment by jiaaro** [comment]
I don't know of anything about pyqt that would cause this, but… 

pull request welcome :smiley:

**Comment by jiaaro** [comment]
@tsw-apropos Did you ever learn anything more about this issue?

**Comment by tsw-apropos** [comment]
@jiaaro sorry. I've not had time to look more deeply into this; really busy with other things at the moment.

**Comment by KarlKastor** [comment]
I have a possible fix, but I'm not sure about unwanted consequences: https://github.com/jiaaro/pydub/pull/108

**Comment by KarlKastor** [comment]
@tsw-apropos It works fine on my WIndows machine now: https://github.com/jiaaro/pydub/commit/95325fe0b58fa4fa42efeb290f48a4ed247bb5e5#diff-3075d64f0dccef419a0c80b3ff7ed81f

**Comment by tsw-apropos** [comment]
Did a test with the master and it works for me now.

Thanks
