### ISSUE TITLE
Troubles with 32-bits m4a files ? 

### ISSUE THREAD

**Issue by kursusHC** [jiaaro/pydub#93]
I'm trying to convert .m4a files to wav. 

`audiofile = AudioSegment.from_file(filename)`

It works perfectly for 16-bits files (s16p according to ffmpeg) but for 32-bits files (s32p according to ffmpeg) I get an error :

`Decoding failed. ffmpeg returned error code: {0}".format(retcode)`

I know pydub does not support 24-bits but I thought it was ok with 32-bits. 

Thank you.

**Comment by jiaaro** [comment]
That is true about 24/32 bit - but this error is happening with ffmpeg - the 32 bit audio data isn't even getting returned to pydub.

If it's not too sensitive, would you ming sharing the m4a file?

**Comment by kursusHC** [comment]
I was afraid of that. 

You can find a sample here : 
http://wikisend.com/download/406618/32bitsError.m4a

Thank you very much for your anwser.

**Comment by jiaaro** [comment]
hmm... my install of pydub+ffmpeg is able to open it.

```python
>>> import pydub
>>> sound = pydub.AudioSegment.from_file("./32bitsError.m4a")
>>> len(sound)
1996
>>> s.dBFS
-32.65850794009675
```

I'm on a Mac, with OS X 10.10
latest pydub (0.10.0)
and ffmpeg installed as described in the readme (https://github.com/jiaaro/pydub#getting-ffmpeg-set-up)

**Comment by kursusHC** [comment]
Thanks for the answer. I was running ffmpeg 1 which triggered this error, problem solved with ffmpeg 2.

**Comment by jiaaro** [comment]
@kursusHC I'm glad you were able to sort it out - thanks for posting your solution. I'm sure someone else is going to run into the same thing and find this thread :+1:
