### ISSUE TITLE
Couldn't install ffmpeg or libavcodec-extra-53. Only libav-tools installation works.

### ISSUE THREAD

**Issue by sergiofv** [jiaaro/pydub#95]
I have Ubuntu 14.04 in spanish, so my error is printed in spanish, I'll try to traduce the error which appears in the terminal when i run: sudo apt-get install ffmpeg libavcodec-extra-53

------
El paquete ffmpeg no está disponible, pero algún otro paquete hace referencia
a él. Esto puede significar que el paquete falta, está obsoleto o solo se
encuentra disponible desde alguna otro origen

El paquete libavcodec-extra-53 no está disponible, pero algún otro paquete hace referencia
a él. Esto puede significar que el paquete falta, está obsoleto o solo se
encuentra disponible desde alguna otro origen
Sin embargo, los siguientes paquetes lo reemplazan:
  libav-tools:i386 libav-tools

------

Translation: 
------
ffmpeg is not available, but some other pack makes a reference to it. This could mean that ffmpeg pack is missing, is obsolete or it's only available from another origin.

(There says the same for libavcodec-extra53)

Nevertheless, the following packs could replace them:
 libav-tools:i386 libav-tools

------

So i installed libav-tools as the terminal suggested but when i run this in a python file:

-

from pydub import AudioSegment 
song = AudioSegment.from_file("piano.wav")

#MP3
song.export("piano.mp3", format="mp3")

#Ogg Vorbis
song.export("piano.ogg", format="ogg")

#WMA (windows media) 
song.export("piano.wma", format="wma")

#AAC (advanced audio coding)
song.export("piano.m4a", format="aac")

---- 

It only exports real -listenable- audio files for mp3 and ogg formats, but for wma and aac it only exports 0 bytes files that i can't listen.

I think it occurs because i don't have ffmpeg or libavcodec-extra-53 installed, only libav-tools.

Could you help with this? I have been looking how to fix this error for a while but i couldn't.

PD:  Sorry for my awful english.

**Comment by jiaaro** [comment]
Hi,




First of all, your english is quite good! 




Those formats are not working beause their codecs are missing.




Probably the package you need to install is libavcodec-extra-53 (definitely not ffmpeg, libav-tools is a fork of ffmpeg - they are almost the same thing =D)




You can determine which codecs are available in your installation of libav using this command:




avconv -codecs




I hope this is helpful!




James




PS - I haven't used ubuntu in a few years, so I'm not sure what the new name of the package might be now (if it isn't libavcodec-extra-53 anymore)

**Comment by sergiofv** [comment]
There says the following for aac and wma formats (when i run anconv -codecs):

DEA.L. aac                  AAC (Advanced Audio Coding) (encoders: aac libvo_aacenc )
DEA.L. wmav1             Windows Media Audio 1
DEA.L. wmav2             Windows Media Audio 2

So i tried to install aac package like this:

sudo apt-get install aac libvo_aac

But there says (in the terminal) that there's no package with that name, do i have to download the package? or how do i install the wma and acc packs correctly?

**Comment by kursusHC** [comment]
Follow this advice by @jiaaro :

You need to run 

`apt-cache search libav | grep extra-`

It will return something like 

`libavcodec-extra-56` 

or so, then just run 

`apt-get install libavcodec-extra-56`

replace "56" with the number version you get.

**Comment by jiaaro** [comment]
@kursusHC thanks for filling in the details - I think that might have been somebody else's advice though because it's news to me :smile:

**Comment by sergiofv** [comment]
I just run:

apt-cache search libav | grep extra-

and it returned this:

libavcodec-extra-54 - Libav codec library (additional codecs)
libavdevice-extra-53 - Libav device handling library (transitional package)
libavfilter-extra-3 - Libav filter library (transitional package)
libavformat-extra-54 - Libav file format library (transitional package)
libavutil-extra-52 - Libav utility library (transitional package)
libswscale-extra-2 - Libav video software scaling library (transitional package)

so i execute:

sudo apt-get install libavcodec-extra-54

but the terminal still says that couldn't locate the package. Are you sure that i don't have to download something first?

Thanks anyway

**Comment by sergiofv** [comment]
Finally i could install libavcodec-extra-54. I did it building and upgrading the package since the terminal. But there is the same error:

.wma and .aac files are non-reproducible 0 byte files when i run the python file i showed you a few comments before.

What should i do? Is there another package that contains .wma and .aac formats? 

Once i used faad to decode wav to aac files from the terminal, but i couldn't do this from a script python file.

Any ideas?

**Comment by kursusHC** [comment]
I tried your code on debian stable and debian sid and get the same behavior. 

There is very few docs regarding ffmpeg convert to WMA (I can see why) but for AAC it seems that it's a common problem. (see [here](http://stackoverflow.com/questions/10330215/ffmpeg-too-many-bits-per-frame-requested), [here](http://stackoverflow.com/questions/19774975/unknown-encoder-libfaac-ubuntu-12-04-and-ruby-on-rails-3) or [here](http://unix.stackexchange.com/questions/77687/how-do-i-convert-flac-files-to-aac-preferrably-vbr-320k)).

 When trying to convert to .m4a the classic way I get an error :
 
`$ ffmpeg -i test.wav -strict experimental output.m4a`
`$ [aac @ 0x197c220] Too many bits per frame requested`

That's probably what Pydub send to ffmpeg ? 

I could make it work by reducing the bitrate manually as suggested on the first link : 

`ffmpeg -i piano.wav -b:a 32k -strict experimental output.m4a`

That's ugly of course but there must be others way. More info by looking up "Too many bits per frame requested".

**Comment by sergiofv** [comment]
Thanks you so much for your collab jiaaro and kursusHC.

I finally did what you said to me (reducing bitrates manually to convert the .aac audio files), at least temporary, because nonetheless it's a good option.

Do you know what package should i use (or install, or download) to convert .wav to .ape (Monkey's audio), or you can tell me if i can do that with pydub?

**Comment by jiaaro** [comment]
@sergiofv to be honest I've never heard of it, but pydub supports anything your build of ffmpeg supports.

After a little googling, it looks like ape files can only be _decoded_ but not _encoded_ (so you can open them with `AudioSegment.from_file("/path/to/audio.ape", format="ape")` but not export them a la `sound.export("/path/to/output.ape", format="ape")`)

**Comment by jiaaro** [comment]
note I found this out using `ffmpeg -codecs` at the terminal (or `avconv -codecs` if you're using libav)

`ffmpeg -codecs | head` shows the key:

```
Codecs:
 D..... = Decoding supported
 .E.... = Encoding supported
 ..V... = Video codec
 ..A... = Audio codec
 ..S... = Subtitle codec
 ...I.. = Intra frame-only codec
 ....L. = Lossy compression
 .....S = Lossless compression
```

and I found the ape format using `ffmpeg -codecs | grep ape` — the relevant line being…
```
 D.A..S ape                  Monkey's Audio
```

Decode, Audio, Lossless. note the lack of `E` for encode

**Comment by nazar212** [comment]
How To Fix E: Unable to locate kali linux-restricted-extras

**Comment by martinjobb** [comment]
```apt-get install libav-tools libav-tools``` worked for me on Debian GNU/Linux 8 (jessie)

**Comment by Franck-Dernoncourt** [comment]
`sudo apt-get install libav-tools libav-tools` also worked for me, on Ubuntu 16.04 LTS x64 (used 316 MB of additional disk space though).
